-- Generated by `jwc v1 gen-sql`. Do not edit.
-- Emission order: schema, enum type, table, foreign key, index, trigger, view, comment.

-- ── Schema ──
CREATE SCHEMA IF NOT EXISTS audit;

CREATE SCHEMA IF NOT EXISTS auth;

CREATE SCHEMA IF NOT EXISTS billing;

CREATE SCHEMA IF NOT EXISTS org;


-- ── EnumType ──
CREATE TYPE billing.billing_interval AS ENUM ('monthly', 'yearly');

CREATE TYPE billing.invoice_status AS ENUM ('draft', 'open', 'paid', 'void');

CREATE TYPE billing.payment_status AS ENUM ('pending', 'succeeded', 'failed', 'refunded');

CREATE TYPE billing.subscription_status AS ENUM ('trialing', 'active', 'past_due', 'canceled');

CREATE TYPE org.member_role AS ENUM ('owner', 'admin', 'member', 'viewer');


-- ── Table ──
CREATE TABLE audit.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_id bigint,
    actor_id bigint,
    action varchar(60) NOT NULL,
    route varchar(200) NOT NULL,
    entity_id bigint,
    payload jsonb,
    ip inet,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE auth.accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(255) NOT NULL,
    display_name varchar(80) NOT NULL,
    password_hash varchar(255) NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT uq_accounts__email UNIQUE (email),
    CONSTRAINT ck_accounts__email__pattern CHECK (email ~ '^[^@]+@[^@]+\.[^@]+$'),
    CONSTRAINT ck_accounts__display_name__minlength CHECK (char_length(display_name) >= 2)
);

CREATE TABLE auth.api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_id bigint NOT NULL,
    name varchar(80) NOT NULL,
    key_hash varchar(64) NOT NULL,
    scopes text[] NOT NULL,
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_api_keys PRIMARY KEY (id),
    CONSTRAINT uq_api_keys__key_hash UNIQUE (key_hash)
);

CREATE TABLE auth.sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    user_agent varchar(255),
    ip inet,
    expires_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id),
    CONSTRAINT uq_sessions__token_hash UNIQUE (token_hash)
);

CREATE TABLE billing.counters (
    name varchar(40) NOT NULL,
    value bigint DEFAULT 0 NOT NULL,
    CONSTRAINT pk_counters PRIMARY KEY (name)
);

CREATE TABLE billing.invoice_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice_id bigint NOT NULL,
    description varchar(200) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(14, 2) NOT NULL,
    CONSTRAINT pk_invoice_lines PRIMARY KEY (id),
    CONSTRAINT ck_invoice_lines__description__minlength CHECK (char_length(description) >= 1),
    CONSTRAINT ck_invoice_lines__quantity__min CHECK (quantity >= 1),
    CONSTRAINT ck_invoice_lines__unit_price__min CHECK (unit_price >= 0)
);

CREATE TABLE billing.invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_id bigint NOT NULL,
    subscription_id bigint,
    number varchar(20) NOT NULL,
    amount numeric(14, 2) NOT NULL,
    currency varchar(3) DEFAULT 'USD' NOT NULL,
    status billing.invoice_status DEFAULT 'draft'::billing.invoice_status NOT NULL,
    issued_at timestamptz,
    due_at timestamptz,
    paid_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uq_invoices__number UNIQUE (number),
    CONSTRAINT ck_invoices__amount__min CHECK (amount >= 0),
    CONSTRAINT ck_invoices__status_paid_at__1 CHECK ((paid_at IS NULL) OR (status = 'paid'))
);

CREATE TABLE billing.payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice_id bigint NOT NULL,
    provider varchar(20) NOT NULL,
    provider_ref varchar(120) NOT NULL,
    amount numeric(14, 2) NOT NULL,
    status billing.payment_status DEFAULT 'pending'::billing.payment_status NOT NULL,
    failure_code varchar(60),
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT uq_payments__provider_ref UNIQUE (provider_ref),
    CONSTRAINT ck_payments__amount__min CHECK (amount >= 0)
);

CREATE TABLE billing.plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(40) NOT NULL,
    name varchar(80) NOT NULL,
    price numeric(14, 2) NOT NULL,
    currency varchar(3) DEFAULT 'USD' NOT NULL,
    interval billing.billing_interval DEFAULT 'monthly'::billing.billing_interval NOT NULL,
    features jsonb,
    active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_plans PRIMARY KEY (id),
    CONSTRAINT uq_plans__code UNIQUE (code),
    CONSTRAINT ck_plans__code__pattern CHECK (code ~ '^[a-z0-9_]+$'),
    CONSTRAINT ck_plans__price__min CHECK (price >= 0),
    CONSTRAINT ck_plans__currency__pattern CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE TABLE billing.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    status billing.subscription_status DEFAULT 'trialing'::billing.subscription_status NOT NULL,
    current_period_start timestamptz NOT NULL,
    current_period_end timestamptz NOT NULL,
    cancel_at timestamptz,
    canceled_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id),
    CONSTRAINT ck_subscriptions__current_period_end_current_period_start__1 CHECK (current_period_end > current_period_start),
    CONSTRAINT ck_subscriptions__status_canceled_at__2 CHECK ((canceled_at IS NULL) OR (status = 'canceled'))
);

CREATE TABLE org.invites (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_id bigint NOT NULL,
    email varchar(255) NOT NULL,
    role org.member_role DEFAULT 'member'::org.member_role NOT NULL,
    token_hash varchar(64) NOT NULL,
    invited_by bigint NOT NULL,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_invites PRIMARY KEY (id),
    CONSTRAINT uq_invites__token_hash UNIQUE (token_hash),
    CONSTRAINT ck_invites__email__pattern CHECK (email ~ '^[^@]+@[^@]+\.[^@]+$')
);

CREATE TABLE org.members (
    org_id bigint NOT NULL,
    account_id bigint NOT NULL,
    role org.member_role DEFAULT 'member'::org.member_role NOT NULL,
    joined_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (org_id, account_id)
);

CREATE TABLE org.orgs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug varchar(40) NOT NULL,
    name varchar(120) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_orgs PRIMARY KEY (id),
    CONSTRAINT uq_orgs__slug UNIQUE (slug),
    CONSTRAINT ck_orgs__slug__pattern CHECK (slug ~ '^[a-z0-9-]{3,40}$'),
    CONSTRAINT ck_orgs__name__minlength CHECK (char_length(name) >= 2)
);


-- ── ForeignKey ──
ALTER TABLE audit.events ADD CONSTRAINT fk_events__org_id
    FOREIGN KEY (org_id) REFERENCES org.orgs (id)
    ON DELETE SET NULL;

ALTER TABLE audit.events ADD CONSTRAINT fk_events__actor_id
    FOREIGN KEY (actor_id) REFERENCES auth.accounts (id)
    ON DELETE SET NULL;

ALTER TABLE auth.api_keys ADD CONSTRAINT fk_api_keys__org_id
    FOREIGN KEY (org_id) REFERENCES org.orgs (id)
    ON DELETE CASCADE;

ALTER TABLE auth.sessions ADD CONSTRAINT fk_sessions__account_id
    FOREIGN KEY (account_id) REFERENCES auth.accounts (id)
    ON DELETE CASCADE;

ALTER TABLE billing.invoice_lines ADD CONSTRAINT fk_invoice_lines__invoice_id
    FOREIGN KEY (invoice_id) REFERENCES billing.invoices (id)
    ON DELETE CASCADE;

ALTER TABLE billing.invoices ADD CONSTRAINT fk_invoices__org_id
    FOREIGN KEY (org_id) REFERENCES org.orgs (id);

ALTER TABLE billing.invoices ADD CONSTRAINT fk_invoices__subscription_id
    FOREIGN KEY (subscription_id) REFERENCES billing.subscriptions (id)
    ON DELETE SET NULL;

ALTER TABLE billing.payments ADD CONSTRAINT fk_payments__invoice_id
    FOREIGN KEY (invoice_id) REFERENCES billing.invoices (id);

ALTER TABLE billing.subscriptions ADD CONSTRAINT fk_subscriptions__org_id
    FOREIGN KEY (org_id) REFERENCES org.orgs (id)
    ON DELETE CASCADE;

ALTER TABLE billing.subscriptions ADD CONSTRAINT fk_subscriptions__plan_id
    FOREIGN KEY (plan_id) REFERENCES billing.plans (id);

ALTER TABLE org.invites ADD CONSTRAINT fk_invites__org_id
    FOREIGN KEY (org_id) REFERENCES org.orgs (id)
    ON DELETE CASCADE;

ALTER TABLE org.invites ADD CONSTRAINT fk_invites__invited_by
    FOREIGN KEY (invited_by) REFERENCES auth.accounts (id);

ALTER TABLE org.members ADD CONSTRAINT fk_members__org_id
    FOREIGN KEY (org_id) REFERENCES org.orgs (id)
    ON DELETE CASCADE;

ALTER TABLE org.members ADD CONSTRAINT fk_members__account_id
    FOREIGN KEY (account_id) REFERENCES auth.accounts (id)
    ON DELETE CASCADE;


-- ── Index ──
CREATE INDEX ix_events__org_id_created_at
    ON audit.events (org_id, created_at);

CREATE INDEX ix_events__route_created_at
    ON audit.events (route, created_at);

CREATE INDEX ix_accounts__created_at
    ON auth.accounts (created_at);

CREATE INDEX ix_api_keys__org_id__4db1527c
    ON auth.api_keys (org_id)
    WHERE revoked_at IS NULL;

CREATE INDEX ix_sessions__account_id_expires_at
    ON auth.sessions (account_id, expires_at);

CREATE INDEX ix_invoice_lines__invoice_id
    ON billing.invoice_lines (invoice_id);

CREATE INDEX ix_invoices__org_id_status
    ON billing.invoices (org_id, status);

CREATE INDEX ix_invoices__org_id_issued_at_id
    ON billing.invoices (org_id, issued_at DESC, id DESC);

CREATE INDEX ix_invoices__due_at__d4a78ad7
    ON billing.invoices (due_at)
    WHERE status = 'open';

CREATE INDEX ix_payments__invoice_id_status
    ON billing.payments (invoice_id, status);

CREATE INDEX ix_plans__active_code
    ON billing.plans (active, code);

CREATE UNIQUE INDEX uq_subscriptions__org_id__d671f003
    ON billing.subscriptions (org_id)
    WHERE status <> 'canceled';

CREATE INDEX ix_subscriptions__status_current_period_end
    ON billing.subscriptions (status, current_period_end);

CREATE UNIQUE INDEX uq_invites__org_id_email__03f9d236
    ON org.invites (org_id, email)
    WHERE accepted_at IS NULL;

CREATE INDEX ix_invites__expires_at
    ON org.invites (expires_at);

CREATE INDEX ix_members__account_id
    ON org.members (account_id);


-- ── Trigger ──
CREATE OR REPLACE FUNCTION billing.tg_subscriptions__touch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

CREATE TRIGGER tg_subscriptions__touch
    BEFORE UPDATE ON billing.subscriptions
    FOR EACH ROW EXECUTE FUNCTION billing.tg_subscriptions__touch();


-- ── View ──
CREATE VIEW billing.invoice_detail AS
SELECT t0.id AS id,
       t0.org_id AS org_id,
       t0.number AS number,
       t0.amount AS amount,
       t0.currency AS currency,
       t0.status AS status,
       t0.issued_at AS issued_at,
       t0.due_at AS due_at,
       t0.paid_at AS paid_at,
       coalesce(t1_agg.data, '[]'::json) AS lines,
       coalesce(t2_agg.data, '[]'::json) AS payments
  FROM billing.invoices t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'description', t1.description, 'quantity', t1.quantity, 'unit_price', t1.unit_price::text) AS j
        FROM billing.invoice_lines t1
        WHERE t1.invoice_id = t0.id
        ORDER BY t1.id
        LIMIT 200) c
  ) t1_agg ON true
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t2.id::text, 'provider', t2.provider, 'provider_ref', t2.provider_ref, 'amount', t2.amount::text, 'status', t2.status, 'created_at', t2.created_at) AS j
        FROM billing.payments t2
        WHERE t2.invoice_id = t0.id
        ORDER BY t2.created_at DESC
        LIMIT 20) c
  ) t2_agg ON true;

CREATE VIEW billing.subscription_detail AS
SELECT t0.id AS id,
       t0.org_id AS org_id,
       t0.status AS status,
       t0.current_period_start AS current_period_start,
       t0.current_period_end AS current_period_end,
       t0.cancel_at AS cancel_at,
       CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'code', t1.code, 'name', t1.name, 'price', t1.price::text, 'currency', t1.currency, 'interval', t1.interval) END AS plan,
       t1.id AS plan__id,
       t1.code AS plan__code,
       t1.name AS plan__name,
       t1.price AS plan__price,
       t1.currency AS plan__currency,
       t1.interval AS plan__interval,
       CASE WHEN t2.id IS NULL THEN NULL ELSE json_build_object('id', t2.id::text, 'slug', t2.slug, 'name', t2.name) END AS org,
       t2.id AS org__id,
       t2.slug AS org__slug,
       t2.name AS org__name
  FROM billing.subscriptions t0
  LEFT JOIN billing.plans t1 ON t1.id = t0.plan_id
  LEFT JOIN org.orgs t2 ON t2.id = t0.org_id;

CREATE VIEW org.member_access AS
SELECT t0.org_id AS org_id,
       t0.account_id AS account_id,
       t0.role AS role,
       CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'slug', t1.slug, 'name', t1.name) END AS org,
       t1.id AS org__id,
       t1.slug AS org__slug,
       t1.name AS org__name
  FROM org.members t0
  LEFT JOIN org.orgs t1 ON t1.id = t0.org_id;

CREATE VIEW org.org_billing_summary AS
SELECT t0.id AS org_id,
       t0.slug AS slug,
       count(t1.id)::int AS invoice_count,
       (count(t1.id) FILTER (WHERE t1.status = 'open'::billing.invoice_status))::int AS open_count,
       sum(t1.amount) FILTER (WHERE t1.status = 'paid'::billing.invoice_status) AS paid_total,
       min(t1.due_at) FILTER (WHERE t1.status = 'open'::billing.invoice_status) AS oldest_due
  FROM org.orgs t0
  LEFT JOIN billing.invoices t1 ON t1.org_id = t0.id
  GROUP BY t0.id, t0.slug;

CREATE VIEW org.org_with_members AS
SELECT t0.id AS id,
       t0.slug AS slug,
       t0.name AS name,
       t0.created_at AS created_at,
       coalesce(t1_agg.data, '[]'::json) AS members
  FROM org.orgs t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('role', t1.role, 'joined_at', t1.joined_at, 'account', CASE WHEN t2.id IS NULL THEN NULL ELSE json_build_object('id', t2.id::text, 'email', t2.email, 'display_name', t2.display_name) END) AS j
        FROM org.members t1
        LEFT JOIN auth.accounts t2 ON t2.id = t1.account_id
        WHERE t1.org_id = t0.id
        ORDER BY t1.joined_at
        LIMIT 200) c
  ) t1_agg ON true;


-- ── Comment ──
COMMENT ON TABLE audit.events IS 'Append-only. Every FK is `on delete set null` so a deleted org never
blocks the log, and every column that could be missing is nullable —
an `after` block cannot recover from a failed insert (middleware.md §5.5).';

COMMENT ON TABLE auth.accounts IS 'One human identity. Email is the login handle and is immutable.';

COMMENT ON COLUMN auth.accounts.id IS 'Surrogate key. Exposed to clients as a string (types.md §2.3).';

COMMENT ON COLUMN auth.accounts.password_hash IS 'Argon2id. Never leaves the database (schema.md §3.1).';

COMMENT ON TABLE auth.sessions IS 'Bearer-token sessions. `token_hash` is an unsalted SHA-256 of a
32-byte CSPRNG token, so it can be looked up by equality
(builtins.md §6).';

COMMENT ON TABLE billing.counters IS 'Monotonic counters. `update … first` emits FOR UPDATE, which is what
makes this safe under concurrency (writes.md §4). Sequences are
DEFERRED-17.';

COMMENT ON COLUMN billing.payments.provider_ref IS 'The provider''s idempotency key. `on conflict do nothing` on this
constraint is what makes webhook redelivery safe (writes.md §2.3).';

COMMENT ON TABLE billing.plans IS 'Money is `numeric`, never an integer count of cents (types.md §2.1).
`price` is per `interval`.';

COMMENT ON TABLE org.orgs IS 'Tenant. Every billing and audit row hangs off one of these.';

COMMENT ON COLUMN org.orgs.slug IS 'URL-safe handle. Immutable after creation.';

COMMENT ON VIEW billing.invoice_detail IS 'Two `as many` children. A paged select against this view compiles to
the two-stage form so children are aggregated for the page only
(queries.md §8.3).';

COMMENT ON VIEW org.member_access IS 'The membership gate reads `role` off this view, which is legal because
a view is a projection and therefore a Record (types.md §5.3).';

COMMENT ON VIEW org.org_billing_summary IS 'Bare join + aggregates + group by. No `as many` in the same query,
which is what keeps it out of E0532 (queries.md §6.2).';

COMMENT ON VIEW org.org_with_members IS 'One org with its members, each member carrying its account.
`account` attaches to `members` because its `on` clause names only
`Members` besides the joined table (queries.md §4.4).

The `limit` is not decoration: without it the collection is unbounded
(`W0501`), and an org with fifty thousand members would be built in
memory to answer one detail request.';

