-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view CustomerTotals ──
-- $1 = OrderStatus.paid :: s.order_status
-- $2 = OrderStatus.paid :: s.order_status
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('customer_id', t0.id::text, 'name', t0.name, 'order_count', count(t1.id), 'paid_count', count(t1.id) FILTER (WHERE t1.status = ($1::text)::s.order_status), 'paid_total', (sum(t1.amount) FILTER (WHERE t1.status = ($2::text)::s.order_status))::text, 'item_total', sum(t1.items)::text, 'avg_amount', avg(t1.amount)::text, 'first_order', min(t1.id)::text, 'last_order', max(t1.id)::text) AS j
  FROM s.customers t0
  LEFT JOIN s.orders t1 ON t1.customer_id = t0.id
  GROUP BY t0.id, t0.name) q

-- ── view BusyCustomers ──
-- $1 = 2 :: bigint
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('customer_id', t0.id::text, 'order_count', count(t1.id)) AS j
  FROM s.customers t0
  LEFT JOIN s.orders t1 ON t1.customer_id = t0.id
  GROUP BY t0.id
  HAVING count(t1.id) > ($1::text)::bigint
  ORDER BY t0.id) q

-- ── view CustomerActivity ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('customer_id', t0.id::text, 'orders', count(DISTINCT t1.id), 'notes', count(DISTINCT t2.id)) AS j
  FROM s.customers t0
  LEFT JOIN s.orders t1 ON t1.customer_id = t0.id
  LEFT JOIN s.notes t2 ON t2.customer_id = t0.id
  GROUP BY t0.id) q
