-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view AccountRows ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'email', t0.email, 'balance', t0.balance::text, 'created_at', t0.created_at) AS j
  FROM s.accounts t0
  ORDER BY t0.id) q
