-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── Orgs.active_admins ──
-- $1 = 10 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'name', t0.name, 'region', t0.region, 'admins', coalesce(t1_agg.data, '[]'::json)) AS j
  FROM s.orgs t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'role', t1.role) AS j
        FROM s.members t1
        WHERE t1.org_id = t0.id AND t1.removed IS NULL
        ORDER BY t1.id
        LIMIT ($1::text)::int) c
  ) t1_agg ON true
  WHERE t0.region IS NOT NULL
  ORDER BY t0.name NULLS LAST) q
