-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view SessionAccount ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'account', json_build_object('id', t1.id::text, 'email', t1.email)) AS j
  FROM s.sessions t0
  JOIN s.accounts t1 ON t1.id = t0.account_id) q

-- ── view SessionProfile ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'profile', CASE WHEN t1.account_id IS NULL THEN NULL ELSE json_build_object('account_id', t1.account_id::text, 'nickname', t1.nickname) END) AS j
  FROM s.sessions t0
  LEFT JOIN s.profiles t1 ON t1.account_id = t0.account_id) q
