-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view OrgRoster ──
-- $1 = 50 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'name', t0.name, 'members', coalesce(t1_agg.data, '[]'::json)) AS j
  FROM s.orgs t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'role', t1.role, 'account', CASE WHEN t2.id IS NULL THEN NULL ELSE json_build_object('id', t2.id::text, 'email', t2.email) END) AS j
        FROM s.members t1
        LEFT JOIN s.accounts t2 ON t2.id = t1.account_id
        WHERE t1.org_id = t0.id
        ORDER BY t1.id
        LIMIT ($1::text)::int) c
  ) t1_agg ON true) q
