-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── Rosters.by_org_name ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('account_id', t0.account_id::text, 'org', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'name', t1.name) END) AS j
  FROM s.members t0
  LEFT JOIN s.orgs t1 ON t1.id = t0.org_id
  ORDER BY t1.name, t0.id) q

-- ── Rosters.by_binding_name ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('account_id', t0.account_id::text, 'org', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'name', t1.name) END) AS j
  FROM s.members t0
  LEFT JOIN s.orgs t1 ON t1.id = t0.org_id
  ORDER BY t1.name, t0.id) q
