-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view AccountManager ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'email', t0.email, 'manager', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'email', t1.email) END) AS j
  FROM s.accounts t0
  LEFT JOIN s.accounts t1 ON t1.id = t0.manager_id) q

-- ── view AccountReports ──
-- $1 = 100 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'email', t0.email, 'reports', coalesce(t1_agg.data, '[]'::json)) AS j
  FROM s.accounts t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'email', t1.email) AS j
        FROM s.accounts t1
        WHERE t1.manager_id = t0.id
        ORDER BY t1.email
        LIMIT ($1::text)::int) c
  ) t1_agg ON true) q
