-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view OrgBoard ──
-- $1 = 20 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'name', t0.name, 'notes', coalesce(t1_agg.data, '[]'::json), 'tags', coalesce(t2_agg.data, '[]'::json)) AS j
  FROM s.orgs t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'body', t1.body) AS j
        FROM s.notes t1
        WHERE t1.org_id = t0.id
        ORDER BY t1.created_at DESC
        LIMIT ($1::text)::int) c
  ) t1_agg ON true
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t2.id::text, 'label', t2.label) AS j
        FROM s.tags t2
        WHERE t2.org_id = t0.id
        ORDER BY t2.label) c
  ) t2_agg ON true) q
