-- Generated by jwc
CREATE TABLE IF NOT EXISTS "brand_entity" (
    "id" integer NOT NULL,
    "name" varchar(255) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "car_entity" (
    "id" integer NOT NULL,
    "model" varchar(255) NOT NULL,
    "year" integer NOT NULL,
    "brandId" integer NOT NULL,
    "colorId" integer NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "color_entity" (
    "id" integer NOT NULL,
    "name" varchar(255) NOT NULL,
    "hex" varchar(7) NOT NULL,
    PRIMARY KEY ("id")
);

