//! `jwc openapi` — emit an OpenAPI 3.0.3 spec for the current project.
//!
//! This is the v1, best-effort generator tracked alongside the existing
//! `jwc swagger` command (which targets the richer OpenAPI 3.1 surface).
//! `openapi` is intentionally narrower:
//!
//! - Outputs `openapi: "3.0.3"` so it slots straight into tooling that
//!   hasn't moved to 3.1 yet (codegen, mock servers, contract-test runners).
//! - Walks the project's `Program` and, per HTTP route, surfaces path
//!   params, query params (from the handler's typed signature), and a
//!   request body for `POST` / `PUT` / `PATCH`.
//! - Adds a `200` response (referencing the handler return type if it
//!   matches a known model), plus `400` when `validate body` is present
//!   and `401` when any middleware on the route is named `Auth*`.
//! - Skips WebSocket and SSE routes — OpenAPI 3.0 doesn't model them.
//! - Emits one `components.schemas.<Name>` per model.
//!
//! `build_openapi_value` is exposed as a pure function so the integration
//! test in `tests/openapi.rs` can drive it without touching the filesystem.

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use serde_json::{json, Map, Value};

use crate::ast::{
    FieldDecl, FunctionDecl, ModelDecl, ModelKind, Program, RouteDecl, RouteProtocol, Stmt,
};
use crate::project;

/// CLI entry: load the project rooted at `path` (or cwd), build the
/// OpenAPI value, then print or write it.
pub fn run(path: Option<PathBuf>, out: Option<PathBuf>, pretty: bool) -> Result<()> {
    let start = match path {
        Some(p) => p,
        None => std::env::current_dir()?,
    };
    let root = project::find_project_root(&start)
        .with_context(|| "jwc openapi must run inside a JWC project")?;
    let loaded = project::load_project_from_root(&root)?;

    let doc = build_openapi_value(&loaded.program);
    let serialised = if pretty {
        serde_json::to_string_pretty(&doc)?
    } else {
        serde_json::to_string(&doc)?
    };

    if let Some(out_path) = out {
        fs::write(&out_path, serialised + "\n")
            .with_context(|| format!("write {}", out_path.display()))?;
        println!(
            "Wrote {} ({} paths)",
            out_path.display(),
            loaded.program.routes.len()
        );
    } else {
        println!("{serialised}");
    }
    Ok(())
}

/// Pure-function builder. No I/O, no project lookup — given a validated
/// `Program`, produce the OpenAPI 3.0.3 JSON value. Useful for testing and
/// for callers that already hold a `Program` in memory.
pub fn build_openapi_value(program: &Program) -> Value {
    let mut doc = Map::new();
    doc.insert("openapi".into(), Value::String("3.0.3".to_string()));
    doc.insert(
        "info".into(),
        json!({
            "title": "JWC API",
            "version": "0.0.0",
            "description": "Generated by `jwc openapi` from JWC source — do not hand-edit.",
        }),
    );
    doc.insert("paths".into(), Value::Object(build_paths(program)));
    doc.insert(
        "components".into(),
        json!({
            "schemas": build_component_schemas(program),
        }),
    );
    Value::Object(doc)
}

fn build_paths(program: &Program) -> Map<String, Value> {
    use std::collections::BTreeMap;

    let mut by_path: BTreeMap<String, Map<String, Value>> = BTreeMap::new();
    for route in &program.routes {
        if !matches!(route.protocol, RouteProtocol::Http) {
            continue; // WebSocket / SSE intentionally skipped.
        }
        if !route.namespace.is_empty() {
            continue; // sub-namespace routes need a `mount` to be active.
        }
        let openapi_path = normalize_path(&route.path);
        let method = route.method.to_ascii_lowercase();
        let op = route_to_operation(program, route);
        by_path.entry(openapi_path).or_default().insert(method, op);
    }
    by_path
        .into_iter()
        .map(|(p, ops)| (p, Value::Object(ops)))
        .collect()
}

fn normalize_path(path: &str) -> String {
    if path.starts_with('/') {
        path.to_string()
    } else {
        format!("/{path}")
    }
}

fn route_to_operation(program: &Program, route: &RouteDecl) -> Value {
    let handler_fn = route
        .handler
        .as_deref()
        .and_then(|name| program.functions.iter().find(|f| f.name == name));

    let mut op = Map::new();

    // Summary: namespace + handler name (or the route's method+path when no handler).
    let summary = build_summary(route);
    op.insert("summary".into(), Value::String(summary));

    let path_params = extract_path_params(&route.path);

    let mut parameters: Vec<Value> = Vec::new();
    for pname in &path_params {
        let ty = handler_fn
            .and_then(|f| f.params.iter().find(|p| &p.name == pname))
            .and_then(|p| p.ty.as_deref())
            .unwrap_or("string");
        parameters.push(json!({
            "name": pname,
            "in": "path",
            "required": true,
            "schema": jwc_type_to_openapi(program, ty),
        }));
    }

    // For GET (and DELETE, HEAD, OPTIONS — methods without a body), handler-typed
    // params that aren't path placeholders become query params. For POST/PUT/PATCH
    // they roll into the request body schema instead.
    let method_upper = route.method.to_ascii_uppercase();
    let has_body_method = matches!(method_upper.as_str(), "POST" | "PUT" | "PATCH");

    let mut leftover_params: Vec<&crate::ast::TypedParam> = Vec::new();
    if let Some(f) = handler_fn {
        for p in &f.params {
            if path_params.iter().any(|pp| pp == &p.name) {
                continue;
            }
            leftover_params.push(p);
        }
    }

    if !has_body_method {
        for p in &leftover_params {
            let ty = p.ty.as_deref().unwrap_or("string");
            parameters.push(json!({
                "name": p.name,
                "in": "query",
                "required": false,
                "schema": jwc_type_to_openapi(program, ty),
            }));
        }
    }

    if !parameters.is_empty() {
        op.insert("parameters".into(), Value::Array(parameters));
    }

    if has_body_method {
        let body_schema = build_request_body_schema(program, &leftover_params);
        op.insert(
            "requestBody".into(),
            json!({
                "required": true,
                "content": {
                    "application/json": { "schema": body_schema }
                }
            }),
        );
    }

    op.insert(
        "responses".into(),
        Value::Object(build_responses(program, route, handler_fn)),
    );

    Value::Object(op)
}

fn build_summary(route: &RouteDecl) -> String {
    let handler = route.handler.as_deref().unwrap_or("");
    let ns = if route.namespace.is_empty() {
        String::new()
    } else {
        route.namespace.join(".")
    };
    if handler.is_empty() && ns.is_empty() {
        format!("{} {}", route.method, normalize_path(&route.path))
    } else if ns.is_empty() {
        handler.to_string()
    } else if handler.is_empty() {
        ns
    } else {
        format!("{ns}.{handler}")
    }
}

fn build_request_body_schema(program: &Program, params: &[&crate::ast::TypedParam]) -> Value {
    if params.is_empty() {
        return json!({ "type": "object" });
    }
    let mut props = Map::new();
    let mut required: Vec<Value> = Vec::new();
    for p in params {
        let ty = p.ty.as_deref().unwrap_or("string");
        props.insert(p.name.clone(), jwc_type_to_openapi(program, ty));
        required.push(Value::String(p.name.clone()));
    }
    let mut schema = json!({
        "type": "object",
        "properties": props,
    });
    if !required.is_empty() {
        schema["required"] = Value::Array(required);
    }
    schema
}

fn build_responses(
    program: &Program,
    route: &RouteDecl,
    handler_fn: Option<&FunctionDecl>,
) -> Map<String, Value> {
    let mut responses = Map::new();
    responses.insert("200".into(), build_ok_response(program, handler_fn));

    if has_validate_body(&route.body) {
        responses.insert(
            "400".into(),
            json!({
                "description": "Bad Request",
                "content": {
                    "application/json": { "schema": { "type": "object" } }
                }
            }),
        );
    }
    if route.middlewares.iter().any(|m| m.starts_with("Auth")) {
        responses.insert(
            "401".into(),
            json!({
                "description": "Unauthorized",
                "content": {
                    "application/json": { "schema": { "type": "object" } }
                }
            }),
        );
    }
    responses
}

fn build_ok_response(program: &Program, handler_fn: Option<&FunctionDecl>) -> Value {
    // If the handler's return-type annotation names a known class/entity,
    // surface a `$ref` to it; otherwise emit a permissive object schema.
    let schema = handler_fn
        .and_then(|f| f.return_type.as_deref())
        .filter(|rt| program.models.iter().any(|m| m.name == *rt))
        .map(|rt| json!({ "$ref": format!("#/components/schemas/{rt}") }))
        .unwrap_or_else(|| json!({ "type": "object" }));

    json!({
        "description": "OK",
        "content": {
            "application/json": { "schema": schema }
        }
    })
}

fn has_validate_body(stmts: &[Stmt]) -> bool {
    // clippy 1.95+ would rewrite the `if walk(body) { return true; }` arms
    // below as match guards, but that loses the early-return clarity and
    // would still need the same fallthrough on `false`. Suppress per-function.
    #![allow(clippy::collapsible_match)]
    fn walk(stmts: &[Stmt]) -> bool {
        for s in stmts {
            match s {
                Stmt::ValidateBody { .. } => return true,
                Stmt::If {
                    then_body,
                    else_body,
                    ..
                } => {
                    if walk(then_body) {
                        return true;
                    }
                    if let Some(eb) = else_body {
                        if walk(eb) {
                            return true;
                        }
                    }
                }
                Stmt::While { body, .. }
                | Stmt::ForIn { body, .. }
                | Stmt::Transaction { body } => {
                    if walk(body) {
                        return true;
                    }
                }
                Stmt::Try {
                    body, catch_body, ..
                } => {
                    if walk(body) || walk(catch_body) {
                        return true;
                    }
                }
                _ => {}
            }
        }
        false
    }
    walk(stmts)
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = path.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'{' {
            if let Some(close) = path[i + 1..].find('}') {
                let name = &path[i + 1..i + 1 + close];
                if !name.is_empty() {
                    out.push(name.to_string());
                }
                i += close + 2;
                continue;
            }
        }
        i += 1;
    }
    out
}

fn build_component_schemas(program: &Program) -> Map<String, Value> {
    let mut out = Map::new();
    for model in &program.models {
        if !model.namespace.is_empty() {
            continue; // surface only root-namespace models
        }
        out.insert(model.name.clone(), model_to_schema(program, model));
    }
    out
}

fn model_to_schema(program: &Program, model: &ModelDecl) -> Value {
    let mut props = Map::new();
    let mut required: Vec<Value> = Vec::new();
    for f in &model.fields {
        props.insert(f.name.clone(), field_to_schema(program, f));
        if !f.is_nullable {
            required.push(Value::String(f.name.clone()));
        }
    }
    let kind_label = match model.kind {
        ModelKind::Entity => "entity",
        ModelKind::Class => "class",
    };
    let mut schema = json!({
        "type": "object",
        "title": model.name,
        "description": format!("JWC {kind_label} `{}`", model.name),
        "properties": props,
    });
    if !required.is_empty() {
        schema["required"] = Value::Array(required);
    }
    schema
}

fn field_to_schema(program: &Program, f: &FieldDecl) -> Value {
    let inner = jwc_type_to_openapi(program, &f.ty.name);
    if f.is_nullable {
        // OpenAPI 3.0 only supports `nullable: true`, not `type: [..., "null"]`.
        let mut s = inner;
        if let Value::Object(ref mut m) = s {
            m.insert("nullable".into(), Value::Bool(true));
        }
        s
    } else {
        inner
    }
}

/// Map JWC primitive / model names to an OpenAPI 3.0 schema fragment.
/// Unknown names are assumed to be a component schema (`$ref` form). When
/// a `program` is available, only emit `$ref` for names that exist as a
/// model — anything else falls back to `string` so the generated doc
/// stays well-formed even on partial input.
fn jwc_type_to_openapi(program: &Program, name: &str) -> Value {
    match name.to_ascii_lowercase().as_str() {
        "string" | "str" | "text" | "varchar" => json!({ "type": "string" }),
        "int" | "integer" => json!({ "type": "integer", "format": "int32" }),
        "bigint" | "long" => json!({ "type": "integer", "format": "int64" }),
        "double" | "float" | "number" => json!({ "type": "number", "format": "double" }),
        "decimal" => json!({ "type": "string", "format": "decimal" }),
        "bool" | "boolean" => json!({ "type": "boolean" }),
        "uuid" => json!({ "type": "string", "format": "uuid" }),
        "datetime" | "timestamp" => json!({ "type": "string", "format": "date-time" }),
        "json" => json!({ "type": "object" }),
        "bytes" | "byte[]" => json!({ "type": "string", "format": "byte" }),
        other => {
            if program.models.iter().any(|m| m.name == other) {
                json!({ "$ref": format!("#/components/schemas/{}", other) })
            } else {
                json!({ "type": "string" })
            }
        }
    }
}
