//! v0.22.0 acceptance: DDL is deterministic, matches a reviewed golden file
//! byte for byte, and applies to a real Postgres.
//!
//! The golden files under `tests/ddl_golden/` are the artefact the DBA test
//! is read against (ROADMAP §1): a Postgres engineer reads the `.jwc` and
//! states the DDL, and the `.sql` here is what the compiler actually emits.
//! Regenerate with:
//!
//! ```bash
//! for f in tests/ddl_golden/cases/*.jwc; do
//!   cargo run --bin jwc -- v1 gen-sql "$f" > "${f%.jwc}.sql"
//! done
//! cargo run --bin jwc -- v1 gen-sql docs/spec/v1/sample > tests/ddl_golden/sample.sql
//! ```
//!
//! The apply half is opt-in: set `JWC_V1_PG` to a psql connection string.
//! **A SKIPPED line is not a pass** — the same rule the Postgres integration
//! suite has carried since 0.6.x.

use jwc::{ddl, model, workspace::Workspace};
use std::path::{Path, PathBuf};

mod common;
use common::run_psql;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn cases() -> Vec<PathBuf> {
    let dir = repo_root().join("tests/ddl_golden/cases");
    let mut out: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("tests/ddl_golden/cases")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("jwc"))
        .collect();
    out.sort();
    out
}

fn generate(path: &Path, explain: bool) -> String {
    let ws = Workspace::load(path).expect("load");
    assert!(
        !ws.has_parse_errors(),
        "{} did not parse:\n{}",
        path.display(),
        ws.parse_errors().join("")
    );
    let built = model::build(&ws);
    let errors: Vec<String> = built
        .diags
        .iter()
        .filter(|(_, d)| d.severity == jwc::diag::Severity::Error)
        .map(|(loc, d)| ws.render(*loc, d))
        .collect();
    assert!(
        errors.is_empty(),
        "{} has schema errors:\n{}",
        path.display(),
        errors.join("")
    );
    let statements = ddl::emit(&built.model);
    ddl::render(&ws, &statements, explain)
}

#[test]
fn goldens_match_byte_for_byte() {
    let mut mismatches = Vec::new();
    for case in cases() {
        let golden_path = case.with_extension("sql");
        let want = std::fs::read_to_string(&golden_path)
            .unwrap_or_else(|_| panic!("missing golden {}", golden_path.display()));
        let got = generate(&case, false);
        if got.trim_end() != want.trim_end() {
            mismatches.push(format!(
                "=== {} ===\n--- want ---\n{want}\n--- got ---\n{got}",
                case.display()
            ));
        }
    }
    assert!(mismatches.is_empty(), "{}", mismatches.join("\n\n"));
}

#[test]
fn the_sample_golden_matches() {
    let want = std::fs::read_to_string(repo_root().join("tests/ddl_golden/sample.sql"))
        .expect("tests/ddl_golden/sample.sql");
    let got = generate(&repo_root().join("docs/spec/v1/sample"), false);
    assert_eq!(
        got.trim_end(),
        want.trim_end(),
        "regenerate: cargo run --bin jwc -- v1 gen-sql docs/spec/v1/sample > tests/ddl_golden/sample.sql"
    );
}

#[test]
fn generation_is_deterministic() {
    // Two runs on the same source must be byte-identical. Anything that
    // iterates a HashMap breaks this, and it breaks silently: the DDL is
    // still correct, but every `migrate new` produces a phantom diff.
    for case in cases()
        .into_iter()
        .chain([repo_root().join("docs/spec/v1/sample")])
    {
        let a = generate(&case, false);
        let b = generate(&case, false);
        assert_eq!(a, b, "{} is not deterministic", case.display());
    }
}

#[test]
fn every_statement_carries_a_source_location() {
    // `--explain` is the DBA test's other half: each statement names the
    // declaration that produced it. A statement with no location is a
    // compiler bug (schema.md §9.1).
    //
    // Statements are separated by a blank line — but only a blank line
    // that is really between statements. A `COMMENT ON` carries the
    // declaration's doc text verbatim and prose has paragraphs in it, so
    // the scanner tracks whether it is inside a string literal or a `$$`
    // function body. SQL doubles a quote to escape it, which keeps the
    // parity, so counting is enough.
    let path = repo_root().join("docs/spec/v1/sample");
    let explained = generate(&path, true);
    let mut located = 0usize;
    let mut in_statement = false;
    let mut in_quote = false;
    let mut in_body = false;
    for line in explained.lines() {
        if !in_quote && !in_body {
            if line.starts_with("-- ── ")
                || line.starts_with("-- Generated by")
                || line.starts_with("-- Emission order:")
            {
                continue;
            }
            if line.trim().is_empty() {
                in_statement = false;
                continue;
            }
            if line.starts_with("-- ") && line.contains(".jwc:") {
                assert!(!in_statement, "two locations for one statement:\n{line}");
                located += 1;
                in_statement = true;
                continue;
            }
            assert!(in_statement, "statement with no source location:\n{line}");
        }
        if line.matches("$$").count() % 2 == 1 {
            in_body = !in_body;
        }
        if !in_body && line.matches('\'').count() % 2 == 1 {
            in_quote = !in_quote;
        }
    }

    // Compared against what the emitter actually produced, so the number
    // cannot drift out from under the test.
    let ws = Workspace::load(&path).expect("load");
    let emitted = ddl::emit(&model::build(&ws).model).len();
    assert_eq!(located, emitted, "every statement carries a location");
    assert!(emitted > 40, "expected the sample's DDL, saw {emitted}");
}

#[test]
fn emission_order_is_the_specified_order() {
    // schema.md §9: schema, enum type, table, every FK in a separate pass,
    // index, trigger, comment. The FK pass is what makes the sample's
    // auth → org → auth cycle emittable, so its position is load-bearing.
    let sql = generate(&repo_root().join("docs/spec/v1/sample"), false);
    let order: Vec<&str> = sql
        .lines()
        .filter(|l| l.starts_with("-- ── "))
        .map(|l| l.trim_start_matches("-- ── ").trim_end_matches(" ──"))
        .collect();
    assert_eq!(
        order,
        vec![
            "Schema",
            "EnumType",
            "Table",
            "ForeignKey",
            "Index",
            "Trigger",
            "View",
            "Comment"
        ]
    );

    // No FK inside a CREATE TABLE.
    let table_section = sql
        .split("-- ── ForeignKey ──")
        .next()
        .expect("table section");
    assert!(
        !table_section.contains("FOREIGN KEY"),
        "foreign keys must be emitted in their own pass, not inline"
    );
}

#[test]
fn private_columns_are_still_created() {
    // `private` hides a column from responses (schema.md §3.1); it is not a
    // storage decision. The column must exist.
    let sql = generate(&repo_root().join("docs/spec/v1/sample"), false);
    assert!(sql.contains("password_hash varchar(255) NOT NULL"));
    assert!(sql.contains("token_hash varchar(64) NOT NULL"));
}

#[test]
fn identity_not_bigserial() {
    let sql = generate(&repo_root().join("docs/spec/v1/sample"), false);
    assert!(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
    assert!(
        !sql.contains("bigserial"),
        "schema.md §2.3 forbids bigserial"
    );
    assert!(!sql.contains("nextval("), "no explicit sequence defaults");
}

#[test]
fn money_is_numeric() {
    // N2: a billing language with no money type was not acceptable.
    let sql = generate(&repo_root().join("docs/spec/v1/sample"), false);
    assert!(sql.contains("amount numeric(14, 2)"));
    assert!(sql.contains("price numeric(14, 2)"));
    assert!(sql.contains("unit_price numeric(14, 2)"));
}

// ---------------------------------------------------------------- apply

/// Applies every golden to a real Postgres. Opt-in via `JWC_V1_PG`, which
/// is a psql connection string (`postgres://…` or `-h /path -p 5432 -U u`).
#[test]
fn goldens_apply_to_postgres() {
    let Ok(conn) = std::env::var("JWC_V1_PG") else {
        eprintln!(
            "SKIPPED goldens_apply_to_postgres — set JWC_V1_PG to a psql \
             connection string. A SKIPPED line is not a pass."
        );
        return;
    };

    let mut files: Vec<PathBuf> = cases().iter().map(|c| c.with_extension("sql")).collect();
    files.push(repo_root().join("tests/ddl_golden/sample.sql"));

    for (i, f) in files.iter().enumerate() {
        let db = format!("jwc_v1_golden_{i}");
        run_psql(
            &conn,
            "postgres",
            &["-c", &format!("DROP DATABASE IF EXISTS {db}")],
        );
        run_psql(&conn, "postgres", &["-c", &format!("CREATE DATABASE {db}")]);
        let out = run_psql(
            &conn,
            &db,
            &[
                "-q",
                "-v",
                "ON_ERROR_STOP=1",
                "-f",
                &f.display().to_string(),
            ],
        );
        assert!(
            out.trim().is_empty(),
            "{} did not apply cleanly:\n{out}",
            f.display()
        );
        run_psql(&conn, "postgres", &["-c", &format!("DROP DATABASE {db}")]);
    }
}
