//! Sprint 8 smoke test for `jwc build --native --emit-rust-source`.
//!
//! Drives the public `native_build::emit_rust_source` entry point on a
//! minimal in-memory program and asserts the dump (a) is non-empty,
//! (b) starts with the generated-by header, and (c) lands at the expected
//! `bin/<profile>/<app>.generated.rs` path.

use std::fs;

use jwc::native_build::emit_rust_source;
use jwc::parser::{parse_program, validate_program};

fn parse(src: &str) -> jwc::ast::Program {
    let p = parse_program(src).expect("parse");
    validate_program(&p).expect("validate");
    p
}

#[test]
fn emit_rust_source_writes_to_expected_path_with_header() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        function main() {
            print("hi");
        }
    "#;
    let program = parse(src);

    let out = emit_rust_source(&program, root, "emittest", false).expect("emit");

    assert_eq!(
        out,
        root.join("bin").join("debug").join("emittest.generated.rs")
    );
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(!body.is_empty(), "generated source is empty");
    assert!(
        body.starts_with("// Generated by jwc build --native. DO NOT EDIT."),
        "missing generated-by header; got: {}",
        &body[..body.len().min(200)]
    );
}

#[test]
fn emit_rust_source_supports_full_nav_eager_load() {
    // Native AOT parity (Epic 4): `with` eager-load reuses the interpreter's
    // json-subquery SQL, so every nav kind — ordered has-many, belongs-to, and
    // two-level nested — codegens correlated json subqueries read back through
    // `jwc_db_query_json`, NOT a compile_error rejection.
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        dbcontext AppDb : Postgres;
        entity User of AppDb {
            id int pk;
            name varchar(64);
            posts: List<Post> via Post.userId orderby createdAt desc;
        }
        entity Post of AppDb {
            id int pk;
            userId int;
            authorId int;
            createdAt datetime;
            author: User via authorId;
        }
        entity Project of AppDb {
            id int pk;
            boards: List<Board> via Board.projectId;
        }
        entity Board of AppDb {
            id int pk;
            projectId int;
            lanes: List<Lane> via Lane.boardId;
        }
        entity Lane of AppDb { id int pk; boardId int; }
        function ordered() { return select User with posts from AppDb.User; }
        function belongs() { return select Post with author from AppDb.Post; }
        function nested() { return select Project with boards.lanes from AppDb.Project first; }
        function main() { ordered(); belongs(); nested(); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, root, "navs", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // The eager-load result is read through the json-text helper.
    assert!(
        body.contains("jwc_db_query_json"),
        "nav selects must use the json-text read path"
    );
    // Correlated json subqueries + ordered collection.
    assert!(
        body.contains("json_agg"),
        "expected json_agg nav subqueries"
    );
    assert!(
        body.contains("DESC"),
        "ordered nav must carry ORDER BY ... DESC"
    );
    // Two-level nested `with boards.lanes` merges the child as a jsonb key.
    assert!(
        body.contains("jsonb_build_object('lanes'"),
        "nested nav must merge the child collection"
    );
    // None of these navs may hit a native rejection any more.
    assert!(
        !body.contains("does not yet support"),
        "belongs-to / ordered / nested navs should no longer be rejected"
    );
    assert!(
        !body.contains("interpreter-only"),
        "nested nav should no longer be interpreter-only in native"
    );
}

#[test]
fn emit_rust_source_supports_optional_predicate() {
    // Native AOT parity (Epic 4): `status ==? @s` (optional predicate) can't be
    // dropped per-call in static SQL, so it codegens an equivalent guard that
    // treats NULL / empty as "no filter" — not a compile_error rejection.
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        dbcontext AppDb : Postgres;
        entity Task of AppDb {
            id int pk;
            status varchar(32);
        }
        function filter(s) {
            return select Task from AppDb.Task where Task.status ==? @s;
        }
        function main() { filter(""); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, root, "optpred", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // String column: NULL or empty short-circuits the predicate to TRUE.
    assert!(
        body.contains("($1 IS NULL OR $1 = '' OR"),
        "optional string predicate must emit the NULL/empty guard"
    );
    assert!(
        !body.contains("WHERE operator"),
        "`==?` must not fall through to the unsupported-operator bail"
    );
}

#[test]
fn emit_rust_source_respects_release_profile_dir() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let program = parse(r#"function main() { print("x"); }"#);

    let out = emit_rust_source(&program, root, "rel_app", true).expect("emit");

    assert_eq!(
        out,
        root.join("bin")
            .join("release")
            .join("rel_app.generated.rs")
    );
    assert!(out.exists(), "release output not written");
}
