//! Sprint 8 follow-up: golden parity harness between the interpreter
//! (`runner::run_main`) and the native AOT codegen (`native_build::emit_rust_source`).
//!
//! For each small in-test JWC program we:
//!   1. parse + validate the source,
//!   2. run it through the async interpreter and capture stdout,
//!   3. emit the equivalent Rust source into a `TempDir`,
//!   4. assert the emitted Rust file is well-formed and contains the
//!      builtin call shapes (e.g. `jwc_print`) that, once compiled, would
//!      produce the same output the interpreter just produced.
//!
//! v1 deliberately stops short of shelling out to `cargo build` on the
//! emitted source. A full compile-and-run parity check (v2) needs a live
//! cargo toolchain at test time and ~30s/program — out of scope here.
//! Instead we treat the interpreter's stdout as the source of truth and
//! verify the codegen *would* emit equivalent calls.

use std::fs;

use jwc::native_build::emit_rust_source;
use jwc::parser::{parse_program, validate_program};
use jwc::runner::run_main;

struct Case {
    name: &'static str,
    source: &'static str,
    /// Exact interpreter stdout we expect (acts as the golden value).
    expected_output: &'static str,
    /// Substrings that MUST appear in the emitted Rust source. These are
    /// the builtin call shapes that make the native binary produce the
    /// same stdout as the interpreter once compiled.
    expected_emit_contains: &'static [&'static str],
}

const CASES: &[Case] = &[
    Case {
        name: "hello",
        source: r#"
            function main() {
                print("hello");
            }
        "#,
        expected_output: "hello\n",
        expected_emit_contains: &["jwc_print(", "\"hello\""],
    },
    Case {
        name: "add",
        source: r#"
            function add(a: int, b: int): int {
                return a + b;
            }
            function main() {
                print(add(2, 3));
            }
        "#,
        expected_output: "5\n",
        expected_emit_contains: &["jwc_print(", "fn add"],
    },
];

#[tokio::test]
async fn interpreter_and_native_emit_agree_for_small_programs() {
    for case in CASES {
        // 1. parse + validate
        let program = parse_program(case.source)
            .unwrap_or_else(|e| panic!("[{}] parse failed: {e}", case.name));
        validate_program(&program)
            .unwrap_or_else(|e| panic!("[{}] validate failed: {e}", case.name));

        // 2. run the interpreter — this is the golden output
        let result = run_main(&program)
            .await
            .unwrap_or_else(|e| panic!("[{}] interpreter run failed: {e}", case.name));
        assert_eq!(
            result.output, case.expected_output,
            "[{}] interpreter stdout drifted from golden value",
            case.name
        );

        // 3. emit Rust source into an isolated temp dir
        let tmp =
            tempfile::tempdir().unwrap_or_else(|e| panic!("[{}] tempdir failed: {e}", case.name));
        let out_path = emit_rust_source(&program, tmp.path(), case.name, false)
            .unwrap_or_else(|e| panic!("[{}] emit_rust_source failed: {e}", case.name));

        // 4. well-formed emission
        assert!(
            out_path.exists(),
            "[{}] emit_rust_source returned a path that doesn't exist: {}",
            case.name,
            out_path.display()
        );
        let body = fs::read_to_string(&out_path)
            .unwrap_or_else(|e| panic!("[{}] read emitted file failed: {e}", case.name));
        assert!(
            !body.is_empty(),
            "[{}] emitted Rust source is empty",
            case.name
        );
        assert!(
            body.starts_with("// Generated by jwc build --native. DO NOT EDIT."),
            "[{}] emitted source missing generated-by header; head: {}",
            case.name,
            &body[..body.len().min(120)]
        );
        assert!(
            body.contains("fn main"),
            "[{}] emitted source is missing a `fn main` entry point",
            case.name
        );

        // 5. builtin call-shape parity: every expected substring must appear
        for needle in case.expected_emit_contains {
            assert!(
                body.contains(needle),
                "[{}] emitted Rust source missing expected substring `{}`",
                case.name,
                needle
            );
        }
    }
}
