//! Sprint 8 smoke test for `jwc build --native --emit-rust-source`.
//!
//! Drives the public `native_build::emit_rust_source` entry point on a
//! minimal in-memory program and asserts the dump (a) is non-empty,
//! (b) starts with the generated-by header, and (c) lands at the expected
//! `bin/<profile>/<app>.generated.rs` path.

use std::fs;

use jwc::native_build::emit_rust_source;
use jwc::parser::{parse_program, validate_program};

fn parse(src: &str) -> jwc::ast::Program {
    let p = parse_program(src).expect("parse");
    validate_program(&p).expect("validate");
    p
}

#[test]
fn emit_rust_source_writes_to_expected_path_with_header() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        function main() {
            print("hi");
        }
    "#;
    let program = parse(src);

    let out = emit_rust_source(&program, root, "emittest", false).expect("emit");

    assert_eq!(
        out,
        root.join("bin").join("debug").join("emittest.generated.rs")
    );
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(!body.is_empty(), "generated source is empty");
    assert!(
        body.starts_with("// Generated by jwc build --native. DO NOT EDIT."),
        "missing generated-by header; got: {}",
        &body[..body.len().min(200)]
    );
}

#[test]
fn emit_rust_source_supports_full_nav_eager_load() {
    // Native AOT parity (Epic 4): `with` eager-load reuses the interpreter's
    // json-subquery SQL, so every nav kind — ordered has-many, belongs-to, and
    // two-level nested — codegens correlated json subqueries read back through
    // `jwc_db_query_json`, NOT a compile_error rejection.
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        dbcontext AppDb : Postgres;
        entity User of AppDb {
            id int pk;
            name varchar(64);
            posts: List<Post> via Post.userId orderby createdAt desc;
        }
        entity Post of AppDb {
            id int pk;
            userId int;
            authorId int;
            createdAt datetime;
            author: User via authorId;
        }
        entity Project of AppDb {
            id int pk;
            boards: List<Board> via Board.projectId;
        }
        entity Board of AppDb {
            id int pk;
            projectId int;
            lanes: List<Lane> via Lane.boardId;
        }
        entity Lane of AppDb { id int pk; boardId int; }
        function ordered() { return select User with posts from AppDb.User; }
        function belongs() { return select Post with author from AppDb.Post; }
        function nested() { return select Project with boards.lanes from AppDb.Project first; }
        function main() { ordered(); belongs(); nested(); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, root, "navs", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // The eager-load result is read through the json-text helper.
    assert!(
        body.contains("jwc_db_query_json"),
        "nav selects must use the json-text read path"
    );
    // Correlated json subqueries + ordered collection.
    assert!(
        body.contains("json_agg"),
        "expected json_agg nav subqueries"
    );
    assert!(
        body.contains("DESC"),
        "ordered nav must carry ORDER BY ... DESC"
    );
    // Two-level nested `with boards.lanes` merges the child as a jsonb key.
    assert!(
        body.contains("jsonb_build_object('lanes'"),
        "nested nav must merge the child collection"
    );
    // None of these navs may hit a native rejection any more.
    assert!(
        !body.contains("does not yet support"),
        "belongs-to / ordered / nested navs should no longer be rejected"
    );
    assert!(
        !body.contains("interpreter-only"),
        "nested nav should no longer be interpreter-only in native"
    );
}

#[test]
fn emit_rust_source_supports_optional_predicate() {
    // Native AOT parity (Epic 4): `status ==? @s` (optional predicate) can't be
    // dropped per-call in static SQL, so it codegens an equivalent guard that
    // treats NULL / empty as "no filter" — not a compile_error rejection.
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        dbcontext AppDb : Postgres;
        entity Task of AppDb {
            id int pk;
            status varchar(32);
        }
        function filter(s) {
            return select Task from AppDb.Task where Task.status ==? @s;
        }
        function main() { filter(""); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, root, "optpred", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // String column: NULL or empty short-circuits the predicate to TRUE.
    assert!(
        body.contains("($1 IS NULL OR $1 = '' OR"),
        "optional string predicate must emit the NULL/empty guard"
    );
    assert!(
        !body.contains("WHERE operator"),
        "`==?` must not fall through to the unsupported-operator bail"
    );
}

#[test]
fn emit_rust_source_supports_grouped_aggregation_and_join() {
    // Native AOT parity (Epic 4): grouped aggregation, explicit JOIN, and
    // aliased columns all codegen via the shared SQL builders — no rejection.
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        dbcontext AppDb : Postgres;
        entity Task of AppDb {
            id int pk;
            projectId int;
            columnId int;
            status varchar(32);
        }
        entity Column of AppDb {
            id int pk;
            name varchar(64);
        }
        function byStatus(projectId: int) {
            return select Task { status, total: count(*) } from AppDb.Task
                where Task.projectId == @projectId
                group by status orderby status asc;
        }
        function byColumn(projectId: int) {
            return select Task { columnId, columnName: Column.name, total: count(*) }
                from AppDb.Task
                join Column on Column.id == Task.columnId
                where Task.projectId == @projectId
                group by Task.columnId, Column.name
                orderby Task.columnId asc;
        }
        function main() { byStatus(1); byColumn(1); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, root, "agg", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // Single-table grouped aggregation.
    assert!(
        body.contains("count(*) AS \\\"total\\\""),
        "aggregate term must be emitted"
    );
    assert!(body.contains("GROUP BY"), "group by must be emitted");
    // Explicit JOIN with table-alias qualification + aliased joined column.
    assert!(
        body.contains("JOIN \\\"column\\\" j0 ON"),
        "join must be emitted with a j0 alias"
    );
    assert!(
        body.contains("j0.\\\"name\\\" AS \\\"columnName\\\""),
        "aliased joined column must be qualified"
    );
    // WHERE on the main entity is qualified to t under a join.
    assert!(
        body.contains("t.\\\"projectId\\\""),
        "join-query WHERE must qualify the main entity column"
    );
    assert!(
        body.contains("jwc_db_query_json"),
        "grouped/join selects use the json-text read path"
    );
    assert!(
        !body.contains("does not support aggregate"),
        "grouped aggregation / JOIN should no longer be rejected"
    );
}

#[test]
fn emit_rust_source_respects_release_profile_dir() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let program = parse(r#"function main() { print("x"); }"#);

    let out = emit_rust_source(&program, root, "rel_app", true).expect("emit");

    assert_eq!(
        out,
        root.join("bin")
            .join("release")
            .join("rel_app.generated.rs")
    );
    assert!(out.exists(), "release output not written");
}

/// The AOT path has to agree with the interpreter on `having`: aggregate
/// comparisons emit the aggregate, and a projection alias is resolved to the
/// aggregate it names (Postgres rejects an output alias in `HAVING`).
#[test]
fn emit_rust_source_lowers_having_aggregates_and_aliases() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let program = parse(
        r#"
        dbcontext AppDb : Postgres;
        entity Sale of AppDb {
            id int pk;
            country varchar(64);
            amount int;
        }

        function busy() {
            return select Sale { country, total: count(*) } from AppDb.Sale
                group by Sale.country
                having count(*) > 2 and sum(Sale.amount) >= 500;
        }

        function viaAlias() {
            return select Sale { country, total: count(*) } from AppDb.Sale
                group by Sale.country
                having total > 2;
        }

        function main() { busy(); viaAlias(); }
    "#,
    );

    let out = emit_rust_source(&program, root, "having_app", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    assert!(
        body.contains("HAVING (COUNT(*) > $1 AND SUM("),
        "aggregate comparison must lower to the SQL aggregate; got:\n{}",
        having_lines(&body)
    );
    // The alias query names no aggregate of its own — if the alias were passed
    // through as a column the emitted SQL would say `\"total\"` here, which is
    // what fails at the database.
    assert!(
        !body.contains("HAVING \\\"total\\\""),
        "a projection alias must not reach SQL as a column; got:\n{}",
        having_lines(&body)
    );
    assert!(
        body.matches("HAVING COUNT(*) > $1").count() >= 1,
        "the alias query must lower to COUNT(*); got:\n{}",
        having_lines(&body)
    );
}

fn having_lines(body: &str) -> String {
    body.lines()
        .filter(|l| l.contains("HAVING"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// `distinct` has to reach the AOT SQL too — the interpreter and the compiled
/// binary must not disagree on how many rows a query returns.
#[test]
fn emit_rust_source_lowers_select_distinct() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let program = parse(
        r#"
        dbcontext AppDb : Postgres;
        entity Sale of AppDb {
            id int pk;
            country varchar(64);
        }

        function countries() {
            return select distinct Sale { country } from AppDb.Sale;
        }

        function all() {
            return select Sale { country } from AppDb.Sale;
        }

        function main() { countries(); all(); }
    "#,
    );

    let out = emit_rust_source(&program, root, "distinct_app", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    assert!(
        body.contains("SELECT DISTINCT \\\"country\\\" FROM \\\"sale\\\""),
        "`select distinct` must lower to SELECT DISTINCT; got:\n{}",
        select_lines(&body)
    );
    assert!(
        body.contains("SELECT \\\"country\\\" FROM \\\"sale\\\""),
        "the non-distinct query must stay non-distinct; got:\n{}",
        select_lines(&body)
    );
}

fn select_lines(body: &str) -> String {
    body.lines()
        .filter(|l| l.contains("FROM \\\"sale\\\""))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Guard on the `is_async_builtin` list in `native_build.rs`.
///
/// Every `file.*` / `directory.*` / `console.read` builtin is an `async fn`
/// in the prelude, so codegen must emit `.await` on the call. Missing an
/// entry in that `matches!` produces a `Future`-vs-`V` type error inside
/// the *generated* crate, which only surfaces on a real `jwc build
/// --native` — neither the conformance suite nor `native_parity` compiles
/// emitted source. This test is the cheap version of that check.
///
/// `console.write` / `console.error` are deliberately synchronous, so they
/// must NOT get `.await`; that direction is asserted too, because adding
/// them to the async list would break the build just as thoroughly.
#[test]
fn emit_rust_source_awaits_async_io_builtins() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        function main() {
            console.write("a");
            console.error("b");
            let line = console.read();
            directory.create("d");
            let t = file.read("d/x.txt");
            file.write("d/x.txt", "y");
            file.append("d/x.txt", "z");
            let ex = file.exists("d/x.txt");
            let sz = file.size("d/x.txt");
            let ls = file.lines("d/x.txt");
            file.copy("d/x.txt", "d/y.txt");
            file.move("d/y.txt", "d/z.txt");
            file.delete("d/z.txt");
            let names = directory.list("d");
            let de = directory.exists("d");
            directory.delete("d");
            // RS256 verification fetches the issuer's JWKS, so it suspends.
            let claims = jwt_verify_jwks("tok", "https://idp.test/jwks");
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, root, "iotest", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    for name in [
        "jwc_b_jwt_verify_jwks",
        "jwc_b_console_read",
        "jwc_b_file_read",
        "jwc_b_file_write",
        "jwc_b_file_append",
        "jwc_b_file_exists",
        "jwc_b_file_delete",
        "jwc_b_file_copy",
        "jwc_b_file_move",
        "jwc_b_file_size",
        "jwc_b_file_lines",
        "jwc_b_directory_list",
        "jwc_b_directory_create",
        "jwc_b_directory_exists",
        "jwc_b_directory_delete",
    ] {
        // The call site inside `user_main`, not the `async fn` definition
        // the prelude contributes — hence the `(` and the `.await` check on
        // the same emitted line.
        let called = body
            .lines()
            .filter(|l| l.contains(&format!("{name}(")) && !l.contains(&format!("fn {name}")))
            .collect::<Vec<_>>();
        assert!(!called.is_empty(), "{name} was never called in the output");
        for line in called {
            assert!(
                line.contains(".await"),
                "{name} emitted without `.await` — add it to `is_async_builtin` \
                 in native_build.rs. Line: {line}"
            );
        }
    }

    // Sync direction, checked on a separate program so each console call is
    // the only thing on its emitted line. In the program above the
    // arguments are literals, but a nested async call would put an unrelated
    // `.await` on the same line and make the assertion meaningless.
    let tmp2 = tempfile::tempdir().expect("tempdir");
    let sync_src = r#"
        function main() {
            console.write("a");
            console.error("b");
        }
    "#;
    let program2 = parse(sync_src);
    let out2 = emit_rust_source(&program2, tmp2.path(), "synctest", false).expect("emit");
    let body2 = fs::read_to_string(&out2).expect("read generated");

    for name in ["jwc_b_console_write", "jwc_b_console_error"] {
        let called = body2
            .lines()
            .filter(|l| l.contains(&format!("{name}(")) && !l.contains(&format!("fn {name}")))
            .collect::<Vec<_>>();
        assert!(!called.is_empty(), "{name} was never called in the output");
        for line in called {
            assert!(
                !line.contains(".await"),
                "{name} must not be awaited — it is synchronous, and adding it \
                 to `is_async_builtin` breaks the generated crate. Line: {line}"
            );
        }
    }
}

/// Same guard as above, for the Redis built-ins — plus a check that the
/// Redis prelude fragment actually gets concatenated.
///
/// The coverage assertion is the point: the exercised set is compared
/// against every `redis_*` row in `BUILTIN_DEFS`, so adding a tenth Redis
/// built-in without teaching `is_async_builtin` about it fails here rather
/// than in a user's `jwc build --native`.
#[test]
fn emit_rust_source_awaits_redis_builtins() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        function main() {
            let on = redis_enabled();
            let up = redis_ping();
            let v = redis_get("k");
            redis_set("k", "v", 60);
            let n = redis_del("k");
            let has = redis_exists("k");
            let c = redis_incr("hits");
            let ok = redis_expire("hits", 60);
            let r = redis_eval("return 1", "[]", "[]");
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "redistest", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // The prelude fragment must be present, or every call below resolves
    // to nothing and the generated crate fails on unknown functions.
    assert!(
        body.contains("fn jwc_redis_pool()"),
        "native_prelude_redis.rs.in was not concatenated — check \
         `program_uses_redis` / REDIS_BUILTINS in native_build.rs"
    );

    let exercised: Vec<&str> = jwc::builtins::BUILTIN_DEFS
        .iter()
        .map(|d| d.name)
        .filter(|n| n.starts_with("redis_"))
        .collect();
    assert_eq!(
        exercised.len(),
        9,
        "the Redis built-in set changed; add the new call to this test's \
         program so its `.await` is covered: {exercised:?}"
    );

    for name in exercised {
        let emitted = format!("jwc_b_{name}");
        let called = body
            .lines()
            .filter(|l| l.contains(&format!("{emitted}(")) && !l.contains(&format!("fn {emitted}")))
            .collect::<Vec<_>>();
        assert!(
            !called.is_empty(),
            "{emitted} was never called in the output"
        );
        for line in called {
            assert!(
                line.contains(".await"),
                "{emitted} emitted without `.await` — add it to \
                 `is_async_builtin` in native_build.rs. Line: {line}"
            );
        }
    }
}

/// A program with no `redis_*` call must not drag the Redis prelude (and
/// therefore the `redis` / `deadpool-redis` crates) into the generated
/// binary. Guards the `program_uses_redis` gate against being wired to a
/// constant `true`.
#[test]
fn emit_rust_source_omits_redis_prelude_when_unused() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        function main() {
            console.write("no redis here");
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "noredis", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(
        !body.contains("fn jwc_redis_pool()"),
        "Redis prelude was concatenated into a program that never calls a \
         redis_* built-in"
    );
}

/// The HTTP prelude carries `reqwest` into the generated crate's manifest,
/// so a program that never reaches `http_get` must not receive it. This is
/// the guard on the split: adding a `reqwest` call back into
/// `native_prelude.rs.in` would put the whole hyper / rustls subtree back on
/// every hello-world's compile, and nothing else in the suite would notice.
#[test]
fn emit_rust_source_omits_http_prelude_when_unused() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        function main() {
            console.write("no outbound http here");
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "nohttp", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(
        !body.contains("fn jwc_http_client()"),
        "HTTP prelude was concatenated into a program that never calls an \
         outbound-HTTP built-in"
    );
    assert!(
        !body.contains("reqwest::"),
        "generated source references reqwest without the HTTP prelude"
    );
}

/// ...and is emitted when the program does call one.
#[test]
fn emit_rust_source_includes_http_prelude_when_used() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        function main() {
            let body = http_get("https://example.com");
            console.write(body);
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "withhttp", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(
        body.contains("fn jwc_http_client()"),
        "HTTP prelude missing from a program that calls http_get"
    );
}

/// The crypto prelude's JWKS fetch calls `jwc_http_client` and
/// `jwc_check_outbound_url`, so crypto must drag the HTTP prelude in even
/// when the program never calls `http_get` itself. Without this the
/// generated crate fails to compile on unresolved names.
#[test]
fn emit_rust_source_includes_http_prelude_for_crypto_programs() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        function main() {
            let token = jwt_sign("{\"sub\":\"1\"}", "secret");
            console.write(token);
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "crypto", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(
        body.contains("fn jwc_check_outbound_url("),
        "crypto prelude emitted without the HTTP helpers it calls"
    );
}

/// `log_insert` lowers to the buffered push, not to `jwc_db_exec`. If it
/// ever regresses to a direct exec the latency win is silently gone — the
/// program still works, which is exactly why this needs a test.
#[test]
fn emit_rust_source_lowers_log_insert_to_the_buffered_push() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        dbcontext AppDb : Postgres;
        entity ApiCall of AppDb {
            id int pk serial;
            path varchar(255);
            status int;
        }
        function main() {
            let row = new ApiCall();
            row.path = "/x";
            row.status = 200;
            log_insert("ApiCall", row);
        }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "logins", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(
        body.contains("jwc_log_push("),
        "log_insert did not lower to the buffered push"
    );
    // Auto-increment columns are excluded, matching `emit_db_insert`.
    assert!(
        body.contains("INSERT INTO \\\"api_call\\\" (\\\"path\\\", \\\"status\\\") VALUES "),
        "unexpected statement prefix for the buffered insert"
    );
    // Sync by construction: a `.await` here would mean the push suspends on
    // the request path, which defeats the point.
    assert!(
        !body.contains("jwc_log_push(") || !body.contains("jwc_log_push(\"...\").await"),
        "buffered push must not be awaited"
    );
}

/// A route body ending in `return` must not skip the after-chain.
///
/// `Stmt::Return` lowers to a real Rust `return`. Emitted inline into
/// `route_N_inner`, that jumped over the response-status capture and every
/// `_after()` call — so a middleware `after { }` block never ran on a native
/// build. Nearly every route ends in `return`, so this was not an edge case:
/// jwc-shortener served 3.5M requests and logged exactly zero rows.
///
/// Nothing caught it. The emitted source still *contains* the `_after()`
/// call — just after a `return` — so a substring assertion passes while the
/// code is unreachable. This test checks reachability instead: no `return`
/// may sit between binding `__resp` and the after-call.
#[test]
fn emit_rust_source_keeps_the_after_block_reachable_past_a_return() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        middleware Tracker {
        }
        after {
            let s = response_status();
        }
        route GET "/" use Tracker {
            return json({ ok: true });
        }
        function main() { serve(8080); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "afterret", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");

    // The call site, not the `fn mw_tracker_after()` definition — that is
    // emitted earlier in the file and would match first.
    let after_call = body
        .find("let _ = mw_tracker_after().await;")
        .expect("after-chain call missing entirely");
    let resp_bind = body.find("let __resp =").expect("__resp binding missing");
    assert!(
        resp_bind < after_call,
        "__resp must be bound before the after-chain runs"
    );
    let between = &body[resp_bind..after_call];
    assert!(
        !between.contains("return "),
        "a `return` between binding __resp and the after-call makes the \
         after-block unreachable; body must be lifted into its own fn:\n{between}"
    );
    // The lifted body is what makes that true.
    assert!(
        body.contains("async fn route_0_body()"),
        "route body was not lifted into its own fn"
    );
}

/// The lift is conditional: a route with no after-chain keeps the flat
/// inline shape, so the common case pays neither an extra function nor an
/// extra await.
#[test]
fn emit_rust_source_keeps_bodies_inline_without_an_after_chain() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let src = r#"
        route GET "/" {
            return json({ ok: true });
        }
        function main() { serve(8080); }
    "#;
    let program = parse(src);
    let out = emit_rust_source(&program, tmp.path(), "noafter", false).expect("emit");
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(
        !body.contains("async fn route_0_body()"),
        "a route with no after-chain must not pay for the lifted body"
    );
}
