//! Sprint 8 smoke test for `jwc build --native --emit-rust-source`.
//!
//! Drives the public `native_build::emit_rust_source` entry point on a
//! minimal in-memory program and asserts the dump (a) is non-empty,
//! (b) starts with the generated-by header, and (c) lands at the expected
//! `bin/<profile>/<app>.generated.rs` path.

use std::fs;

use jwc::native_build::emit_rust_source;
use jwc::parser::{parse_program, validate_program};

fn parse(src: &str) -> jwc::ast::Program {
    let p = parse_program(src).expect("parse");
    validate_program(&p).expect("validate");
    p
}

#[test]
fn emit_rust_source_writes_to_expected_path_with_header() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let src = r#"
        function main() {
            print("hi");
        }
    "#;
    let program = parse(src);

    let out = emit_rust_source(&program, root, "emittest", false).expect("emit");

    assert_eq!(
        out,
        root.join("bin").join("debug").join("emittest.generated.rs")
    );
    let body = fs::read_to_string(&out).expect("read generated");
    assert!(!body.is_empty(), "generated source is empty");
    assert!(
        body.starts_with("// Generated by jwc build --native. DO NOT EDIT."),
        "missing generated-by header; got: {}",
        &body[..body.len().min(200)]
    );
}

#[test]
fn emit_rust_source_respects_release_profile_dir() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    let program = parse(r#"function main() { print("x"); }"#);

    let out = emit_rust_source(&program, root, "rel_app", true).expect("emit");

    assert_eq!(
        out,
        root.join("bin")
            .join("release")
            .join("rel_app.generated.rs")
    );
    assert!(out.exists(), "release output not written");
}
