//! v0.25.b acceptance: the SQL a query compiles to, reviewed by hand and
//! then frozen.
//!
//! The goldens under `tests/sql_golden/` are the artefact the join work is
//! read against. A query compiler is easy to make *plausible* and hard to
//! make *right*: `json_agg` over a left join silently multiplies the
//! driving rows, an `as one` that misses yields an object of nulls instead
//! of a null, and a `limit` written on a collection can end up bounding the
//! page instead of the collection. None of those fail loudly. They fail as
//! wrong data, so the SQL text itself is the thing under test.
//!
//! Regenerate after an intentional change:
//!
//! ```bash
//! JWC_V1_BLESS=1 cargo test --test v1_sql_golden
//! ```
//!
//! and **read the diff** — that is the entire point of the file.
//!
//! The execution half is opt-in: set `JWC_V1_PG` to a psql connection
//! string. **A SKIPPED line is not a pass.**

use jwc::v1::{fmt, model, query, query_sql, symbols, workspace::Workspace};
use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn sample() -> PathBuf {
    repo_root().join("docs/spec/v1/sample")
}

fn cases() -> Vec<PathBuf> {
    let dir = repo_root().join("tests/sql_golden/cases");
    let mut out: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("tests/sql_golden/cases")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("jwc"))
        .collect();
    out.sort();
    out
}

/// Every query in a project, compiled, in one reviewable document.
fn render(path: &Path) -> String {
    let ws = Workspace::load(path).expect("load");
    assert!(
        !ws.has_parse_errors(),
        "{} did not parse:\n{}",
        path.display(),
        ws.parse_errors().join("")
    );
    let built = model::build(&ws);
    let sym = symbols::build(&ws, &built.model);

    let mut out = String::new();
    out.push_str("-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.\n");
    for file in &ws.files {
        for site in query_sql::sites(&file.program) {
            out.push_str(&format!("\n-- ── {} ──\n", site.label));
            let plan = query::plan(site.select, &sym);
            // A planner error means the query never reaches emission; say so
            // rather than printing SQL built from a broken tree.
            let errors: Vec<&jwc::v1::diag::Diagnostic> = plan
                .diags
                .iter()
                .filter(|d| d.severity == jwc::v1::diag::Severity::Error)
                .collect();
            if let Some(d) = errors.first() {
                out.push_str(&format!("-- rejected: {} {}\n", d.code, d.message));
                continue;
            }
            let mut c = query_sql::Compiler::new(&built.model);
            match c.compile(site.select, &plan) {
                Some(compiled) => {
                    for (i, p) in compiled.params.iter().enumerate() {
                        out.push_str(&format!(
                            "-- ${} = {} :: {}\n",
                            i + 1,
                            fmt::expr(&p.expr),
                            p.cast
                        ));
                    }
                    out.push_str(&format!("{}\n", compiled.sql));
                }
                // The gap names the release that closes it, so the golden
                // doubles as the query compiler's to-do list.
                None => out.push_str(&format!("-- not compilable yet: {}\n", c.gap())),
            }
        }
    }
    out
}

fn check(path: &Path, golden: &Path) -> Option<String> {
    let got = render(path);
    if std::env::var("JWC_V1_BLESS").is_ok() {
        std::fs::write(golden, &got).expect("write golden");
        return None;
    }
    let want = std::fs::read_to_string(golden)
        .unwrap_or_else(|_| panic!("missing golden {} — bless with JWC_V1_BLESS=1", golden.display()));
    if got.trim_end() == want.trim_end() {
        return None;
    }
    Some(format!(
        "=== {} ===\n--- want ---\n{want}\n--- got ---\n{got}",
        path.display()
    ))
}

#[test]
fn goldens_match_byte_for_byte() {
    let mut bad = Vec::new();
    for case in cases() {
        if let Some(diff) = check(&case, &case.with_extension("sql")) {
            bad.push(diff);
        }
    }
    if let Some(diff) = check(&sample(), &repo_root().join("tests/sql_golden/sample.sql")) {
        bad.push(diff);
    }
    assert!(bad.is_empty(), "{}", bad.join("\n\n"));
}

#[test]
fn compilation_is_deterministic() {
    // Aliases are `t0`, `t1`, … assigned in tree order, and parameters are
    // numbered in emission order. Either one drifting between runs would
    // still produce *correct* SQL — and a prepared-statement cache that
    // never hits.
    for path in cases().into_iter().chain([sample()]) {
        assert_eq!(render(&path), render(&path), "{} is not deterministic", path.display());
    }
}

// ------------------------------------------------------------- shapes

/// The sample's compiled SQL, as one string, for shape assertions.
fn sample_sql() -> String {
    render(&sample())
}

#[test]
fn a_nullable_one_is_a_null_object_not_an_object_of_nulls() {
    // #3. `left join … as one` that finds nothing must project JSON null,
    // not `{"id": null, "name": null}`. The guard is the child's primary
    // key: NOT NULL when the row exists.
    let sql = sample_sql();
    assert!(
        sql.contains("CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object("),
        "expected the null-object guard:\n{sql}"
    );
}

#[test]
fn an_inner_one_carries_no_guard() {
    // An `inner join … as one` cannot miss, so guarding it would be dead
    // SQL that still costs a comparison per row.
    let ws = Workspace::load(repo_root().join("tests/sql_golden/cases/inner_one.jwc")).expect("load");
    let built = model::build(&ws);
    let sym = symbols::build(&ws, &built.model);
    let file = &ws.files[0];
    let site = &query_sql::sites(&file.program)[0];
    let plan = query::plan(site.select, &sym);
    let sql = query_sql::Compiler::new(&built.model)
        .compile(site.select, &plan)
        .expect("compiles")
        .sql;
    assert!(sql.contains("JOIN"), "{sql}");
    assert!(!sql.contains("CASE WHEN"), "an inner join needs no guard:\n{sql}");
}

#[test]
fn a_collection_is_a_lateral_not_an_ordered_json_agg() {
    // `json_agg(… ORDER BY …)` can order a collection but cannot bound it,
    // and it multiplies the driving row when two collections are projected
    // side by side. The lateral does both correctly (queries.md §4.5).
    let sql = sample_sql();
    assert!(sql.contains("LEFT JOIN LATERAL"), "expected a lateral:\n{sql}");
    assert!(
        !sql.contains("json_agg(") || !sql.contains("ORDER BY) "),
        "no ordered json_agg:\n{sql}"
    );
    for line in sql.lines() {
        assert!(
            !(line.contains("json_agg(") && line.contains(" ORDER BY ")),
            "ordered json_agg is the shape this test exists to forbid:\n{line}"
        );
    }
}

#[test]
fn a_collection_bounds_the_rows_not_the_page() {
    // The `limit` on `as many` belongs to the child rows, inside the
    // lateral's subquery. Outside it, the same word bounds the page — the
    // two readings differ by one nesting level and produce plausible,
    // different answers, so every LIMIT in the sample is checked for which
    // side of `) c` it landed on.
    let sql = sample_sql();
    let mut bounded = 0usize;
    for lateral in sql.split("LEFT JOIN LATERAL").skip(1) {
        let (inner, rest) = lateral.split_once(") c\n").expect("the lateral's inner select");
        let tail = rest.split("ON true").next().unwrap_or("");
        assert!(
            !tail.contains("LIMIT") && !tail.contains("ORDER BY"),
            "a collection's order and bound escaped its subquery:\n{tail}"
        );
        if inner.contains("LIMIT") {
            assert!(inner.contains("ORDER BY"), "a bound with no order:\n{inner}");
            bounded += 1;
        }
    }
    assert!(bounded > 0, "expected a bounded collection in the sample");
}

#[test]
fn a_collection_is_never_null() {
    // `as many` yields `[]`, never null — types.md §6.2. Both halves are
    // needed: the aggregate is null when the subquery has no rows, and the
    // lateral itself contributes null when the ON side has none.
    let sql = sample_sql();
    assert!(sql.contains("coalesce(json_agg(c.j), '[]'::json)"));
    assert!(sql.contains("_agg.data, '[]'::json)"));
}

#[test]
fn projections_use_json_not_jsonb() {
    // `jsonb` sorts object keys. A projection's key order is written down
    // in the source and the response must keep it (queries.md §7.2).
    let sql = sample_sql();
    assert!(!sql.contains("jsonb"), "jsonb reorders keys:\n{sql}");
    assert!(sql.contains("json_build_object("));
}

#[test]
fn parameters_are_bound_as_text_and_cast_in_sql() {
    // `$1::bigint` makes Postgres infer bigint for the parameter and then
    // refuse the String the runtime sends. The cast has to be on the value.
    let sql = sample_sql();
    for i in 1..=9 {
        let bad = format!("(${i}::bigint)");
        assert!(!sql.contains(&bad), "parameter cast the wrong way round: {bad}");
    }
    assert!(sql.contains("::text)::"));
}

#[test]
fn private_columns_never_reach_a_default_projection() {
    // schema.md §3.1 — `private` is about what leaves the process, and a
    // `select` with no projection is the easiest way to leak one. Naming a
    // private column explicitly stays legal: `AuthService.login` reads
    // `password_hash` into a local and the taint rule stops it at the
    // response builder, not here.
    let golden = std::fs::read_to_string(repo_root().join("tests/sql_golden/cases/default_projection.sql"))
        .expect("golden");
    assert!(golden.contains("'email'"), "the default projection is not empty:\n{golden}");
    assert!(
        !golden.contains("password_hash"),
        "private column in a default projection:\n{golden}"
    );
}

// ------------------------------------------------------------ execute

/// The DDL a project's schema compiles to.
fn ddl_for(path: &Path) -> String {
    let ws = Workspace::load(path).expect("load");
    let built = model::build(&ws);
    jwc::v1::ddl::render(&ws, &jwc::v1::ddl::emit(&built.model), false)
}

fn pg() -> Option<String> {
    match std::env::var("JWC_V1_PG") {
        Ok(c) => Some(c),
        Err(_) => {
            eprintln!(
                "SKIPPED — set JWC_V1_PG to a psql connection string \
                 (`-h 127.0.0.1 -p 5432 -U postgres`). A SKIPPED line is not \
                 a pass."
            );
            None
        }
    }
}

/// Create a database, apply a project's schema to it, and hand back its name.
fn seeded(conn: &str, db: &str, project: &Path, seed: &str) -> String {
    run_psql(conn, "postgres", &["-c", &format!("DROP DATABASE IF EXISTS {db}")]);
    run_psql(conn, "postgres", &["-c", &format!("CREATE DATABASE {db}")]);
    let sql = ddl_for(project);
    let file = std::env::temp_dir().join(format!("{db}.sql"));
    std::fs::write(&file, &sql).expect("write ddl");
    let out = run_psql(
        conn,
        db,
        &["-q", "-v", "ON_ERROR_STOP=1", "-f", &file.display().to_string()],
    );
    assert!(out.trim().is_empty(), "schema did not apply:\n{out}");
    if !seed.is_empty() {
        let out = run_psql(conn, db, &["-q", "-v", "ON_ERROR_STOP=1", "-c", seed]);
        assert!(out.trim().is_empty(), "seed did not apply:\n{out}");
    }
    db.to_string()
}

/// Run one compiled query and return the single JSON text it produces.
fn execute(conn: &str, db: &str, sql: &str, args: &[&str]) -> String {
    let types = vec!["text"; args.len()].join(", ");
    let decl = if args.is_empty() {
        String::new()
    } else {
        format!(" ({types})")
    };
    let values: Vec<String> = args.iter().map(|a| format!("'{a}'")).collect();
    // `EXECUTE q()` is a syntax error: with no parameters the parens go too.
    let call = if args.is_empty() {
        "EXECUTE q".to_string()
    } else {
        format!("EXECUTE q({})", values.join(", "))
    };
    let batch = format!("PREPARE q{decl} AS {sql}; {call};");
    // `-q` keeps the PREPARE command tag out of the way, so the only line
    // left is the one column the query produces.
    let out = run_psql(conn, db, &["-At", "-q", "-v", "ON_ERROR_STOP=1", "-c", &batch]);
    assert!(
        out.trim_start().starts_with('[') || out.trim_start().starts_with('{'),
        "query did not run:\n{batch}\n{out}"
    );
    out.trim().to_string()
}

/// `(label, sql, param count)` for every compilable query in a project.
fn statements(path: &Path) -> Vec<(String, String, usize)> {
    let ws = Workspace::load(path).expect("load");
    let built = model::build(&ws);
    let sym = symbols::build(&ws, &built.model);
    let mut out = Vec::new();
    for file in &ws.files {
        for site in query_sql::sites(&file.program) {
            let plan = query::plan(site.select, &sym);
            if plan.diags.iter().any(|d| d.severity == jwc::v1::diag::Severity::Error) {
                continue;
            }
            let mut c = query_sql::Compiler::new(&built.model);
            if let Some(compiled) = c.compile(site.select, &plan) {
                out.push((site.label.clone(), compiled.sql, compiled.params.len()));
            }
        }
    }
    out
}

fn statement(path: &Path, label: &str) -> String {
    statements(path)
        .into_iter()
        .find(|(l, _, _)| l == label)
        .unwrap_or_else(|| panic!("no query labelled {label}"))
        .1
}

/// Every compiled statement must be something Postgres accepts. `PREPARE`
/// resolves names, types and function signatures without needing real
/// argument values — which is a whole class of bug a golden file cannot
/// see, because wrong SQL is still stable SQL.
#[test]
fn every_golden_prepares_on_postgres() {
    let Some(conn) = pg() else { return };

    let mut prepared = 0usize;
    let mut failures = Vec::new();
    for (i, project) in cases().into_iter().chain([sample()]).enumerate() {
        let db = format!("jwc_v1_sql_golden_{i}");
        seeded(&conn, &db, &project, "");
        for (j, (label, sql, params)) in statements(&project).into_iter().enumerate() {
            let types = vec!["text"; params].join(", ");
            let stmt = if params == 0 {
                format!("PREPARE p{j} AS {sql}")
            } else {
                format!("PREPARE p{j} ({types}) AS {sql}")
            };
            let out = run_psql(&conn, &db, &["-q", "-v", "ON_ERROR_STOP=1", "-c", &stmt]);
            if out.trim().is_empty() {
                prepared += 1;
            } else {
                failures.push(format!("{}: {label}\n{sql}\n{out}", project.display()));
            }
        }
        run_psql(&conn, "postgres", &["-c", &format!("DROP DATABASE {db}")]);
    }

    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
    assert!(prepared >= 20, "expected every golden's queries, prepared {prepared}");
}

#[test]
fn two_collections_do_not_multiply_each_other() {
    // The reason `as many` is a lateral. Under `json_agg` over a plain join,
    // an org with three notes and two tags reports six of each — a wrong
    // answer that looks like a right one, on data that looks fine.
    let Some(conn) = pg() else { return };
    let project = repo_root().join("tests/sql_golden/cases/two_collections.jwc");
    let db = seeded(
        &conn,
        "jwc_v1_sql_two_collections",
        &project,
        "INSERT INTO s.orgs (id, name) VALUES (1, 'acme');
         INSERT INTO s.notes (org_id, body) VALUES (1, 'a'), (1, 'b'), (1, 'c');
         INSERT INTO s.tags (org_id, label) VALUES (1, 'x'), (1, 'y');",
    );
    let sql = statement(&project, "view OrgBoard");
    let json = execute(&conn, &db, &sql, &["20"]);
    run_psql(&conn, "postgres", &["-c", &format!("DROP DATABASE {db}")]);

    let rows: serde_json::Value = serde_json::from_str(&json).expect("json");
    let row = &rows[0];
    assert_eq!(row["notes"].as_array().map(|a| a.len()), Some(3), "{json}");
    assert_eq!(row["tags"].as_array().map(|a| a.len()), Some(2), "{json}");
}

#[test]
fn a_missing_one_is_json_null_and_an_empty_many_is_an_empty_array() {
    // #3 and types.md §6.2, on real rows. An account with no manager must
    // read `"manager": null`, not `{"id": null, "email": null}` — the two
    // differ only in the guard, and both deserialise.
    let Some(conn) = pg() else { return };
    let project = repo_root().join("tests/sql_golden/cases/self_join.jwc");
    let db = seeded(
        &conn,
        "jwc_v1_sql_self_join",
        &project,
        "INSERT INTO s.accounts (id, email, manager_id) VALUES (1, 'boss@x', NULL);
         INSERT INTO s.accounts (id, email, manager_id) VALUES (2, 'ic@x', 1);",
    );
    let managers: serde_json::Value =
        serde_json::from_str(&execute(&conn, &db, &statement(&project, "view AccountManager"), &[]))
            .expect("json");
    let reports: serde_json::Value = serde_json::from_str(&execute(
        &conn,
        &db,
        &statement(&project, "view AccountReports"),
        &["100"],
    ))
    .expect("json");
    run_psql(&conn, "postgres", &["-c", &format!("DROP DATABASE {db}")]);

    let boss = managers.as_array().unwrap().iter().find(|r| r["id"] == "1").unwrap();
    let ic = managers.as_array().unwrap().iter().find(|r| r["id"] == "2").unwrap();
    assert!(boss["manager"].is_null(), "a missing `one` must be null: {boss}");
    assert_eq!(ic["manager"]["email"], "boss@x", "{ic}");

    let boss = reports.as_array().unwrap().iter().find(|r| r["id"] == "1").unwrap();
    let ic = reports.as_array().unwrap().iter().find(|r| r["id"] == "2").unwrap();
    assert_eq!(boss["reports"].as_array().map(|a| a.len()), Some(1), "{boss}");
    assert_eq!(
        ic["reports"].as_array().map(|a| a.len()),
        Some(0),
        "an empty collection is `[]`, never null: {ic}"
    );
}

#[test]
fn a_collections_limit_bounds_the_collection() {
    // With the limit outside the lateral this query returns one org and two
    // of its notes; inside, it returns every org and two notes each. Both
    // are believable until you look.
    let Some(conn) = pg() else { return };
    let project = repo_root().join("tests/sql_golden/cases/two_collections.jwc");
    let db = seeded(
        &conn,
        "jwc_v1_sql_bound",
        &project,
        "INSERT INTO s.orgs (id, name) VALUES (1, 'acme'), (2, 'globex');
         INSERT INTO s.notes (org_id, body) VALUES (1, 'a'), (1, 'b'), (1, 'c'), (2, 'd');",
    );
    let json = execute(&conn, &db, &statement(&project, "view OrgBoard"), &["2"]);
    run_psql(&conn, "postgres", &["-c", &format!("DROP DATABASE {db}")]);

    let rows: serde_json::Value = serde_json::from_str(&json).expect("json");
    let rows = rows.as_array().expect("an array");
    assert_eq!(rows.len(), 2, "the bound is the collection's, not the page's: {json}");
    assert_eq!(rows[0]["notes"].as_array().map(|a| a.len()), Some(2), "{json}");
    assert_eq!(rows[1]["notes"].as_array().map(|a| a.len()), Some(1), "{json}");
}

#[test]
fn a_join_level_where_narrows_the_collection_not_the_driving_rows() {
    // queries.md §4.7. Moved to the outer WHERE, this same clause would
    // drop orgs that have no active member at all.
    let Some(conn) = pg() else { return };
    let project = repo_root().join("tests/sql_golden/cases/filters.jwc");
    let db = seeded(
        &conn,
        "jwc_v1_sql_filters",
        &project,
        "INSERT INTO s.orgs (id, name, region) VALUES (1, 'acme', 'eu'), (2, 'globex', 'us');
         INSERT INTO s.members (org_id, role, removed) VALUES
             (1, 'admin', NULL), (1, 'member', now()), (2, 'admin', now());",
    );
    let json = execute(&conn, &db, &statement(&project, "view ActiveAdmins"), &["10"]);
    run_psql(&conn, "postgres", &["-c", &format!("DROP DATABASE {db}")]);

    let rows: serde_json::Value = serde_json::from_str(&json).expect("json");
    let rows = rows.as_array().expect("an array");
    assert_eq!(rows.len(), 2, "both orgs still have a region: {json}");
    let acme = rows.iter().find(|r| r["name"] == "acme").unwrap();
    let globex = rows.iter().find(|r| r["name"] == "globex").unwrap();
    assert_eq!(acme["admins"].as_array().map(|a| a.len()), Some(1), "{acme}");
    assert_eq!(
        globex["admins"].as_array().map(|a| a.len()),
        Some(0),
        "an org whose every member is removed keeps its row: {globex}"
    );
}

fn run_psql(conn: &str, db: &str, args: &[&str]) -> String {
    let mut cmd = Command::new("psql");
    for part in conn.split_whitespace() {
        cmd.arg(part);
    }
    cmd.arg("-d").arg(db);
    for a in args {
        cmd.arg(a);
    }
    let out = cmd.output().expect("psql");
    format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    )
}
