-- Generated by `jwc v1 gen-sql`. Do not edit.
-- Emission order: schema, enum type, table, foreign key, index, trigger, comment.

-- ── Schema ──
CREATE SCHEMA IF NOT EXISTS s;


-- ── EnumType ──
CREATE TYPE s.kind AS ENUM ('a', 'b');


-- ── Table ──
CREATE TABLE s.children (
    parent_id bigint NOT NULL,
    seq integer NOT NULL,
    label varchar(50) NOT NULL,
    email varchar(255),
    amount numeric(12, 2) NOT NULL,
    kind s.kind NOT NULL,
    retired timestamptz,
    payload jsonb,
    CONSTRAINT pk_children PRIMARY KEY (parent_id, seq),
    CONSTRAINT uq_children__parent_id_label UNIQUE (parent_id, label),
    CONSTRAINT ck_children__label__minlength CHECK (char_length(label) >= 1),
    CONSTRAINT ck_children__label__maxlength CHECK (char_length(label) <= 40),
    CONSTRAINT ck_children__email__pattern CHECK (email IS NULL OR email ~ '^[^@]+@[^@]+$'),
    CONSTRAINT ck_children__amount__min CHECK (amount >= 0),
    CONSTRAINT ck_children__amount__max CHECK (amount <= 1000),
    CONSTRAINT ck_children__seq__1 CHECK (seq > 0),
    CONSTRAINT ck_children__amount_kind__2 CHECK ((amount >= 0) AND (kind = 'a'))
);

CREATE TABLE s.parents (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(20) NOT NULL,
    CONSTRAINT pk_parents PRIMARY KEY (id),
    CONSTRAINT uq_parents__code UNIQUE (code)
);


-- ── ForeignKey ──
ALTER TABLE s.children ADD CONSTRAINT fk_children__parent_id
    FOREIGN KEY (parent_id) REFERENCES s.parents (id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;


-- ── Index ──
CREATE UNIQUE INDEX uq_children__parent_id__e0051a5c
    ON s.children (parent_id)
    WHERE retired IS NULL;

CREATE INDEX ix_children__label
    ON s.children (label);

CREATE INDEX ix_children__parent_id_seq
    ON s.children (parent_id, seq DESC NULLS LAST);

CREATE INDEX ix_children__retired__2f4217bd
    ON s.children (retired)
    WHERE retired IS NOT NULL;

CREATE INDEX ix_children__payload__gin
    ON s.children USING gin (payload);


-- ── Comment ──
COMMENT ON TABLE s.children IS 'Composite primary key, composite foreign key as ONE constraint,
partial unique as an index, and a table check.';

