-- Generated by `jwc v1 gen-sql`. Do not edit.
-- Emission order: schema, enum type, table, foreign key, index, trigger, comment.

-- ── Schema ──
CREATE SCHEMA IF NOT EXISTS s;


-- ── EnumType ──
CREATE TYPE s.status AS ENUM ('draft', 'live', 'archived');


-- ── Table ──
CREATE TABLE s.items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    priority varchar(6) DEFAULT 'normal' NOT NULL,
    status s.status DEFAULT 'draft'::s.status NOT NULL,
    fallback varchar(6),
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT ck_items__priority__enum CHECK (priority IN ('low', 'normal', 'high')),
    CONSTRAINT ck_items__fallback__enum CHECK (fallback IS NULL OR fallback IN ('low', 'normal', 'high'))
);

