-- Generated by `jwc v1 gen-sql`. Do not edit.
-- Emission order: schema, enum type, table, foreign key, index, trigger, view, comment.

-- ── Schema ──
CREATE SCHEMA IF NOT EXISTS rpt;


-- ── Table ──
CREATE TABLE rpt.tbl_org_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order" integer NOT NULL,
    "createdAt" timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    touched_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_tbl_org_members PRIMARY KEY (id)
);


-- ── Trigger ──
CREATE OR REPLACE FUNCTION rpt.tg_tbl_org_members__touch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  NEW.touched_at := now();
  RETURN NEW;
END $$;

CREATE TRIGGER tg_tbl_org_members__touch
    BEFORE UPDATE ON rpt.tbl_org_members
    FOR EACH ROW EXECUTE FUNCTION rpt.tg_tbl_org_members__touch();

