-- Generated by `jwc v1 gen-sql`. Do not edit.
-- Emission order: schema, enum type, table, foreign key, index, trigger, view, comment.

-- ── Schema ──
CREATE SCHEMA IF NOT EXISTS s;


-- ── Table ──
CREATE TABLE s.every (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    a smallint NOT NULL,
    b integer NOT NULL,
    c bigint NOT NULL,
    d numeric(14, 2) NOT NULL,
    e numeric NOT NULL,
    f boolean NOT NULL,
    g varchar(40) NOT NULL,
    h text NOT NULL,
    i timestamptz NOT NULL,
    j date NOT NULL,
    k time NOT NULL,
    l interval NOT NULL,
    m uuid NOT NULL,
    n jsonb NOT NULL,
    o inet NOT NULL,
    p bytea NOT NULL,
    q text[] NOT NULL,
    nullable_text text,
    nullable_arr text[],
    CONSTRAINT pk_every PRIMARY KEY (id)
);


-- ── Comment ──
COMMENT ON TABLE s.every IS 'Every scalar in the dictionary (types.md §2.1), so the golden file is
the type-mapping table in executable form.';

