-- Generated by jwc (diff-sql)
CREATE TABLE IF NOT EXISTS "todo" (
    "id" integer NOT NULL,
    "title" text NOT NULL,
    "done" boolean NOT NULL,
    "created_at" timestamptz NULL,
    CONSTRAINT "pk_todo" PRIMARY KEY ("id")
);

