// Generated by jwc build --native. DO NOT EDIT.
#![allow(
    unused_imports,
    dead_code,
    unused_variables,
    unused_mut,
    unused_assignments,
    unreachable_code,
    non_snake_case,
    non_camel_case_types,
    clippy::all
)]

use std::collections::BTreeMap;
use std::fmt;

/// Load a `.env` from the current working directory or the binary's directory.
/// Mirrors `project::load_dotenv` so a standalone native binary picks up the
/// same env layout the `jwc run`/`jwc serve` CLI does.
fn jwc_load_dotenv() {
    let candidates: Vec<std::path::PathBuf> = {
        let mut v = Vec::new();
        if let Ok(cwd) = std::env::current_dir() {
            v.push(cwd.join(".env"));
        }
        if let Ok(exe) = std::env::current_exe() {
            // bin/release/app.exe → walk up to project root
            if let Some(parent) = exe.parent() {
                v.push(parent.join(".env"));
                if let Some(g) = parent.parent() {
                    v.push(g.join(".env"));
                    if let Some(gg) = g.parent() {
                        v.push(gg.join(".env"));
                    }
                }
            }
        }
        v
    };
    let mut content = None;
    for c in &candidates {
        if let Ok(s) = std::fs::read_to_string(c) {
            content = Some(s);
            break;
        }
    }
    let Some(content) = content else { return };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') { continue; }
        if let Some((k, v)) = line.split_once('=') {
            let k = k.trim();
            let v = v.trim();
            if std::env::var(k).is_err() {
                std::env::set_var(k, v);
            }
        }
    }
    if std::env::var("DATABASE_URL").is_err() {
        if let (Ok(u), Ok(p), Ok(h), Ok(port), Ok(d)) = (
            std::env::var("PG_USER"),
            std::env::var("PG_PASSWORD"),
            std::env::var("PG_HOST"),
            std::env::var("PG_PORT"),
            std::env::var("PG_DATABASE"),
        ) {
            std::env::set_var(
                "DATABASE_URL",
                format!("postgresql://{}:{}@{}:{}/{}", u, p, h, port, d),
            );
        }
    }
}

#[derive(Clone, Debug)]
enum V {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(String),
    Array(Vec<V>),
    Object(BTreeMap<String, V>),
}

impl fmt::Display for V {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            V::Null => write!(f, "null"),
            V::Bool(b) => write!(f, "{}", b),
            V::Int(n) => write!(f, "{}", n),
            V::Float(n) => write!(f, "{}", n),
            V::Str(s) => write!(f, "{}", s),
            V::Array(_) | V::Object(_) => write!(f, "{}", jwc_to_json(self)),
        }
    }
}

fn jwc_print(v: V) {
    println!("{}", v);
}

fn jwc_truthy(v: &V) -> bool {
    match v {
        V::Null => false,
        V::Bool(b) => *b,
        V::Int(n) => *n != 0,
        V::Float(n) => *n != 0.0,
        V::Str(s) => !s.is_empty(),
        V::Array(a) => !a.is_empty(),
        V::Object(o) => !o.is_empty(),
    }
}

// --- non-local return slot ---------------------------------------------------
//
// `try { ... } catch (e) { ... }` and `transaction { ... }` wrap their body in
// a `std::panic::catch_unwind` closure. A naked `return X;` inside that closure
// would only exit the closure, not the enclosing function. We park the value
// in a thread-local and the closing wrapper drains it.

use std::cell::RefCell;
thread_local! {
    static JWC_RETURN_SLOT: RefCell<Option<V>> = const { RefCell::new(None) };
}

fn jwc_set_return(v: V) {
    JWC_RETURN_SLOT.with(|s| *s.borrow_mut() = Some(v));
}

fn jwc_has_return() -> bool {
    JWC_RETURN_SLOT.with(|s| s.borrow().is_some())
}

fn jwc_take_return() -> Option<V> {
    JWC_RETURN_SLOT.with(|s| s.borrow_mut().take())
}

// Classify an error message string into one of the well-known JWC error
// kinds — mirrors `runner::classify_jwc_error` for the native AOT path.
fn jwc_classify_error(msg: &str) -> &'static str {
    let lc = msg.to_ascii_lowercase();
    let has = |needles: &[&str]| -> bool { needles.iter().any(|n| lc.contains(n)) };
    if has(&[
        "validate body",
        "validation failed",
        "field '",
        "required",
        "minlength",
        "maxlength",
        "is not declared on",
        "type error",
    ]) {
        return "ValidationError";
    }
    if has(&[
        "deadpool",
        "tokio-postgres",
        "postgres",
        "db error",
        "no connection",
        "pool",
        "advisory lock",
        "migration",
        "sql",
    ]) {
        return "DbError";
    }
    if has(&["timeout", "deadline", "elapsed"]) {
        return "TimeoutError";
    }
    if has(&[
        "http",
        "reqwest",
        "status code",
        "url",
        "fetch_json",
        "http_get",
        "http_post",
    ]) {
        return "HttpError";
    }
    "Error"
}

fn jwc_catch_type_matches(catch_type: Option<&str>, kind: &str) -> bool {
    match catch_type {
        None => true,
        Some("Error") => true,
        Some(t) => t == kind,
    }
}

// Builds the V passed to `errorHandler (e)` and `try {} catch (e)`.
fn jwc_error_value(msg: String) -> V {
    let kind = jwc_classify_error(&msg).to_string();
    let mut m = BTreeMap::new();
    m.insert("type".to_string(), V::Str(kind));
    m.insert("message".to_string(), V::Str(msg));
    m.insert("causes".to_string(), V::Array(Vec::new()));
    V::Object(m)
}

fn jwc_panic_payload_to_string(p: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = p.downcast_ref::<String>() {
        return s.clone();
    }
    if let Some(s) = p.downcast_ref::<&'static str>() {
        return (*s).to_string();
    }
    "panic".to_string()
}

// --- arithmetic & coercion ---------------------------------------------------

fn jwc_add(a: V, b: V) -> V {
    match (a, b) {
        (V::Int(x), V::Int(y)) => V::Int(x + y),
        (V::Float(x), V::Float(y)) => V::Float(x + y),
        (V::Int(x), V::Float(y)) => V::Float(x as f64 + y),
        (V::Float(x), V::Int(y)) => V::Float(x + y as f64),
        (V::Str(x), b) => V::Str(format!("{}{}", x, b)),
        (a, V::Str(y)) => V::Str(format!("{}{}", a, y)),
        (a, b) => panic!("unsupported `+` between {:?} and {:?}", a, b),
    }
}

fn jwc_sub(a: V, b: V) -> V {
    match (a, b) {
        (V::Int(x), V::Int(y)) => V::Int(x - y),
        (V::Float(x), V::Float(y)) => V::Float(x - y),
        (V::Int(x), V::Float(y)) => V::Float(x as f64 - y),
        (V::Float(x), V::Int(y)) => V::Float(x - y as f64),
        (a, b) => panic!("unsupported `-` between {:?} and {:?}", a, b),
    }
}

fn jwc_mul(a: V, b: V) -> V {
    match (a, b) {
        (V::Int(x), V::Int(y)) => V::Int(x * y),
        (V::Float(x), V::Float(y)) => V::Float(x * y),
        (V::Int(x), V::Float(y)) => V::Float(x as f64 * y),
        (V::Float(x), V::Int(y)) => V::Float(x * y as f64),
        (a, b) => panic!("unsupported `*` between {:?} and {:?}", a, b),
    }
}

fn jwc_div(a: V, b: V) -> V {
    match (a, b) {
        (V::Int(x), V::Int(y)) => {
            if y == 0 { panic!("division by zero"); }
            V::Int(x / y)
        }
        (V::Float(x), V::Float(y)) => V::Float(x / y),
        (V::Int(x), V::Float(y)) => V::Float(x as f64 / y),
        (V::Float(x), V::Int(y)) => V::Float(x / y as f64),
        (a, b) => panic!("unsupported `/` between {:?} and {:?}", a, b),
    }
}

fn jwc_mod(a: V, b: V) -> V {
    match (a, b) {
        (V::Int(x), V::Int(y)) => {
            if y == 0 { panic!("mod by zero"); }
            V::Int(x % y)
        }
        (V::Float(x), V::Float(y)) => V::Float(x % y),
        (a, b) => panic!("unsupported `%` between {:?} and {:?}", a, b),
    }
}

fn jwc_neg(v: V) -> V {
    match v {
        V::Int(n) => V::Int(-n),
        V::Float(n) => V::Float(-n),
        v => panic!("unsupported unary `-` on {:?}", v),
    }
}

fn jwc_eq(a: &V, b: &V) -> bool {
    match (a, b) {
        (V::Null, V::Null) => true,
        (V::Bool(x), V::Bool(y)) => x == y,
        (V::Int(x), V::Int(y)) => x == y,
        (V::Float(x), V::Float(y)) => x == y,
        (V::Int(x), V::Float(y)) | (V::Float(y), V::Int(x)) => (*x as f64) == *y,
        (V::Str(x), V::Str(y)) => x == y,
        (V::Array(x), V::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y.iter()).all(|(a, b)| jwc_eq(a, b))
        }
        (V::Object(x), V::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).map(|w| jwc_eq(v, w)).unwrap_or(false))
        }
        _ => false,
    }
}

fn jwc_cmp(a: &V, b: &V) -> Option<std::cmp::Ordering> {
    match (a, b) {
        (V::Int(x), V::Int(y)) => Some(x.cmp(y)),
        (V::Float(x), V::Float(y)) => x.partial_cmp(y),
        (V::Int(x), V::Float(y)) => (*x as f64).partial_cmp(y),
        (V::Float(x), V::Int(y)) => x.partial_cmp(&(*y as f64)),
        (V::Str(x), V::Str(y)) => Some(x.cmp(y)),
        (V::Bool(x), V::Bool(y)) => Some(x.cmp(y)),
        _ => None,
    }
}

fn jwc_lt(a: &V, b: &V) -> bool { matches!(jwc_cmp(a, b), Some(std::cmp::Ordering::Less)) }
fn jwc_lte(a: &V, b: &V) -> bool { matches!(jwc_cmp(a, b), Some(std::cmp::Ordering::Less | std::cmp::Ordering::Equal)) }
fn jwc_gt(a: &V, b: &V) -> bool { matches!(jwc_cmp(a, b), Some(std::cmp::Ordering::Greater)) }
fn jwc_gte(a: &V, b: &V) -> bool { matches!(jwc_cmp(a, b), Some(std::cmp::Ordering::Greater | std::cmp::Ordering::Equal)) }

// --- field / array helpers ---------------------------------------------------

fn jwc_get_field(v: &V, k: &str) -> V {
    match v {
        V::Object(m) => m.get(k).cloned().unwrap_or(V::Null),
        _ => V::Null,
    }
}

fn jwc_set_field(v: &mut V, k: &str, value: V) {
    match v {
        V::Object(m) => { m.insert(k.to_string(), value); }
        other => panic!("field assignment on non-object value: {:?}", other),
    }
}

fn jwc_to_array(v: V) -> Vec<V> {
    match v {
        V::Array(a) => a,
        V::Null => Vec::new(),
        V::Str(s) => {
            // Accept JSON-array strings to match interpreter semantics.
            match jwc_from_json(&s) {
                Ok(V::Array(a)) => a,
                _ => panic!("for-in expects an array, got string {:?}", s),
            }
        }
        other => panic!("for-in expects an array, got {:?}", other),
    }
}

// --- JSON --------------------------------------------------------------------

fn jwc_to_json(v: &V) -> String {
    let mut out = String::new();
    jwc_write_json(v, &mut out);
    out
}

fn jwc_write_json(v: &V, out: &mut String) {
    match v {
        V::Null => out.push_str("null"),
        V::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        V::Int(n) => out.push_str(&n.to_string()),
        V::Float(n) => {
            if n.is_finite() {
                out.push_str(&n.to_string());
            } else {
                out.push_str("null");
            }
        }
        V::Str(s) => jwc_write_json_string(s, out),
        V::Array(items) => {
            out.push('[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 { out.push(','); }
                jwc_write_json(item, out);
            }
            out.push(']');
        }
        V::Object(map) => {
            out.push('{');
            for (i, (k, val)) in map.iter().enumerate() {
                if i > 0 { out.push(','); }
                jwc_write_json_string(k, out);
                out.push(':');
                jwc_write_json(val, out);
            }
            out.push('}');
        }
    }
}

fn jwc_write_json_string(s: &str, out: &mut String) {
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\x08' => out.push_str("\\b"),
            '\x0c' => out.push_str("\\f"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

fn jwc_from_json(s: &str) -> Result<V, String> {
    let mut p = JsonParser { src: s.as_bytes(), pos: 0 };
    p.skip_ws();
    let v = p.parse_value()?;
    p.skip_ws();
    if p.pos != p.src.len() {
        return Err(format!("trailing data at byte {}", p.pos));
    }
    Ok(v)
}

struct JsonParser<'a> {
    src: &'a [u8],
    pos: usize,
}

impl<'a> JsonParser<'a> {
    fn peek(&self) -> Option<u8> { self.src.get(self.pos).copied() }
    fn bump(&mut self) -> Option<u8> { let b = self.peek(); if b.is_some() { self.pos += 1; } b }

    fn skip_ws(&mut self) {
        while let Some(b) = self.peek() {
            if matches!(b, b' ' | b'\t' | b'\n' | b'\r') { self.pos += 1; } else { break; }
        }
    }

    fn expect(&mut self, b: u8) -> Result<(), String> {
        if self.bump() == Some(b) { Ok(()) } else { Err(format!("expected '{}' at {}", b as char, self.pos)) }
    }

    fn parse_value(&mut self) -> Result<V, String> {
        self.skip_ws();
        match self.peek() {
            Some(b'n') => self.parse_keyword(b"null", V::Null),
            Some(b't') => self.parse_keyword(b"true", V::Bool(true)),
            Some(b'f') => self.parse_keyword(b"false", V::Bool(false)),
            Some(b'"') => self.parse_string().map(V::Str),
            Some(b'[') => self.parse_array(),
            Some(b'{') => self.parse_object(),
            Some(b) if b == b'-' || b.is_ascii_digit() => self.parse_number(),
            Some(b) => Err(format!("unexpected byte '{}' at {}", b as char, self.pos)),
            None => Err("unexpected end of input".into()),
        }
    }

    fn parse_keyword(&mut self, kw: &[u8], val: V) -> Result<V, String> {
        if self.pos + kw.len() > self.src.len() || &self.src[self.pos..self.pos + kw.len()] != kw {
            return Err(format!("expected `{}` at {}", std::str::from_utf8(kw).unwrap(), self.pos));
        }
        self.pos += kw.len();
        Ok(val)
    }

    fn parse_string(&mut self) -> Result<String, String> {
        self.expect(b'"')?;
        let mut out = String::new();
        loop {
            match self.bump() {
                None => return Err("unterminated string".into()),
                Some(b'"') => return Ok(out),
                Some(b'\\') => match self.bump() {
                    Some(b'"') => out.push('"'),
                    Some(b'\\') => out.push('\\'),
                    Some(b'/') => out.push('/'),
                    Some(b'n') => out.push('\n'),
                    Some(b'r') => out.push('\r'),
                    Some(b't') => out.push('\t'),
                    Some(b'b') => out.push('\x08'),
                    Some(b'f') => out.push('\x0c'),
                    Some(b'u') => {
                        if self.pos + 4 > self.src.len() {
                            return Err("truncated \\u escape".into());
                        }
                        let hex = std::str::from_utf8(&self.src[self.pos..self.pos + 4])
                            .map_err(|_| "invalid \\u".to_string())?;
                        let code = u32::from_str_radix(hex, 16).map_err(|e| e.to_string())?;
                        self.pos += 4;
                        if let Some(c) = char::from_u32(code) { out.push(c); }
                    }
                    Some(b) => return Err(format!("bad escape \\{}", b as char)),
                    None => return Err("eof after backslash".into()),
                },
                Some(b) => out.push(b as char),
            }
        }
    }

    fn parse_number(&mut self) -> Result<V, String> {
        let start = self.pos;
        if self.peek() == Some(b'-') { self.pos += 1; }
        while let Some(b) = self.peek() {
            if b.is_ascii_digit() { self.pos += 1; } else { break; }
        }
        let mut is_float = false;
        if self.peek() == Some(b'.') {
            is_float = true;
            self.pos += 1;
            while let Some(b) = self.peek() {
                if b.is_ascii_digit() { self.pos += 1; } else { break; }
            }
        }
        if matches!(self.peek(), Some(b'e') | Some(b'E')) {
            is_float = true;
            self.pos += 1;
            if matches!(self.peek(), Some(b'+') | Some(b'-')) { self.pos += 1; }
            while let Some(b) = self.peek() {
                if b.is_ascii_digit() { self.pos += 1; } else { break; }
            }
        }
        let slice = std::str::from_utf8(&self.src[start..self.pos]).map_err(|e| e.to_string())?;
        if is_float {
            slice.parse::<f64>().map(V::Float).map_err(|e| e.to_string())
        } else {
            slice.parse::<i64>().map(V::Int).map_err(|e| e.to_string())
        }
    }

    fn parse_array(&mut self) -> Result<V, String> {
        self.expect(b'[')?;
        let mut out = Vec::new();
        self.skip_ws();
        if self.peek() == Some(b']') { self.pos += 1; return Ok(V::Array(out)); }
        loop {
            out.push(self.parse_value()?);
            self.skip_ws();
            match self.bump() {
                Some(b',') => self.skip_ws(),
                Some(b']') => return Ok(V::Array(out)),
                _ => return Err(format!("expected ',' or ']' at {}", self.pos)),
            }
        }
    }

    fn parse_object(&mut self) -> Result<V, String> {
        self.expect(b'{')?;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.peek() == Some(b'}') { self.pos += 1; return Ok(V::Object(out)); }
        loop {
            self.skip_ws();
            let k = self.parse_string()?;
            self.skip_ws();
            self.expect(b':')?;
            let v = self.parse_value()?;
            out.insert(k, v);
            self.skip_ws();
            match self.bump() {
                Some(b',') => continue,
                Some(b'}') => return Ok(V::Object(out)),
                _ => return Err(format!("expected ',' or '}}' at {}", self.pos)),
            }
        }
    }
}

// --- Built-in functions ------------------------------------------------------

fn jwc_b_length(v: V) -> V {
    match v {
        V::Str(s) => V::Int(s.chars().count() as i64),
        V::Array(a) => V::Int(a.len() as i64),
        V::Object(o) => V::Int(o.len() as i64),
        V::Null => V::Int(0),
        other => panic!("length() not supported on {:?}", other),
    }
}

fn jwc_b_lower(v: V) -> V {
    match v {
        V::Str(s) => V::Str(s.to_lowercase()),
        other => panic!("lower() expects a string, got {:?}", other),
    }
}

fn jwc_b_upper(v: V) -> V {
    match v {
        V::Str(s) => V::Str(s.to_uppercase()),
        other => panic!("upper() expects a string, got {:?}", other),
    }
}

fn jwc_b_trim(v: V) -> V {
    match v {
        V::Str(s) => V::Str(s.trim().to_string()),
        other => panic!("trim() expects a string, got {:?}", other),
    }
}

fn jwc_b_contains(haystack: V, needle: V) -> V {
    let result = match (&haystack, &needle) {
        (V::Str(s), V::Str(p)) => s.contains(p.as_str()),
        (V::Array(items), n) => items.iter().any(|item| jwc_eq(item, n)),
        (V::Object(map), V::Str(k)) => map.contains_key(k),
        _ => false,
    };
    V::Bool(result)
}

fn jwc_b_starts_with(s: V, p: V) -> V {
    match (s, p) {
        (V::Str(a), V::Str(b)) => V::Bool(a.starts_with(b.as_str())),
        (a, b) => panic!("starts_with() expects two strings, got {:?} / {:?}", a, b),
    }
}

fn jwc_b_ends_with(s: V, p: V) -> V {
    match (s, p) {
        (V::Str(a), V::Str(b)) => V::Bool(a.ends_with(b.as_str())),
        (a, b) => panic!("ends_with() expects two strings, got {:?} / {:?}", a, b),
    }
}

fn jwc_b_replace(s: V, old: V, new: V) -> V {
    match (s, old, new) {
        (V::Str(a), V::Str(b), V::Str(c)) => V::Str(a.replace(b.as_str(), c.as_str())),
        (a, b, c) => panic!("replace() expects three strings, got {:?} / {:?} / {:?}", a, b, c),
    }
}

fn jwc_b_split(s: V, sep: V) -> V {
    match (s, sep) {
        (V::Str(a), V::Str(b)) => {
            let parts: Vec<V> = a.split(b.as_str()).map(|p| V::Str(p.to_string())).collect();
            V::Array(parts)
        }
        (a, b) => panic!("split() expects two strings, got {:?} / {:?}", a, b),
    }
}

fn jwc_b_first(v: V) -> V {
    match v {
        V::Array(mut a) => if a.is_empty() { V::Null } else { a.remove(0) },
        V::Str(s) => s.chars().next().map(|c| V::Str(c.to_string())).unwrap_or(V::Null),
        V::Null => V::Null,
        other => panic!("first() expects an array or string, got {:?}", other),
    }
}

fn jwc_b_last(v: V) -> V {
    match v {
        V::Array(a) => a.last().cloned().unwrap_or(V::Null),
        V::Str(s) => s.chars().last().map(|c| V::Str(c.to_string())).unwrap_or(V::Null),
        V::Null => V::Null,
        other => panic!("last() expects an array or string, got {:?}", other),
    }
}

fn jwc_b_json_parse(v: V) -> V {
    match v {
        V::Str(s) => match jwc_from_json(&s) {
            Ok(parsed) => parsed,
            Err(e) => panic!("json_parse failed: {}", e),
        },
        other => panic!("json_parse() expects a string, got {:?}", other),
    }
}

fn jwc_b_json_stringify(v: V) -> V {
    V::Str(jwc_to_json(&v))
}

fn jwc_b_env(name: V) -> V {
    let n = match name {
        V::Str(s) => s,
        _ => return V::Str(String::new()),
    };
    V::Str(std::env::var(&n).unwrap_or_default())
}

fn jwc_b_int(v: V) -> V {
    match v {
        V::Int(_) => v,
        V::Float(n) => V::Int(n as i64),
        V::Str(s) => V::Int(s.parse::<i64>().unwrap_or(0)),
        V::Bool(b) => V::Int(if b { 1 } else { 0 }),
        _ => V::Int(0),
    }
}

// --- HTTP runtime ------------------------------------------------------------
//
// Tokio-based async HTTP/1.0 server. One tokio task per connection; the
// per-request `Request` lives in a `tokio::task_local!` so JWC code's
// `body()` / `path_param()` / `query_param()` / `header()` built-ins can
// read it without threading the value through every helper signature.
//
// Response values are represented as a `V::Object` with a magic
// `__http_response` marker. The route dispatcher converts the handler's V
// return value into an HTTP response via `jwc_to_response`.

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use tokio::net::TcpListener;

/// Type of a generated route handler: an `async fn()` boxed/erased into a
/// `Pin<Box<dyn Future>>` so we can store them in a homogeneous `Router`.
type RouteFn = fn() -> Pin<Box<dyn Future<Output = V> + Send>>;

const HTTP_RESPONSE_MARKER: &str = "__http_response";

fn jwc_to_u16(v: V) -> u16 {
    match v {
        V::Int(n) => n as u16,
        V::Float(n) => n as u16,
        V::Str(s) => s.parse().unwrap_or(0),
        _ => 0,
    }
}

fn jwc_to_int(v: &V) -> Option<i64> {
    match v {
        V::Int(n) => Some(*n),
        V::Float(n) => Some(*n as i64),
        V::Str(s) => s.parse().ok(),
        _ => None,
    }
}

fn jwc_to_float(v: &V) -> Option<f64> {
    match v {
        V::Int(n) => Some(*n as f64),
        V::Float(n) => Some(*n),
        V::Str(s) => s.parse().ok(),
        _ => None,
    }
}

#[derive(Debug, Clone)]
struct Request {
    method: String,
    path: String,
    query: BTreeMap<String, String>,
    headers: BTreeMap<String, String>,
    body: Vec<u8>,
    path_params: BTreeMap<String, String>,
    /// `true` if the request line was `HTTP/1.1`. Drives default keep-alive.
    http_version_11: bool,
}

tokio::task_local! {
    /// Active HTTP request for the current handler task. Set by
    /// `handle_connection` via `CURRENT_REQUEST.scope(req, async { ... }).await`
    /// before dispatching into the user's route fn so built-ins can read it
    /// across `.await` points without explicit plumbing.
    static CURRENT_REQUEST: Arc<Request>;
}

fn with_current_request<F: FnOnce(&Request) -> V>(f: F) -> V {
    match CURRENT_REQUEST.try_with(|req| f(req.as_ref())) {
        Ok(v) => v,
        Err(_) => V::Null,
    }
}

fn jwc_b_path_param(name: V) -> V {
    let k = match name { V::Str(s) => s, _ => return V::Null };
    with_current_request(|req| {
        req.path_params.get(&k).cloned().map(V::Str).unwrap_or(V::Null)
    })
}

/// Used by `route ... -> handler;` codegen: pulls a positional arg for the
/// declared handler param. Path params take precedence; query params fall
/// back; missing keys become `V::Null`. Mirrors `runner.rs::build_handler_args`.
fn jwc_b_handler_arg(name: &str) -> V {
    with_current_request(|req| {
        if let Some(s) = req.path_params.get(name) {
            return V::Str(s.clone());
        }
        if let Some(s) = req.query.get(name) {
            return V::Str(s.clone());
        }
        V::Null
    })
}

fn jwc_b_query_param(name: V, default: V) -> V {
    let k = match name { V::Str(s) => s, _ => return default };
    with_current_request(|req| {
        req.query.get(&k).cloned().map(V::Str).unwrap_or_else(|| default.clone())
    })
}

fn jwc_b_header(name: V) -> V {
    let k = match name { V::Str(s) => s.to_lowercase(), _ => return V::Null };
    with_current_request(|req| {
        req.headers.get(&k).cloned().map(V::Str).unwrap_or(V::Null)
    })
}

fn jwc_b_body() -> V {
    with_current_request(|req| {
        if req.body.is_empty() {
            return V::Null;
        }
        let as_str = String::from_utf8_lossy(&req.body).to_string();
        // Auto-parse JSON bodies to match interpreter semantics.
        match jwc_from_json(&as_str) {
            Ok(parsed) => parsed,
            Err(_) => V::Str(as_str),
        }
    })
}

// --- response helpers --------------------------------------------------------

fn make_response(status: u16, body: String, content_type: &str) -> V {
    let mut m = BTreeMap::new();
    m.insert(HTTP_RESPONSE_MARKER.to_string(), V::Bool(true));
    m.insert("status".to_string(), V::Int(status as i64));
    m.insert("body".to_string(), V::Str(body));
    m.insert("content_type".to_string(), V::Str(content_type.to_string()));
    V::Object(m)
}

fn body_string(v: V) -> String {
    match v {
        V::Str(s) => s,
        V::Null => String::new(),
        v => jwc_to_json(&v),
    }
}

fn jwc_b_text(v: V) -> V {
    make_response(200, body_string(v), "text/plain; charset=utf-8")
}

fn jwc_b_html(v: V) -> V {
    make_response(200, body_string(v), "text/html; charset=utf-8")
}

fn jwc_b_json(v: V) -> V {
    let body = jwc_to_json(&v);
    make_response(200, body, "application/json")
}

fn jwc_b_ok(v: V) -> V {
    match &v {
        V::Str(_) => jwc_b_text(v),
        _ => jwc_b_json(v),
    }
}

fn jwc_b_created(v: V) -> V {
    let body = match &v {
        V::Str(_) => body_string(v.clone()),
        _ => jwc_to_json(&v),
    };
    let ct = match &v {
        V::Str(_) => "text/plain; charset=utf-8",
        _ => "application/json",
    };
    make_response(201, body, ct)
}

fn jwc_b_not_found(v: V) -> V {
    let body = body_string(v);
    make_response(404, body, "text/plain; charset=utf-8")
}

fn jwc_b_no_content(_v: V) -> V {
    make_response(204, String::new(), "text/plain; charset=utf-8")
}

fn jwc_b_bad_request(v: V) -> V {
    let body = body_string(v);
    make_response(400, body, "text/plain; charset=utf-8")
}

fn jwc_b_unauthorized(v: V) -> V {
    let (body, ct) = match &v {
        V::Null => ("Unauthorized".to_string(), "text/plain; charset=utf-8"),
        V::Str(_) => (body_string(v.clone()), "text/plain; charset=utf-8"),
        _ => (jwc_to_json(&v), "application/json"),
    };
    make_response(401, body, ct)
}

fn jwc_b_forbidden(v: V) -> V {
    let (body, ct) = match &v {
        V::Null => ("Forbidden".to_string(), "text/plain; charset=utf-8"),
        V::Str(_) => (body_string(v.clone()), "text/plain; charset=utf-8"),
        _ => (jwc_to_json(&v), "application/json"),
    };
    make_response(403, body, ct)
}

fn jwc_b_internal_error(v: V) -> V {
    let body = body_string(v);
    make_response(500, body, "text/plain; charset=utf-8")
}

fn jwc_b_status_code(v: V, code: V) -> V {
    let status = jwc_to_int(&code).unwrap_or(200) as u16;
    let body = body_string(v.clone());
    let ct = match &v {
        V::Str(_) => "text/plain; charset=utf-8",
        _ => "application/json",
    };
    make_response(status, body, ct)
}

fn jwc_to_response(v: V) -> (u16, String, String) {
    if let V::Object(ref m) = v {
        if matches!(m.get(HTTP_RESPONSE_MARKER), Some(V::Bool(true))) {
            let status = m.get("status").and_then(jwc_to_int).unwrap_or(200) as u16;
            let body = match m.get("body") {
                Some(V::Str(s)) => s.clone(),
                Some(other) => jwc_to_json(other),
                None => String::new(),
            };
            let ct = match m.get("content_type") {
                Some(V::Str(s)) => s.clone(),
                _ => "text/plain; charset=utf-8".to_string(),
            };
            return (status, body, ct);
        }
    }
    match v {
        V::Str(s) => (200, s, "text/plain; charset=utf-8".to_string()),
        V::Null => (200, String::new(), "text/plain; charset=utf-8".to_string()),
        other => (200, jwc_to_json(&other), "application/json".to_string()),
    }
}

// --- routing -----------------------------------------------------------------

#[derive(Clone)]
enum PathSeg {
    Literal(String),
    Param(String),
}

#[derive(Clone, Copy)]
enum RouteKind {
    Http,
    Ws,
}

struct RouteEntry {
    method: String,
    segments: Vec<PathSeg>,
    kind: RouteKind,
    handler: RouteFn,
}

struct Router {
    entries: Vec<RouteEntry>,
}

impl Router {
    fn new() -> Self { Router { entries: Vec::new() } }

    fn add(&mut self, method: &str, pattern: &str, handler: RouteFn) {
        self.add_kind(method, pattern, RouteKind::Http, handler);
    }

    fn add_ws(&mut self, pattern: &str, handler: RouteFn) {
        self.add_kind("GET", pattern, RouteKind::Ws, handler);
    }

    fn add_kind(&mut self, method: &str, pattern: &str, kind: RouteKind, handler: RouteFn) {
        let segments = pattern
            .trim_start_matches('/')
            .split('/')
            .filter(|s| !s.is_empty())
            .map(|s| {
                if s.starts_with('{') && s.ends_with('}') {
                    PathSeg::Param(s[1..s.len() - 1].to_string())
                } else {
                    PathSeg::Literal(s.to_string())
                }
            })
            .collect();
        self.entries.push(RouteEntry {
            method: method.to_string(),
            segments,
            kind,
            handler,
        });
    }

    fn match_route(
        &self,
        method: &str,
        path: &str,
    ) -> Option<(RouteKind, RouteFn, BTreeMap<String, String>)> {
        let req_segs: Vec<&str> = path.trim_start_matches('/').split('/').filter(|s| !s.is_empty()).collect();
        for entry in &self.entries {
            if entry.method != method { continue; }
            if entry.segments.len() != req_segs.len() { continue; }
            let mut params = BTreeMap::new();
            let mut ok = true;
            for (seg, req) in entry.segments.iter().zip(req_segs.iter()) {
                match seg {
                    PathSeg::Literal(lit) => if lit != req { ok = false; break; },
                    PathSeg::Param(name) => { params.insert(name.clone(), (*req).to_string()); }
                }
            }
            if ok { return Some((entry.kind, entry.handler, params)); }
        }
        None
    }
}

// --- HTTP server (axum-based, HTTP/1.1 + keep-alive) -------------------------

struct HttpServer {
    port: u16,
    router: Arc<Router>,
}

impl HttpServer {
    fn new(port: u16, router: Router) -> Self {
        HttpServer { port, router: Arc::new(router) }
    }

    async fn run(self) {
        let app = axum::Router::new()
            .fallback(axum::routing::any(handle_axum_request))
            .with_state(self.router.clone());
        let addr = std::net::SocketAddr::from(([0, 0, 0, 0], self.port));
        let listener = match TcpListener::bind(addr).await {
            Ok(l) => l,
            Err(e) => {
                eprintln!("[jwc] failed to bind {}: {}", addr, e);
                std::process::exit(1);
            }
        };
        eprintln!("[jwc] listening on http://{}", addr);
        if let Err(e) = axum::serve(listener, app).await {
            eprintln!("[jwc] server error: {}", e);
        }
    }
}

async fn handle_axum_request(
    axum::extract::State(router): axum::extract::State<Arc<Router>>,
    method: axum::http::Method,
    uri: axum::http::Uri,
    headers: axum::http::HeaderMap,
    body: axum::body::Bytes,
) -> axum::response::Response {
    let path_str = uri.path();
    let mut query_map: BTreeMap<String, String> = BTreeMap::new();
    if let Some(q) = uri.query() {
        for pair in q.split('&') {
            if pair.is_empty() { continue; }
            let (k, v) = match pair.find('=') {
                Some(i) => (&pair[..i], &pair[i + 1..]),
                None => (pair, ""),
            };
            query_map.insert(url_decode(k), url_decode(v));
        }
    }
    let mut header_map: BTreeMap<String, String> = BTreeMap::new();
    for (name, value) in headers.iter() {
        header_map.insert(
            name.as_str().to_ascii_lowercase(),
            value.to_str().unwrap_or("").to_string(),
        );
    }
    let method_str = method.as_str().to_string();

    let (kind, handler, path_params) = match router.match_route(&method_str, path_str) {
        Some(found) => found,
        None => {
            return axum::response::Response::builder()
                .status(404)
                .header("content-type", "text/plain; charset=utf-8")
                .body("Not Found".into())
                .unwrap();
        }
    };

    if matches!(kind, RouteKind::Ws) {
        return axum::response::Response::builder()
            .status(501)
            .header("content-type", "text/plain; charset=utf-8")
            .body("WebSocket not supported in native build yet; use `jwc run` or `jwc build` (without --native).".into())
            .unwrap();
    }

    let req = Arc::new(Request {
        method: method_str,
        path: path_str.to_string(),
        query: query_map,
        headers: header_map,
        body: body.to_vec(),
        path_params,
        http_version_11: true,
    });

    let result_v = CURRENT_REQUEST
        .scope(req, async move { handler().await })
        .await;

    let (status, body_str, ct) = jwc_to_response(result_v);
    let status_code = axum::http::StatusCode::from_u16(status).unwrap_or(axum::http::StatusCode::OK);
    axum::response::Response::builder()
        .status(status_code)
        .header("content-type", ct.as_str())
        .body(body_str.into())
        .unwrap()
}

fn url_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => { out.push(b' '); i += 1; }
            b'%' if i + 2 < bytes.len() => {
                let hex = std::str::from_utf8(&bytes[i + 1..i + 3]).unwrap_or("");
                match u8::from_str_radix(hex, 16) {
                    Ok(b) => { out.push(b); i += 3; }
                    Err(_) => { out.push(bytes[i]); i += 1; }
                }
            }
            b => { out.push(b); i += 1; }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

// --- async built-ins: sleep_ms / http_get / fetch_json -----------------------

async fn jwc_b_sleep_ms(n: V) -> V {
    let ms = jwc_to_int(&n).unwrap_or(0).max(0) as u64;
    tokio::time::sleep(std::time::Duration::from_millis(ms)).await;
    V::Null
}

static HTTP_CLIENT: std::sync::OnceLock<reqwest::Client> = std::sync::OnceLock::new();

fn jwc_http_client() -> &'static reqwest::Client {
    HTTP_CLIENT.get_or_init(|| {
        reqwest::Client::builder()
            .build()
            .unwrap_or_else(|e| panic!("failed to build reqwest client: {}", e))
    })
}

async fn jwc_b_http_get(url: V) -> V {
    let u = match url {
        V::Str(s) => s,
        other => return V::Str(format!("http_get: url must be a string, got {:?}", other)),
    };
    match jwc_http_client().get(&u).send().await {
        Ok(resp) => match resp.text().await {
            Ok(body) => V::Str(body),
            Err(e) => V::Str(format!("http_get body read failed: {}", e)),
        },
        Err(e) => V::Str(format!("http_get failed: {}", e)),
    }
}

async fn jwc_b_fetch_json(url: V) -> V {
    let body = jwc_b_http_get(url).await;
    match body {
        V::Str(s) => jwc_from_json(&s).unwrap_or_else(|_| V::Str(s)),
        other => other,
    }
}

// --- time / identifiers ------------------------------------------------------

fn jwc_b_uuid() -> V {
    // RFC 4122 v4 — random, includes proper version/variant bits.
    V::Str(uuid::Uuid::new_v4().to_string())
}

fn jwc_b_now() -> V {
    // ISO-8601 / RFC 3339 UTC, second precision — matches the interpreter's
    // `current_utc_iso8601()`. Postgres accepts this as timestamptz on insert.
    let dt: chrono::DateTime<chrono::Utc> = chrono::Utc::now();
    V::Str(dt.format("%Y-%m-%dT%H:%M:%SZ").to_string())
}

// --- process-wide in-memory cache (TTL-keyed, std-only) ---------------------
//
// Mirrors `jwc::cache` from the interpreter: single global Mutex<HashMap>,
// lazy TTL eviction on read. Fine for single-process / single-replica
// deployments; behind multiple replicas use a shared Redis cache instead.

mod jwc_cache_store {
    use std::collections::HashMap;
    use std::sync::{Mutex, OnceLock};
    use std::time::Instant;

    pub struct Entry {
        pub value: String,
        /// `None` means "never expires".
        pub expires_at: Option<Instant>,
    }

    pub fn store() -> &'static Mutex<HashMap<String, Entry>> {
        static STORE: OnceLock<Mutex<HashMap<String, Entry>>> = OnceLock::new();
        STORE.get_or_init(|| Mutex::new(HashMap::new()))
    }
}

fn jwc_b_cache_get(key: V) -> V {
    use std::time::Instant;
    let k = match key {
        V::Str(s) => s,
        _ => return V::Null,
    };
    let mut guard = jwc_cache_store::store().lock().expect("cache mutex poisoned");
    let expired = match guard.get(&k) {
        Some(entry) => match entry.expires_at {
            Some(deadline) => Instant::now() >= deadline,
            None => false,
        },
        None => return V::Null,
    };
    if expired {
        guard.remove(&k);
        return V::Null;
    }
    guard
        .get(&k)
        .map(|e| V::Str(e.value.clone()))
        .unwrap_or(V::Null)
}

fn jwc_b_cache_set(key: V, value: V, ttl_secs: V) -> V {
    use std::time::{Duration, Instant};
    let k = match key {
        V::Str(s) => s,
        _ => return V::Null,
    };
    let v = match value {
        V::Str(s) => s,
        V::Int(n) => n.to_string(),
        V::Float(n) => n.to_string(),
        V::Bool(b) => b.to_string(),
        V::Null => String::new(),
        other => jwc_to_json(&other),
    };
    let ttl = jwc_to_int(&ttl_secs).unwrap_or(0).max(0) as u64;
    let expires_at = if ttl == 0 {
        None
    } else {
        Instant::now().checked_add(Duration::from_secs(ttl))
    };
    let mut guard = jwc_cache_store::store().lock().expect("cache mutex poisoned");
    guard.insert(
        k,
        jwc_cache_store::Entry {
            value: v,
            expires_at,
        },
    );
    V::Null
}

fn jwc_b_cache_del(key: V) -> V {
    let k = match key {
        V::Str(s) => s,
        _ => return V::Null,
    };
    jwc_cache_store::store()
        .lock()
        .expect("cache mutex poisoned")
        .remove(&k);
    V::Null
}

fn jwc_b_cache_clear() -> V {
    jwc_cache_store::store()
        .lock()
        .expect("cache mutex poisoned")
        .clear();
    V::Null
}

// --- Postgres runtime (async) -----------------------------------------------
//
// Only included when the program declares at least one dbcontext / entity.
// Pulls `tokio-postgres` + `deadpool-postgres` deps in the generated Cargo.toml.
//
// Notes:
//   * One global `deadpool_postgres::Pool`; per-call `pool.get().await` checks
//     out a client; `prepare_cached` reuses statements per-client.
//   * Column readers cover BOOL, INT2/4/8, FLOAT4/8, TEXT/VARCHAR/BPCHAR/NAME.
//     UUID, TIMESTAMP, JSONB surface as `V::Null` — switch to TEXT or wait for
//     the uuid/chrono follow-up.

use std::sync::OnceLock;

static DB_POOL: OnceLock<deadpool_postgres::Pool> = OnceLock::new();

fn jwc_db_connection_string() -> String {
    if let Ok(u) = std::env::var("DATABASE_URL") { return u; }
    if let Ok(u) = std::env::var("JWC_DATABASE_URL") { return u; }
    let host = std::env::var("PG_HOST").unwrap_or_else(|_| "localhost".into());
    let port = std::env::var("PG_PORT").unwrap_or_else(|_| "5432".into());
    let user = std::env::var("PG_USER").unwrap_or_else(|_| "postgres".into());
    let pwd = std::env::var("PG_PASSWORD").unwrap_or_default();
    let db = std::env::var("PG_DATABASE").unwrap_or_else(|_| "postgres".into());
    format!("host={} port={} user={} password={} dbname={}", host, port, user, pwd, db)
}

async fn jwc_db_init() {
    if DB_POOL.get().is_some() { return; }
    let url = jwc_db_connection_string();
    let pg_cfg: tokio_postgres::Config = url
        .parse()
        .unwrap_or_else(|e| panic!("setConnectionString: invalid Postgres URL: {}", e));
    let mgr_cfg = deadpool_postgres::ManagerConfig {
        recycling_method: deadpool_postgres::RecyclingMethod::Fast,
    };
    let mgr = deadpool_postgres::Manager::from_config(pg_cfg, tokio_postgres::NoTls, mgr_cfg);
    // Default 64 matches the bundled interpreter's pool tuning; override via
    // `JWC_DB_POOL_SIZE` for memory-constrained deployments.
    let max_size: usize = std::env::var("JWC_DB_POOL_SIZE")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(64);
    let pool = deadpool_postgres::Pool::builder(mgr)
        .max_size(max_size)
        .build()
        .unwrap_or_else(|e| panic!("setConnectionString: pool build failed: {}", e));
    let _ = DB_POOL.set(pool);
}

async fn jwc_b_setConnectionString() -> V {
    jwc_db_init().await;
    V::Null
}

async fn jwc_db_get() -> deadpool_postgres::Object {
    let pool = DB_POOL
        .get()
        .expect("DB used before setConnectionString() — call setConnectionString() in main()");
    pool.get()
        .await
        .unwrap_or_else(|e| panic!("failed to check out a DB connection: {}", e))
}

type DbParams = Vec<Box<dyn tokio_postgres::types::ToSql + Sync + Send>>;

async fn jwc_db_query(sql: &str, params: DbParams) -> Vec<V> {
    let refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> =
        params.iter().map(|b| b.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync)).collect();
    let client = jwc_db_get().await;
    let stmt = client
        .prepare_cached(sql)
        .await
        .unwrap_or_else(|e| panic!("prepare failed: {}\nSQL: {}", e, sql));
    let rows = client
        .query(&stmt, &refs)
        .await
        .unwrap_or_else(|e| panic!("query failed: {}\nSQL: {}", e, sql));
    rows.iter().map(jwc_row_to_v).collect()
}

async fn jwc_db_exec(sql: &str, params: DbParams) -> u64 {
    let refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> =
        params.iter().map(|b| b.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync)).collect();
    let client = jwc_db_get().await;
    let stmt = client
        .prepare_cached(sql)
        .await
        .unwrap_or_else(|e| panic!("prepare failed: {}\nSQL: {}", e, sql));
    client
        .execute(&stmt, &refs)
        .await
        .unwrap_or_else(|e| panic!("execute failed: {}\nSQL: {}", e, sql))
}

fn jwc_row_to_v(row: &tokio_postgres::Row) -> V {
    use tokio_postgres::types::Type;
    let mut m = BTreeMap::new();
    for (i, col) in row.columns().iter().enumerate() {
        let name = col.name().to_string();
        let ty = col.type_();
        let v: V = match *ty {
            Type::BOOL => row
                .try_get::<_, Option<bool>>(i)
                .ok()
                .flatten()
                .map(V::Bool)
                .unwrap_or(V::Null),
            Type::INT2 => row
                .try_get::<_, Option<i16>>(i)
                .ok()
                .flatten()
                .map(|n| V::Int(n as i64))
                .unwrap_or(V::Null),
            Type::INT4 => row
                .try_get::<_, Option<i32>>(i)
                .ok()
                .flatten()
                .map(|n| V::Int(n as i64))
                .unwrap_or(V::Null),
            Type::INT8 => row
                .try_get::<_, Option<i64>>(i)
                .ok()
                .flatten()
                .map(V::Int)
                .unwrap_or(V::Null),
            Type::FLOAT4 => row
                .try_get::<_, Option<f32>>(i)
                .ok()
                .flatten()
                .map(|n| V::Float(n as f64))
                .unwrap_or(V::Null),
            Type::FLOAT8 => row
                .try_get::<_, Option<f64>>(i)
                .ok()
                .flatten()
                .map(V::Float)
                .unwrap_or(V::Null),
            Type::TEXT | Type::VARCHAR | Type::BPCHAR | Type::NAME => row
                .try_get::<_, Option<String>>(i)
                .ok()
                .flatten()
                .map(V::Str)
                .unwrap_or(V::Null),
            _ => V::Null,
        };
        m.insert(name, v);
    }
    V::Object(m)
}

// --- typed-param helpers used by codegen --------------------------------------
//
// tokio-postgres' `ToSql` impls are width-specific: `i16` only binds to
// `INT2`, `i32` only to `INT2 / INT4`, `i64` only to `INT8`. Binding the
// wrong width raises `WrongType { postgres: Int4, rust: "i64" }` at execute
// time. The codegen picks the helper that matches the declared column type
// (see `PgKind` in `native_build.rs`); this file only has to box correctly.

fn jwc_param_smallint(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    match v {
        V::Null => Box::new(None::<i16>),
        other => Box::new(jwc_to_int(&other).unwrap_or(0) as i16),
    }
}

fn jwc_param_int(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    match v {
        V::Null => Box::new(None::<i32>),
        other => Box::new(jwc_to_int(&other).unwrap_or(0) as i32),
    }
}

fn jwc_param_bigint(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    match v {
        V::Null => Box::new(None::<i64>),
        other => Box::new(jwc_to_int(&other).unwrap_or(0)),
    }
}

fn jwc_param_float(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    match v {
        V::Null => Box::new(None::<f64>),
        V::Int(n) => Box::new(n as f64),
        V::Float(n) => Box::new(n),
        V::Str(s) => Box::new(s.parse::<f64>().unwrap_or(0.0)),
        _ => Box::new(0.0_f64),
    }
}

fn jwc_param_str(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    match v {
        V::Null => Box::new(None::<String>),
        V::Str(s) => Box::new(s),
        other => Box::new(other.to_string()),
    }
}

/// Bind a JWC value into a Postgres temporal column (`timestamptz` /
/// `timestamp` / `date`). JWC carries datetimes as RFC 3339 strings, but
/// tokio-postgres' `String` ToSql impl only accepts text-like Postgres
/// types — sending one to `timestamptz` raises
/// `WrongType { postgres: Timestamptz, rust: "alloc::string::String" }`.
/// We parse the RFC 3339 / ISO 8601 / date-only string into a real
/// `chrono::DateTime<Utc>` so the with-chrono-0_4 ToSql impl binds it
/// against `TIMESTAMPTZ` natively. Empty / unparseable input falls back
/// to a NULL bind rather than panicking mid-INSERT.
fn jwc_param_timestamp(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    fn parse(s: &str) -> Option<chrono::DateTime<chrono::Utc>> {
        if let Ok(dt) = chrono::DateTime::parse_from_rfc3339(s) {
            return Some(dt.with_timezone(&chrono::Utc));
        }
        if let Ok(d) = chrono::NaiveDate::parse_from_str(s, "%Y-%m-%d") {
            let dt = d.and_hms_opt(0, 0, 0)?;
            return Some(chrono::DateTime::<chrono::Utc>::from_naive_utc_and_offset(
                dt,
                chrono::Utc,
            ));
        }
        None
    }
    match v {
        V::Null => Box::new(None::<chrono::DateTime<chrono::Utc>>),
        V::Str(s) => match parse(&s) {
            Some(dt) => Box::new(dt),
            None => Box::new(None::<chrono::DateTime<chrono::Utc>>),
        },
        other => match parse(&other.to_string()) {
            Some(dt) => Box::new(dt),
            None => Box::new(None::<chrono::DateTime<chrono::Utc>>),
        },
    }
}

fn jwc_param_bool(v: V) -> Box<dyn tokio_postgres::types::ToSql + Sync + Send> {
    match v {
        V::Null => Box::new(None::<bool>),
        V::Bool(b) => Box::new(b),
        other => Box::new(jwc_truthy(&other)),
    }
}

// --- eager-load helper for `select ... with rel1, rel2 ...` ------------------
//
// One extra `SELECT * FROM <target> WHERE <fk> IN (...)` per relation, groups
// children by FK client-side. N+1 collapses to N+R.

fn jwc_v_to_key(v: &V) -> String {
    match v {
        V::Int(n) => n.to_string(),
        V::Float(n) => n.to_string(),
        V::Str(s) => s.clone(),
        V::Bool(b) => b.to_string(),
        V::Null => String::new(),
        V::Array(_) | V::Object(_) => jwc_to_json(v),
    }
}

// Boxing kind passed to `jwc_db_eager_load` so the IN-clause parameters
// match the FK column's actual Postgres width (i16/i32/i64). The plain bool
// `pk_is_int` flag this used to carry collapsed all integer widths onto i32
// and would re-trigger the INT4/INT8 mismatch bug for `bigint` FKs.
#[derive(Clone, Copy)]
enum JwcPkKind {
    Smallint,
    Int,
    Bigint,
    Str,
}

async fn jwc_db_eager_load(
    parents: &mut Vec<V>,
    parent_pk: &str,
    target_table: &str,
    fk_col: &str,
    pk_kind: JwcPkKind,
    nav_name: &str,
    one_to_one: bool,
) {
    if parents.is_empty() {
        return;
    }
    let mut keys: Vec<V> = Vec::new();
    for p in parents.iter() {
        if let V::Object(m) = p {
            if let Some(v) = m.get(parent_pk) {
                if !matches!(v, V::Null) {
                    keys.push(v.clone());
                }
            }
        }
    }
    if keys.is_empty() {
        for p in parents.iter_mut() {
            if let V::Object(m) = p {
                let val = if one_to_one { V::Null } else { V::Array(Vec::new()) };
                m.insert(nav_name.to_string(), val);
            }
        }
        return;
    }
    let placeholders: Vec<String> = (1..=keys.len()).map(|i| format!("${}", i)).collect();
    let sql = format!(
        "SELECT * FROM \"{}\" WHERE \"{}\" IN ({})",
        target_table,
        fk_col,
        placeholders.join(", "),
    );
    let params: DbParams = match pk_kind {
        JwcPkKind::Smallint => keys.into_iter().map(jwc_param_smallint).collect(),
        JwcPkKind::Int => keys.into_iter().map(jwc_param_int).collect(),
        JwcPkKind::Bigint => keys.into_iter().map(jwc_param_bigint).collect(),
        JwcPkKind::Str => keys.into_iter().map(jwc_param_str).collect(),
    };
    let children = jwc_db_query(&sql, params).await;
    let mut by_fk: BTreeMap<String, Vec<V>> = BTreeMap::new();
    for c in children {
        if let V::Object(ref m) = c {
            if let Some(k) = m.get(fk_col) {
                let key = jwc_v_to_key(k);
                by_fk.entry(key).or_default().push(c);
                continue;
            }
        }
    }
    for p in parents.iter_mut() {
        if let V::Object(m) = p {
            let key = m.get(parent_pk).map(jwc_v_to_key).unwrap_or_default();
            let attached = by_fk.remove(&key).unwrap_or_default();
            let val = if one_to_one {
                attached.into_iter().next().unwrap_or(V::Null)
            } else {
                V::Array(attached)
            };
            m.insert(nav_name.to_string(), val);
        }
    }
}

// --- raw_sql -----------------------------------------------------------------
//
// Escape hatch for SQL the typed query builder doesn't cover (json_agg,
// window functions, ad-hoc analytics). Mirrors the interpreter:
//   * SELECT / WITH → return the first column of the first row as text
//     (or V::Null if no rows). Useful for `SELECT COUNT(*)`, `SELECT json_agg(...)::text`.
//   * Anything else → run as `execute` and return the affected rowcount as int.
//
// `params_json` is a JSON-encoded array of values bound positionally as $1, $2,
// .... It's variadic in JWC source (1 or 2 args); the codegen pads the missing
// param to `V::Str("[]")`.

async fn jwc_b_raw_sql(sql: V, params_json: V) -> V {
    let sql_s = match sql {
        V::Str(s) => s,
        _ => return V::Null,
    };

    let raw = match params_json {
        V::Str(s) => s,
        V::Null => "[]".to_string(),
        _ => "[]".to_string(),
    };
    let params: Vec<V> = match jwc_from_json(&raw) {
        Ok(V::Array(a)) => a,
        _ => Vec::new(),
    };
    // raw_sql doesn't know the prepared statement's parameter types up
    // front, so pick the narrowest integer width the value still fits in.
    // Mirrors `runner::value_to_sql_param` so the AOT and interpreter paths
    // agree on which `INT2`/`INT4`/`INT8` column a JWC int will bind to.
    let boxed: DbParams = params
        .into_iter()
        .map(|p| match p {
            V::Int(n) => {
                if (i32::MIN as i64..=i32::MAX as i64).contains(&n) {
                    Box::new(n as i32) as Box<dyn tokio_postgres::types::ToSql + Sync + Send>
                } else {
                    Box::new(n)
                }
            }
            V::Float(_) => jwc_param_float(p),
            V::Bool(_) => jwc_param_bool(p),
            _ => jwc_param_str(p),
        })
        .collect();

    let lowered = sql_s.trim_start().to_ascii_lowercase();
    if lowered.starts_with("select") || lowered.starts_with("with") {
        let rows = jwc_db_query(&sql_s, boxed).await;
        let Some(first) = rows.into_iter().next() else {
            return V::Null;
        };
        let V::Object(m) = first else {
            return V::Null;
        };
        // First-column-as-text: the only deterministic column ordering we have
        // is insertion order in the BTreeMap (alphabetic). Callers that care
        // about ordering should `SELECT col AS a` to force alphabetic ordering,
        // or use a single-column projection.
        let Some((_, v)) = m.into_iter().next() else {
            return V::Null;
        };
        match v {
            V::Str(s) => V::Str(s),
            V::Int(n) => V::Str(n.to_string()),
            V::Float(n) => V::Str(n.to_string()),
            V::Bool(b) => V::Str(b.to_string()),
            V::Null => V::Null,
            other => V::Str(jwc_to_json(&other)),
        }
    } else {
        let affected = jwc_db_exec(&sql_s, boxed).await;
        V::Int(affected as i64)
    }
}

// --- WebSocket runtime (async, RFC 6455, text frames) -----------------------
//
// Only included when the program declares at least one `route WS ...`. Uses
// tokio for non-blocking frame I/O. Limitations:
//   * Text and close frames returned to user code; binary surfaces as Str.
//   * No fragmentation: every frame must have FIN=1.
//   * No subprotocol negotiation; first match wins.

// --- SHA-1 (RFC 3174) — pure CPU, sync. -------------------------------------

fn jwc_sha1(message: &[u8]) -> [u8; 20] {
    let mut h: [u32; 5] = [
        0x6745_2301, 0xEFCD_AB89, 0x98BA_DCFE, 0x1032_5476, 0xC3D2_E1F0,
    ];
    let bit_len: u64 = (message.len() as u64).wrapping_mul(8);

    let mut padded = Vec::with_capacity(message.len() + 64);
    padded.extend_from_slice(message);
    padded.push(0x80);
    while padded.len() % 64 != 56 {
        padded.push(0);
    }
    padded.extend_from_slice(&bit_len.to_be_bytes());

    for chunk in padded.chunks_exact(64) {
        let mut w = [0u32; 80];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([
                chunk[i * 4], chunk[i * 4 + 1], chunk[i * 4 + 2], chunk[i * 4 + 3],
            ]);
        }
        for i in 16..80 {
            w[i] = (w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]).rotate_left(1);
        }
        let (mut a, mut b, mut c, mut d, mut e) = (h[0], h[1], h[2], h[3], h[4]);
        for i in 0..80 {
            let (f, k) = match i {
                0..=19 => ((b & c) | ((!b) & d), 0x5A82_7999),
                20..=39 => (b ^ c ^ d, 0x6ED9_EBA1),
                40..=59 => ((b & c) | (b & d) | (c & d), 0x8F1B_BCDC),
                _ => (b ^ c ^ d, 0xCA62_C1D6),
            };
            let tmp = a
                .rotate_left(5)
                .wrapping_add(f)
                .wrapping_add(e)
                .wrapping_add(k)
                .wrapping_add(w[i]);
            e = d;
            d = c;
            c = b.rotate_left(30);
            b = a;
            a = tmp;
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
    }

    let mut out = [0u8; 20];
    for (i, word) in h.iter().enumerate() {
        out[i * 4..i * 4 + 4].copy_from_slice(&word.to_be_bytes());
    }
    out
}

// --- base64 (RFC 4648 standard alphabet) ------------------------------------

fn jwc_base64_encode(input: &[u8]) -> String {
    const ALPHA: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((input.len() + 2) / 3 * 4);
    let mut i = 0;
    while i + 3 <= input.len() {
        let n = ((input[i] as u32) << 16) | ((input[i + 1] as u32) << 8) | (input[i + 2] as u32);
        out.push(ALPHA[((n >> 18) & 0x3F) as usize] as char);
        out.push(ALPHA[((n >> 12) & 0x3F) as usize] as char);
        out.push(ALPHA[((n >> 6) & 0x3F) as usize] as char);
        out.push(ALPHA[(n & 0x3F) as usize] as char);
        i += 3;
    }
    let rem = input.len() - i;
    if rem == 1 {
        let n = (input[i] as u32) << 16;
        out.push(ALPHA[((n >> 18) & 0x3F) as usize] as char);
        out.push(ALPHA[((n >> 12) & 0x3F) as usize] as char);
        out.push('=');
        out.push('=');
    } else if rem == 2 {
        let n = ((input[i] as u32) << 16) | ((input[i + 1] as u32) << 8);
        out.push(ALPHA[((n >> 18) & 0x3F) as usize] as char);
        out.push(ALPHA[((n >> 12) & 0x3F) as usize] as char);
        out.push(ALPHA[((n >> 6) & 0x3F) as usize] as char);
        out.push('=');
    }
    out
}

const WS_GUID: &str = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";

fn ws_accept_for_key(client_key: &str) -> String {
    let combined = format!("{}{}", client_key.trim(), WS_GUID);
    let digest = jwc_sha1(combined.as_bytes());
    jwc_base64_encode(&digest)
}

async fn ws_send_handshake_response(
    stream: &mut tokio::net::TcpStream,
    accept: &str,
) -> std::io::Result<()> {
    let resp = format!(
        "HTTP/1.1 101 Switching Protocols\r\n\
         Upgrade: websocket\r\n\
         Connection: Upgrade\r\n\
         Sec-WebSocket-Accept: {}\r\n\
         \r\n",
        accept
    );
    tokio::io::AsyncWriteExt::write_all(stream, resp.as_bytes()).await
}

// --- frame I/O --------------------------------------------------------------

const WS_OP_TEXT: u8 = 0x1;
const WS_OP_BINARY: u8 = 0x2;
const WS_OP_CLOSE: u8 = 0x8;
const WS_OP_PING: u8 = 0x9;
const WS_OP_PONG: u8 = 0xA;

enum WsFrame {
    Text(String),
    Binary(Vec<u8>),
    Close,
    Ping(Vec<u8>),
    Pong(Vec<u8>),
}

async fn ws_read_exact(stream: &mut tokio::net::TcpStream, n: usize) -> std::io::Result<Vec<u8>> {
    let mut buf = vec![0u8; n];
    tokio::io::AsyncReadExt::read_exact(stream, &mut buf).await?;
    Ok(buf)
}

async fn ws_read_frame(stream: &mut tokio::net::TcpStream) -> std::io::Result<WsFrame> {
    let hdr = ws_read_exact(stream, 2).await?;
    let _fin = (hdr[0] & 0x80) != 0;
    let opcode = hdr[0] & 0x0F;
    let masked = (hdr[1] & 0x80) != 0;
    let mut len: u64 = (hdr[1] & 0x7F) as u64;
    if len == 126 {
        let ext = ws_read_exact(stream, 2).await?;
        len = u16::from_be_bytes([ext[0], ext[1]]) as u64;
    } else if len == 127 {
        let ext = ws_read_exact(stream, 8).await?;
        len = u64::from_be_bytes([
            ext[0], ext[1], ext[2], ext[3], ext[4], ext[5], ext[6], ext[7],
        ]);
    }
    let mask = if masked { ws_read_exact(stream, 4).await? } else { Vec::new() };
    let mut payload = ws_read_exact(stream, len as usize).await?;
    if masked {
        for (i, b) in payload.iter_mut().enumerate() {
            *b ^= mask[i & 3];
        }
    }
    let frame = match opcode {
        WS_OP_TEXT => WsFrame::Text(String::from_utf8_lossy(&payload).to_string()),
        WS_OP_BINARY => WsFrame::Binary(payload),
        WS_OP_CLOSE => WsFrame::Close,
        WS_OP_PING => WsFrame::Ping(payload),
        WS_OP_PONG => WsFrame::Pong(payload),
        _ => WsFrame::Close,
    };
    Ok(frame)
}

async fn ws_write_frame(
    stream: &mut tokio::net::TcpStream,
    opcode: u8,
    payload: &[u8],
) -> std::io::Result<()> {
    let mut out = Vec::with_capacity(payload.len() + 10);
    out.push(0x80 | opcode);
    if payload.len() < 126 {
        out.push(payload.len() as u8);
    } else if payload.len() <= u16::MAX as usize {
        out.push(126);
        out.extend_from_slice(&(payload.len() as u16).to_be_bytes());
    } else {
        out.push(127);
        out.extend_from_slice(&(payload.len() as u64).to_be_bytes());
    }
    out.extend_from_slice(payload);
    tokio::io::AsyncWriteExt::write_all(stream, &out).await
}

// --- per-handler shared stream (task-local Arc<Mutex<...>>) -----------------

tokio::task_local! {
    static WS_STREAM: std::sync::Arc<tokio::sync::Mutex<tokio::net::TcpStream>>;
}

// --- built-ins exposed to JWC code ------------------------------------------

async fn jwc_b_ws_send(msg: V) -> V {
    let text = match msg {
        V::Str(s) => s,
        other => jwc_to_json(&other),
    };
    let arc = match WS_STREAM.try_with(|s| s.clone()) {
        Ok(a) => a,
        Err(_) => panic!("ws_send(): only valid inside a WS route handler"),
    };
    let mut s = arc.lock().await;
    match ws_write_frame(&mut *s, WS_OP_TEXT, text.as_bytes()).await {
        Ok(()) => V::Bool(true),
        Err(_) => V::Bool(false),
    }
}

async fn jwc_b_ws_recv() -> V {
    let arc = match WS_STREAM.try_with(|s| s.clone()) {
        Ok(a) => a,
        Err(_) => panic!("ws_recv(): only valid inside a WS route handler"),
    };
    loop {
        let frame_res = {
            let mut s = arc.lock().await;
            ws_read_frame(&mut *s).await
        };
        let frame = match frame_res {
            Ok(f) => f,
            Err(_) => return V::Null,
        };
        match frame {
            WsFrame::Text(s) => return V::Str(s),
            WsFrame::Binary(b) => return V::Str(String::from_utf8_lossy(&b).to_string()),
            WsFrame::Ping(payload) => {
                let mut s = arc.lock().await;
                let _ = ws_write_frame(&mut *s, WS_OP_PONG, &payload).await;
            }
            WsFrame::Pong(_) => {}
            WsFrame::Close => return V::Null,
        }
    }
}

async fn jwc_b_ws_close() -> V {
    if let Ok(arc) = WS_STREAM.try_with(|s| s.clone()) {
        let mut s = arc.lock().await;
        let _ = ws_write_frame(&mut *s, WS_OP_CLOSE, &[]).await;
    }
    V::Null
}

// --- dispatcher called from handle_connection (HTTP prelude) ----------------

async fn jwc_run_ws_handler(
    mut stream: tokio::net::TcpStream,
    req: &Request,
    handler: fn() -> std::pin::Pin<Box<dyn std::future::Future<Output = V> + Send>>,
) {
    let key = match req.headers.get("sec-websocket-key") {
        Some(k) => k.clone(),
        None => {
            let body = "Missing Sec-WebSocket-Key";
            let resp = format!(
                "HTTP/1.1 400 Bad Request\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
                body.len(),
                body,
            );
            let _ = tokio::io::AsyncWriteExt::write_all(&mut stream, resp.as_bytes()).await;
            return;
        }
    };
    let accept = ws_accept_for_key(&key);
    if ws_send_handshake_response(&mut stream, &accept).await.is_err() {
        return;
    }
    let arc = std::sync::Arc::new(tokio::sync::Mutex::new(stream));
    let scope_arc = arc.clone();
    WS_STREAM
        .scope(scope_arc, async move {
            let _ = handler().await;
        })
        .await;
    let mut s = arc.lock().await;
    let _ = ws_write_frame(&mut *s, WS_OP_CLOSE, &[]).await;
}


fn user_main() -> std::pin::Pin<Box<dyn std::future::Future<Output = V> + Send>> {
    Box::pin(async move {
        let _ = jwc_b_setConnectionString().await;
        let mut row: V = V::Object(std::collections::BTreeMap::new());
        { let __rhs = V::Str("/healthz".to_string()); jwc_set_field(&mut row, "path", __rhs); }
        { let __rhs = V::Str("GET".to_string()); jwc_set_field(&mut row, "method", __rhs); }
        { let __rhs = V::Int(200i64); jwc_set_field(&mut row, "status", __rhs); }
        { let __rhs = V::Int(0i64); jwc_set_field(&mut row, "latency_ms", __rhs); }
        { let __rhs = jwc_b_now(); jwc_set_field(&mut row, "ts", __rhs); }
        {
            let __var = &row;
            let __params: DbParams = vec![
                jwc_param_str(jwc_get_field(__var, "path")),
                jwc_param_str(jwc_get_field(__var, "method")),
                jwc_param_int(jwc_get_field(__var, "status")),
                jwc_param_int(jwc_get_field(__var, "latency_ms")),
                jwc_param_timestamp(jwc_get_field(__var, "ts")),
            ];
            let _ = jwc_db_exec("INSERT INTO \"api_call\" (\"path\", \"method\", \"status\", \"latency_ms\", \"ts\") VALUES ($1, $2, $3, $4, $5)", __params).await;
        }
        if let Some(__r) = jwc_take_return() { return __r; }
        V::Null
    })
}

async fn jwc_serve_impl(port: u16) {
    let mut router = Router::new();
    HttpServer::new(port, router).run().await;
}

#[tokio::main(flavor = "multi_thread")]
async fn main() {
    jwc_load_dotenv();
    let _ = user_main().await;
}
