import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'JWC',
  tagline: 'A backend-first language for SQL-native business-logic APIs',
  favicon: 'img/favicon.ico',

  url: 'https://jwc.1kb.uz',
  baseUrl: '/',

  organizationName: 'just-web-code',
  projectName: 'jwc-lang',

  // Every canonical tag and every sitemap entry is emitted without a
  // trailing slash, so say so explicitly and keep nginx serving the same
  // shape. One URL per page is the whole point: the slashed form used to
  // be a second live URL that 301'd back here.
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  // A dead in-page anchor is a dead link to a crawler too; two of them sat
  // in the build output as warnings for long enough to prove that warning
  // isn't enough.
  onBrokenAnchors: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          // The 0.9.x documentation, archived at the v0.25.0 cutover. It
          // describes the language deployed 0.9.x binaries implement, not
          // this compiler; the site is rewritten from `spec/v1/` in
          // v1.0.0-rc.1 (ROADMAP).
          path: 'archive-0.9',
          // The 0.9.x *specification* and the two READMEs are repo documents,
          // not site pages. The spec lived at `docs/spec/` and the 0.9.x
          // README at the repository root — both outside the Docusaurus tree
          // — until the cutover moved them under `archive-0.9/`, which is the
          // content root. The sidebar is autogenerated from the whole
          // directory, so the move alone enrolled them as pages, and MDX
          // rejected the four that use plain-Markdown `<https://…>` autolinks
          // or write `Arc<Mutex<TcpStream>>` outside a fence. Nothing here was
          // ever served: the build has failed on every commit since the move.
          //
          // `README.md` is excluded for a second reason. Docusaurus routes a
          // folder's README like its index, so it claimed `/` — the slug
          // `intro.md` declares — and the build answered "Duplicate routes
          // found … non-deterministic routing behavior". Which of the two the
          // homepage resolved to was luck, and one of them is a note saying
          // this directory is an archive.
          //
          // `exclude` REPLACES the plugin default rather than adding to it,
          // so the four default patterns are restated below.
          exclude: [
            '**/_*.{js,jsx,ts,tsx,md,mdx}',
            '**/_*/**',
            '**/*.test.{js,jsx,ts,tsx}',
            '**/__tests__/**',
            'spec/**',
            'README.md',
            'README-0.9.md',
          ],
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',          // serve docs at site root, no /docs/ prefix
          editUrl:
            'https://github.com/just-web-code/jwc-lang/edit/main/docs/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: {
          // `lastmod` from git history gives crawlers a real recrawl signal;
          // without it every entry looks equally stale.
          lastmod: 'date',
          changefreq: 'weekly',
          priority: 0.5,
        },
      } satisfies Preset.Options,
    ],
  ],

  // JSON-LD. Search engines have no other way to learn that "JWC" here is a
  // programming language and not the three-letter acronym they already rank.
  headTags: [
    {
      tagName: 'script',
      attributes: {type: 'application/ld+json'},
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'JWC',
        alternateName: 'Just Web Code',
        applicationCategory: 'DeveloperApplication',
        operatingSystem: 'Linux, Windows, macOS',
        description:
          'A backend-first programming language with first-class HTTP routes, ' +
          'entities that compile to SQL, and Postgres execution.',
        url: 'https://jwc.1kb.uz',
        image: 'https://jwc.1kb.uz/img/jwc-social-card.png',
        codeRepository: 'https://github.com/just-web-code/jwc-lang',
        programmingLanguage: 'Rust',
        // No `license` / `offers` here on purpose: the repo carries no
        // LICENSE file yet (Cargo.toml: "workspace-private until a license
        // decision lands"), and structured data is a claim, not decoration.
      }),
    },
  ],

  themeConfig: {
    image: 'img/jwc-social-card.png',
    metadata: [
      {
        name: 'keywords',
        content:
          'jwc, jwc language, just web code, backend language, postgres, ' +
          'sql, http routes, entities, orm alternative, rest api, crud',
      },
      {name: 'twitter:card', content: 'summary_large_image'},
    ],
    navbar: {
      title: 'JWC',
      logo: {
        alt: 'JWC hummingbird logo',
        src: 'img/logo.png',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://registry-jwc.1kb.uz/',
          label: 'Registry',
          position: 'right',
        },
        {
          href: 'https://github.com/just-web-code/jwc-lang',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Learn',
          items: [
            {label: 'Getting started', to: '/getting-started/install'},
            {label: 'Language', to: '/language/syntax'},
            {label: 'Data (SQL)', to: '/data/dbcontext'},
            {label: 'Backend', to: '/backend/routes'},
            {label: 'CLI reference', to: '/cli/overview'},
          ],
        },
        {
          title: 'Tools',
          items: [
            {label: 'Registry', href: 'https://registry-jwc.1kb.uz/'},
            {label: 'GitHub', href: 'https://github.com/just-web-code/jwc-lang'},
            {label: 'Roadmap', href: 'https://github.com/just-web-code/jwc-lang/blob/main/ROADMAP.md'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} JWC. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'sql', 'bash', 'json'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
