//! `jwcproj.lock` — reproducible-build manifest of resolved dependencies.
//!
//! The file format is JSON (matching the rest of the project's config; we
//! deliberately avoid pulling in a TOML parser just for one file). The
//! lockfile is regenerated by `jwc add/update/install` and consumed by
//! `jwc run/serve/test` before any source parsing.
//!
//! Schema:
//!
//! ```json
//! {
//!   "version": 1,
//!   "package": [
//!     {
//!       "name": "http",
//!       "version": "1.2.3",
//!       "source": "registry+https://registry.example/",
//!       "checksum": "sha256:...",
//!       "dependencies": ["json@1.0.0"]
//!     }
//!   ]
//! }
//! ```
//!
//! Packages are sorted by name for stable diffs.

use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::project::LOCK_FILE;

const CURRENT_LOCK_VERSION: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct JwcLockfile {
    pub version: u32,
    #[serde(default)]
    pub package: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    /// Source URI: `registry+https://...`, `git+https://...?rev=<sha>`, or
    /// `path+<rel-path>`. Format mirrors Cargo's source encoding so the lock
    /// file shape is recognisable.
    pub source: String,
    /// SHA-256 hex of the tarball / git-snapshot contents. Empty for path
    /// sources (path sources are resolved fresh from disk every run).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub checksum: String,
    /// Transitive dep references in `name@version` form. Used to reconstruct
    /// the graph without re-resolving.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl Default for JwcLockfile {
    fn default() -> Self {
        Self {
            version: CURRENT_LOCK_VERSION,
            package: Vec::new(),
        }
    }
}

impl JwcLockfile {
    pub fn new() -> Self {
        Self::default()
    }

    /// Load the lockfile from `<root>/jwcproj.lock`. Returns `Ok(None)` if
    /// the file does not exist (a project without any dependencies, or one
    /// that hasn't been resolved yet).
    pub fn load(root: &Path) -> Result<Option<Self>> {
        let path = root.join(LOCK_FILE);
        if !path.is_file() {
            return Ok(None);
        }
        let raw = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        let mut lock: JwcLockfile = serde_json::from_str(&raw)
            .with_context(|| format!("Failed to parse {}", path.display()))?;
        if lock.version > CURRENT_LOCK_VERSION {
            anyhow::bail!(
                "{} declares unsupported lockfile version {} (this jwc supports up to v{})",
                path.display(),
                lock.version,
                CURRENT_LOCK_VERSION,
            );
        }
        lock.package.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Some(lock))
    }

    /// Write the lockfile to `<root>/jwcproj.lock`. Packages are sorted by
    /// name first to keep diffs minimal across resolver re-runs.
    pub fn save(&self, root: &Path) -> Result<()> {
        let path = root.join(LOCK_FILE);
        let mut out = self.clone();
        out.version = CURRENT_LOCK_VERSION;
        out.package.sort_by(|a, b| a.name.cmp(&b.name));
        let json = serde_json::to_string_pretty(&out)?;
        std::fs::write(&path, json + "\n")
            .with_context(|| format!("Failed to write {}", path.display()))?;
        Ok(())
    }

    pub fn find(&self, name: &str) -> Option<&LockedPackage> {
        self.package.iter().find(|p| p.name == name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_through_json() {
        let lock = JwcLockfile {
            version: 1,
            package: vec![
                LockedPackage {
                    name: "http".to_string(),
                    version: "1.2.3".to_string(),
                    source: "registry+https://registry.example/".to_string(),
                    checksum: "abc123".to_string(),
                    dependencies: vec!["json@1.0.0".to_string()],
                },
                LockedPackage {
                    name: "auth".to_string(),
                    version: "0.4.0".to_string(),
                    source: "git+https://example.com/auth.git?rev=deadbeef".to_string(),
                    checksum: String::new(),
                    dependencies: vec![],
                },
            ],
        };
        let json = serde_json::to_string_pretty(&lock).unwrap();
        let parsed: JwcLockfile = serde_json::from_str(&json).unwrap();
        // Equality is order-sensitive on the Vec; load() sorts so the
        // observable behaviour is stable.
        parsed
            .package
            .iter()
            .for_each(|p| assert!(!p.name.is_empty()));
        assert_eq!(parsed.version, lock.version);
    }
}
