//! Migration generation — the diff, lowered to files.
//!
//! `jwc migrate new <name>` reads the last snapshot, computes the current
//! one from source, diffs, and writes a migration (migrations.md §1). It
//! never connects to a database.
//!
//! Every statement is rendered by `ddl.rs`, from the snapshot form of the
//! object. `gen-sql` renders the same way, so what a migration applies
//! cannot drift from what a fresh schema would create — which is the
//! property the round-trip test measures.
//!
//! ## Why `down` is a diff and not an inverse table
//!
//! The down file is generated by diffing the *other way*: from the state
//! this migration produces back to the state it started from. That gets the
//! phases, the view drops and the ordering right for free, and there is no
//! second table of inverses to keep in step with the first.
//!
//! It is suppressed entirely when the migration contains an irreversible
//! operation (§9.2). A partial down leaves a database that is neither the
//! old shape nor the new one, and `migrate down` refuses to run a file
//! carrying a marker anyway — so the statements it would have contained
//! could never run. Promising a reversibility that cannot exist is worse
//! than refusing it.

use crate::ddl;
use crate::diag::Diagnostic;
use crate::diff::{self, Change, CommentTarget, Constraint, Op, Phase};
use crate::model::SchemaModel;
use crate::naming::quote_ident;
use crate::snapshot::{self, Snapshot};
use crate::workspace::Loc;

/// The marker an applier honours to run a file outside a transaction
/// (§5.2). First line of the file, or it is not honoured.
pub const NO_TRANSACTION: &str = "-- jwc:no-transaction";

/// Where a `.data.sql` sidecar is spliced in (§7.2, phase 3).
pub const DATA_MARKER: &str = "-- jwc:data";

/// What `migrate down` refuses to run.
pub const IRREVERSIBLE: &str = "-- irreversible:";

/// One file on disk.
pub struct File {
    pub stem: String,
    pub up: String,
    pub down: String,
    /// Written on the **last** file of a migration only, so the snapshot
    /// records a state that is reached once every part has applied.
    pub snapshot: Option<String>,
    pub no_transaction: bool,
}

pub struct Plan {
    pub files: Vec<File>,
    pub diags: Vec<(Loc, Diagnostic)>,
    /// One line per operation, for `--explain`.
    pub explain: Vec<Explained>,
}

pub struct Explained {
    pub phase: Phase,
    pub text: String,
    pub loc: Option<Loc>,
}

impl Plan {
    pub fn has_errors(&self) -> bool {
        self.diags
            .iter()
            .any(|(_, d)| d.severity == crate::diag::Severity::Error)
    }

    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }
}

/// Everything `jwc migrate new` would write, without writing it.
pub fn plan(prev: &Snapshot, model: &SchemaModel, ordinal: u32, name: &str) -> Plan {
    let next = snapshot::of(model);
    let src = diff::Source::of(model);
    let d = diff::compute(prev, &next, &src);

    let explain = d
        .changes
        .iter()
        .map(|c| Explained {
            phase: c.op.phase(),
            text: c.op.describe(),
            loc: c.loc,
        })
        .collect();

    if d.is_empty() || d.has_errors() {
        return Plan {
            files: Vec::new(),
            diags: d.diags,
            explain,
        };
    }

    // §5.2 — `ALTER TYPE … ADD VALUE` cannot share a transaction with
    // anything, so it becomes its own file. It goes *first*: a default or a
    // backfill in the ordinary file may name the value it adds.
    let (loose, boxed): (Vec<&Change>, Vec<&Change>) = d
        .changes
        .iter()
        .partition(|c| c.op.needs_no_transaction());

    let down_source = inverse_source(&src, prev);
    let markers_of = |cs: &[&Change]| -> Vec<String> {
        cs.iter()
            .filter(|c| !c.op.reversible())
            .map(|c| format!("{IRREVERSIBLE} {}", why(&c.op)))
            .collect()
    };

    let mut files: Vec<File> = Vec::new();
    let mut ord = ordinal;
    if !loose.is_empty() {
        let stem = snapshot::stem(ord, &format!("{name}_enum_values"));
        files.push(File {
            up: render_no_transaction(&stem, &loose),
            down: refusal(&stem, &markers_of(&loose)),
            stem,
            snapshot: None,
            no_transaction: true,
        });
        ord += 1;
    }
    // Only when there is something left to do. An `ADD VALUE` on its own is
    // one file, not one file plus an empty transaction.
    if !boxed.is_empty() {
        let stem = snapshot::stem(ord, name);
        let markers = markers_of(&boxed);
        let down = if markers.is_empty() {
            let back = diff::compute(&d.effective, prev, &down_source);
            let refs: Vec<&Change> = back.changes.iter().collect();
            render(&stem, &refs, &format!("down of {stem}"), false)
        } else {
            refusal(&stem, &markers)
        };
        let up = render(&stem, &boxed, &stem, true);
        files.push(File {
            up,
            down,
            stem,
            snapshot: None,
            no_transaction: false,
        });
    }
    // The snapshot goes on the **last** file: it records a state that is
    // only reached once every part of the migration has applied.
    if let Some(last) = files.last_mut() {
        last.snapshot = Some(d.effective.to_json());
    }

    Plan {
        files,
        diags: d.diags,
        explain,
    }
}

/// Renaming back: `display_name was "name"` reversed is `name was
/// "display_name"`, under whatever the table was called *before*.
fn inverse_source(src: &diff::Source, prev: &Snapshot) -> diff::Source {
    let mut out = diff::Source::default();
    for (key, old) in &src.table_was {
        let Some((schema, _new)) = key.rsplit_once('.') else {
            continue;
        };
        if let Some(new) = key.rsplit('.').next() {
            out.table_was
                .insert(format!("{schema}.{old}"), new.to_string());
        }
    }
    for (key, old) in &src.column_was {
        let parts: Vec<&str> = key.split('.').collect();
        let [schema, table, new] = parts[..] else {
            continue;
        };
        // The table may itself be renamed back, in which case the column
        // lives under its old name in the target state.
        let table = src
            .table_was
            .get(&format!("{schema}.{table}"))
            .map(|s| s.as_str())
            .unwrap_or(table);
        // A `was` naming nothing was refused on the way out; on the way back
        // it would be a second, confusing diagnostic, so only real ones are
        // carried over.
        if prev
            .table(schema, table)
            .is_some_and(|t| t.column(old).is_some())
        {
            out.column_was
                .insert(format!("{schema}.{table}.{old}"), new.to_string());
        }
    }
    out
}

fn refusal(stem: &str, markers: &[String]) -> String {
    let mut out = header(&format!("down of {stem}"));
    out.push('\n');
    for m in markers {
        out.push_str(m);
        out.push('\n');
    }
    out.push_str("-- (no down migration is generated for this migration)\n");
    out
}

/// The sentence that goes next to an `-- irreversible:` marker.
fn why(op: &Op) -> String {
    match op {
        Op::DropColumn {
            schema,
            table,
            column,
        } => format!(
            "dropping {schema}.{table}.{} loses data",
            column.name
        ),
        Op::DropTable(t) => format!("dropping {}.{} loses data", t.schema, t.name),
        Op::AddEnumValue {
            schema,
            name,
            value,
            ..
        } => format!(
            "Postgres cannot remove enum value '{value}' from {schema}.{name}"
        ),
        other => format!("{} cannot be undone", other.kind()),
    }
}

fn header(title: &str) -> String {
    format!(
        "-- Generated by `jwc migrate new`. Do not edit.\n\
         -- {title}\n"
    )
}

fn phase_title(p: Phase) -> &'static str {
    match p {
        Phase::DropView => "drop view",
        Phase::Create => "schemas and types",
        Phase::Column => "tables and columns",
        Phase::Data => "data",
        Phase::Constraint => "constraints",
        Phase::Index => "indexes",
        Phase::Trigger => "functions and triggers",
        Phase::Comment => "comments",
        Phase::CreateView => "create view",
        Phase::Destructive => "destructive",
    }
}

fn render(stem: &str, changes: &[&Change], title: &str, data_marker: bool) -> String {
    let mut out = header(title);
    out.push_str(
        "--\n-- Phases (migrations.md §4): drop view, schemas and types, tables and\n\
         -- columns, data, constraints, indexes, functions and triggers, comments,\n\
         -- create view, destructive.\n\n",
    );
    out.push_str("BEGIN;\n");

    let mut phase: Option<Phase> = None;
    for c in changes {
        let p = c.op.phase();
        if data_marker && phase.is_some_and(|x| x < Phase::Data) && p > Phase::Data {
            push_data_marker(&mut out, stem);
        }
        if phase != Some(p) {
            out.push_str(&format!("\n-- ── {} · {} ──\n", p as u8, phase_title(p)));
            phase = Some(p);
        }
        out.push_str(&sql(&c.op));
        out.push('\n');
    }
    if data_marker && phase.is_none_or(|x| x < Phase::Data) {
        push_data_marker(&mut out, stem);
    }

    out.push_str("\nCOMMIT;\n");
    out
}

fn push_data_marker(out: &mut String, stem: &str) {
    out.push_str(&format!(
        "\n-- ── {} · {} ──\n{DATA_MARKER} {stem}\n\
         -- A `{stem}.data.sql` sidecar, if present, is applied here\n\
         -- (migrations.md §7.2). It is hand-written and never generated.\n",
        Phase::Data as u8,
        phase_title(Phase::Data)
    ));
}

fn render_no_transaction(stem: &str, changes: &[&Change]) -> String {
    let mut out = String::from(NO_TRANSACTION);
    out.push('\n');
    out.push_str(&header(stem));
    out.push_str(
        "--\n-- `ALTER TYPE … ADD VALUE` cannot run inside a transaction block, so\n\
         -- this file is applied outside one and contains nothing else — a partial\n\
         -- failure cannot leave half a schema change applied (migrations.md §5.2,\n\
         -- E1101).\n\n",
    );
    for c in changes {
        out.push_str(&sql(&c.op));
        out.push('\n');
    }
    out
}

// ── one operation, one statement ───────────────────────────────────────

fn qualified(schema: &str, name: &str) -> String {
    format!("{}.{}", quote_ident(schema), quote_ident(name))
}

pub fn sql(op: &Op) -> String {
    match op {
        Op::CreateSchema(s) => ddl::create_schema(s),
        Op::CreateEnum(e) => ddl::create_type(e),
        Op::AddEnumValue {
            schema,
            name,
            value,
            before,
        } => {
            // `IF NOT EXISTS` because this statement runs outside a
            // transaction: a retry after a partial failure has to be safe.
            let mut s = format!(
                "ALTER TYPE {} ADD VALUE IF NOT EXISTS {}",
                qualified(schema, name),
                literal(value)
            );
            if let Some(b) = before {
                s.push_str(&format!(" BEFORE {}", literal(b)));
            }
            s.push(';');
            s
        }
        Op::CreateTable(t) => ddl::create_table(t),
        Op::RenameTable { schema, from, to } => format!(
            "ALTER TABLE {} RENAME TO {};",
            qualified(schema, from),
            quote_ident(to)
        ),
        Op::AddColumn {
            schema,
            table,
            column,
        } => ddl::add_column(&qualified(schema, table), column),
        Op::RenameColumn {
            schema,
            table,
            from,
            to,
        } => format!(
            "ALTER TABLE {} RENAME COLUMN {} TO {};",
            qualified(schema, table),
            quote_ident(from),
            quote_ident(to)
        ),
        Op::AlterColumnType {
            schema,
            table,
            column,
            to,
            ..
        } => format!(
            // The `USING` is explicit even where Postgres would manage
            // without one: an enum or a text-to-number change has no
            // implicit cast, and leaving it out turns a working migration
            // into "column cannot be cast automatically" on the one schema
            // that needed it.
            "ALTER TABLE {} ALTER COLUMN {} TYPE {to} USING {}::{to};",
            qualified(schema, table),
            quote_ident(column),
            quote_ident(column)
        ),
        Op::SetNotNull {
            schema,
            table,
            column,
        } => format!(
            "ALTER TABLE {} ALTER COLUMN {} SET NOT NULL;",
            qualified(schema, table),
            quote_ident(column)
        ),
        Op::DropNotNull {
            schema,
            table,
            column,
        } => format!(
            "ALTER TABLE {} ALTER COLUMN {} DROP NOT NULL;",
            qualified(schema, table),
            quote_ident(column)
        ),
        Op::SetDefault {
            schema,
            table,
            column,
            value,
        } => format!(
            "ALTER TABLE {} ALTER COLUMN {} SET DEFAULT {value};",
            qualified(schema, table),
            quote_ident(column)
        ),
        Op::DropDefault {
            schema,
            table,
            column,
        } => format!(
            "ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT;",
            qualified(schema, table),
            quote_ident(column)
        ),
        Op::SetIdentity {
            schema,
            table,
            column,
        } => format!(
            "ALTER TABLE {} ALTER COLUMN {} ADD GENERATED BY DEFAULT AS IDENTITY;",
            qualified(schema, table),
            quote_ident(column)
        ),
        Op::DropIdentity {
            schema,
            table,
            column,
        } => format!(
            "ALTER TABLE {} ALTER COLUMN {} DROP IDENTITY IF EXISTS;",
            qualified(schema, table),
            quote_ident(column)
        ),
        Op::AddConstraint {
            schema,
            table,
            constraint,
        } => {
            let q = qualified(schema, table);
            match constraint {
                Constraint::PrimaryKey(pk) => format!(
                    "ALTER TABLE {q} ADD CONSTRAINT {} PRIMARY KEY ({});",
                    quote_ident(&pk.name),
                    idents(&pk.columns)
                ),
                Constraint::Unique(u) => format!(
                    "ALTER TABLE {q} ADD CONSTRAINT {} UNIQUE ({});",
                    quote_ident(&u.name),
                    idents(&u.columns)
                ),
                Constraint::Check(c) => format!(
                    "ALTER TABLE {q} ADD CONSTRAINT {} CHECK ({});",
                    quote_ident(&c.name),
                    c.expr
                ),
                Constraint::ForeignKey(f) => ddl::add_foreign_key(&q, f),
            }
        }
        Op::DropConstraint {
            schema,
            table,
            name,
            ..
        } => format!(
            "ALTER TABLE {} DROP CONSTRAINT {};",
            qualified(schema, table),
            quote_ident(name)
        ),
        Op::RenameConstraint {
            schema,
            table,
            from,
            to,
        } => format!(
            "ALTER TABLE {} RENAME CONSTRAINT {} TO {};",
            qualified(schema, table),
            quote_ident(from),
            quote_ident(to)
        ),
        Op::CreateIndex {
            schema,
            table,
            index,
        } => ddl::create_index(&qualified(schema, table), index),
        Op::DropIndex { schema, name, .. } => {
            format!("DROP INDEX {};", qualified(schema, name))
        }
        Op::RenameIndex { schema, from, to } => format!(
            "ALTER INDEX {} RENAME TO {};",
            qualified(schema, from),
            quote_ident(to)
        ),
        Op::CreateFunction(f) => ddl::create_function(f),
        Op::DropFunction { schema, name } => {
            format!("DROP FUNCTION IF EXISTS {}();", qualified(schema, name))
        }
        Op::CreateTrigger(t) => ddl::create_trigger(t),
        Op::DropTrigger {
            schema,
            table,
            name,
            ..
        } => format!(
            "DROP TRIGGER IF EXISTS {} ON {};",
            quote_ident(name),
            qualified(schema, table)
        ),
        Op::CommentOn { target, text } => match target {
            CommentTarget::Table { schema, name } => {
                ddl::comment_on("TABLE", &qualified(schema, name), text.as_deref())
            }
            CommentTarget::Column {
                schema,
                table,
                name,
            } => ddl::comment_on(
                "COLUMN",
                &format!("{}.{}", qualified(schema, table), quote_ident(name)),
                text.as_deref(),
            ),
            CommentTarget::View { schema, name } => {
                ddl::comment_on("VIEW", &qualified(schema, name), text.as_deref())
            }
        },
        Op::CreateView(v) => ddl::create_view(&v.qualified(), &v.body),
        Op::DropView { schema, name } => format!("DROP VIEW {};", qualified(schema, name)),
        Op::DropColumn {
            schema,
            table,
            column,
        } => format!(
            "ALTER TABLE {} DROP COLUMN {};",
            qualified(schema, table),
            quote_ident(&column.name)
        ),
        Op::DropTable(t) => format!("DROP TABLE {};", qualified(&t.schema, &t.name)),
    }
}

fn idents(cols: &[String]) -> String {
    cols.iter()
        .map(|c| quote_ident(c))
        .collect::<Vec<_>>()
        .join(", ")
}

fn literal(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

// ── E1101 ──────────────────────────────────────────────────────────────

/// A `-- jwc:no-transaction` file may contain nothing but the statements
/// that need to be outside one (§5.2). The generator never writes such a
/// file, but the files are checked in and editable, and a hand-added
/// statement there would be applied with no transaction to roll it back.
pub fn check_no_transaction(text: &str) -> Result<(), String> {
    if !text.starts_with(NO_TRANSACTION) {
        return Ok(());
    }
    for stmt in statements(text) {
        let upper = stmt.to_uppercase();
        let ok = upper.starts_with("ALTER TYPE") && upper.contains("ADD VALUE");
        if !ok {
            let first: String = stmt.split_whitespace().take(4).collect::<Vec<_>>().join(" ");
            return Err(format!(
                "a `{NO_TRANSACTION}` file may contain only `ALTER TYPE … ADD VALUE`, \
                 found `{first}`"
            ));
        }
    }
    Ok(())
}

/// Split SQL into statements on semicolons that are not inside a string
/// literal or a dollar-quoted body, dropping comments and blank lines.
pub fn statements(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut current = String::new();
    let mut in_dollar = false;
    for raw in text.lines() {
        let line = raw.trim_end();
        if !in_dollar {
            let trimmed = line.trim_start();
            if trimmed.is_empty() || trimmed.starts_with("--") {
                continue;
            }
        }
        // `$$` opens and closes a function body, in which `;` and `--` mean
        // nothing to the splitter.
        if !line.matches("$$").count().is_multiple_of(2) {
            in_dollar = !in_dollar;
        }
        current.push_str(line);
        current.push('\n');
        if in_dollar {
            continue;
        }
        // A `;` inside a quoted string is not a terminator; an odd number of
        // quotes so far means we are inside one.
        if line.trim_end().ends_with(';') && current.matches('\'').count().is_multiple_of(2) {
            out.push(current.trim().trim_end_matches(';').trim().to_string());
            current.clear();
        }
    }
    let rest = current.trim();
    if !rest.is_empty() {
        out.push(rest.to_string());
    }
    out
}
