use std::collections::BTreeMap;

use anyhow::{bail, Result};

use crate::ast::{EntityDecl, FieldMods, Program, TypeSpec};
use crate::sql;

pub fn generate_postgres_migration_sql(old: &Program, new: &Program) -> Result<String> {
    let old_entities = index_entities(old);
    let new_entities = index_entities(new);

    let mut out = String::new();
    out.push_str("-- Generated by jwc (diff-sql)\n");

    // Create new tables
    for (key, new_entity) in &new_entities {
        if !old_entities.contains_key(key) {
            out.push_str(&sql::generate_postgres_table_sql(new_entity)?);
            out.push('\n');
        }
    }

    // Diff existing tables
    for (key, old_entity) in &old_entities {
        if let Some(new_entity) = new_entities.get(key) {
            out.push_str(&diff_entity(old_entity, new_entity)?);
        } else {
            // Keep conservative defaults: do not drop tables implicitly.
            bail!(
                "Entity '{}' was removed; DROP TABLE migrations are not supported in this prototype",
                old_entity.name
            );
        }
    }

    Ok(out)
}

fn index_entities(program: &Program) -> BTreeMap<String, EntityDecl> {
    let mut map = BTreeMap::new();
    for entity in &program.entities {
        map.insert(entity.name.to_lowercase(), entity.clone());
    }
    map
}

fn diff_entity(old: &EntityDecl, new: &EntityDecl) -> Result<String> {
    let table = sql::to_snake_case(&new.name);
    let old_fields = index_fields(old);
    let new_fields = index_fields(new);

    let mut statements: Vec<String> = Vec::new();

    // Added fields
    for (key, new_field) in &new_fields {
        if !old_fields.contains_key(key) {
            let (sql_type, _) = sql::map_type_postgres(&new_field.ty, &new_field.name)?;
            let null_sql = if new_field.mods.nullable { "NULL" } else { "NOT NULL" };
            statements.push(format!(
                "ALTER TABLE \"{}\" ADD COLUMN \"{}\" {} {};",
                table, new_field.name, sql_type, null_sql
            ));

            statements.extend(unique_constraint_delta(
                &table,
                &new_field.name,
                false,
                new_field.mods.unique,
            ));

            statements.extend(int_range_constraint_delta(
                &table,
                &new_field.name,
                &TypeSpec {
                    name: "int".to_string(),
                    args: vec![],
                },
                &new_field.ty,
                true,
            )?);
        }
    }

    // Removed fields
    for (key, old_field) in &old_fields {
        if !new_fields.contains_key(key) {
            statements.push(format!(
                "ALTER TABLE \"{}\" DROP COLUMN \"{}\";",
                table, old_field.name
            ));
        }
    }

    // Modified fields
    for (key, old_field) in &old_fields {
        if let Some(new_field) = new_fields.get(key) {
            if old_field.ty != new_field.ty {
                let (sql_type, _) = sql::map_type_postgres(&new_field.ty, &new_field.name)?;
                statements.push(format!(
                    "ALTER TABLE \"{}\" ALTER COLUMN \"{}\" TYPE {};",
                    table, new_field.name, sql_type
                ));

                statements.extend(int_range_constraint_delta(
                    &table,
                    &new_field.name,
                    &old_field.ty,
                    &new_field.ty,
                    false,
                )?);
            }

            if old_field.mods.nullable != new_field.mods.nullable {
                if new_field.mods.nullable {
                    statements.push(format!(
                        "ALTER TABLE \"{}\" ALTER COLUMN \"{}\" DROP NOT NULL;",
                        table, new_field.name
                    ));
                } else {
                    statements.push(format!(
                        "ALTER TABLE \"{}\" ALTER COLUMN \"{}\" SET NOT NULL;",
                        table, new_field.name
                    ));
                }
            }

            if old_field.mods.unique != new_field.mods.unique {
                statements.extend(unique_constraint_delta(
                    &table,
                    &new_field.name,
                    old_field.mods.unique,
                    new_field.mods.unique,
                ));
            }
        }
    }

    if statements.is_empty() {
        return Ok(String::new());
    }

    Ok(statements.join("\n") + "\n")
}

#[derive(Clone)]
struct FieldRef {
    name: String,
    ty: TypeSpec,
    mods: FieldMods,
}

fn index_fields(entity: &EntityDecl) -> BTreeMap<String, FieldRef> {
    let mut map = BTreeMap::new();
    for f in &entity.fields {
        map.insert(
            f.name.to_lowercase(),
            FieldRef {
                name: f.name.clone(),
                ty: f.ty.clone(),
                mods: f.mods.clone(),
            },
        );
    }
    map
}

fn unique_constraint_delta(
    table: &str,
    field: &str,
    old_unique: bool,
    new_unique: bool,
) -> Vec<String> {
    let constraint = format!("uq_{}_{}", table, field);
    let mut statements = Vec::new();

    if old_unique && !new_unique {
        statements.push(format!(
            "ALTER TABLE \"{}\" DROP CONSTRAINT IF EXISTS \"{}\";",
            table, constraint
        ));
    }
    if !old_unique && new_unique {
        statements.push(format!(
            "ALTER TABLE \"{}\" ADD CONSTRAINT \"{}\" UNIQUE (\"{}\");",
            table, constraint, field
        ));
    }

    statements
}

fn int_range_constraint_delta(
    table: &str,
    field_name: &str,
    old_ty: &TypeSpec,
    new_ty: &TypeSpec,
    is_add_column: bool,
) -> Result<Vec<String>> {
    // Only manage constraints for `int(min,max)`.
    let old_has_range = old_ty.name == "int" && old_ty.args.len() == 2;
    let new_has_range = new_ty.name == "int" && new_ty.args.len() == 2;

    if !old_has_range && !new_has_range {
        return Ok(vec![]);
    }

    let constraint_name = format!("ck_{}_range", field_name);
    let mut statements = Vec::new();

    // When adding a column, there can't be an existing constraint name collision.
    // When altering, drop old constraint if it existed.
    if !is_add_column && old_has_range {
        statements.push(format!(
            "ALTER TABLE \"{}\" DROP CONSTRAINT IF EXISTS \"{}\";",
            table, constraint_name
        ));
    }

    if new_has_range {
        let min = new_ty.args[0];
        let max = new_ty.args[1];
        if min > max {
            bail!("int(min,max) requires min <= max for field '{field_name}'");
        }
        statements.push(format!(
            "ALTER TABLE \"{}\" ADD CONSTRAINT \"{}\" CHECK (\"{}\" >= {} AND \"{}\" <= {});",
            table, constraint_name, field_name, min, field_name, max
        ));
    }

    Ok(statements)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    #[test]
    fn diffs_added_column_and_type_change() {
        let old_src = r#"
            entity User {
                id uuid;
                age int(0,200);
            }
        "#;
        let new_src = r#"
            entity User {
                id uuid;
                age int(0,120);
                name text(50);
            }
        "#;
        let old = parse_program(old_src).unwrap();
        let new = parse_program(new_src).unwrap();
        validate_program(&old).unwrap();
        validate_program(&new).unwrap();

        let sql = generate_postgres_migration_sql(&old, &new).unwrap();
        assert!(sql.contains("ALTER TABLE \"user\" ADD COLUMN \"name\" varchar(50) NOT NULL;"));
        assert!(sql.contains("DROP CONSTRAINT IF EXISTS \"ck_age_range\""));
        assert!(sql.contains("ADD CONSTRAINT \"ck_age_range\" CHECK (\"age\" >= 0 AND \"age\" <= 120)"));
    }

    #[test]
    fn diffs_new_entity_as_create_table() {
        let old_src = r#"entity User { id uuid; }"#;
        let new_src = r#"
            entity User { id uuid; }
            entity Post { id uuid; }
        "#;
        let old = parse_program(old_src).unwrap();
        let new = parse_program(new_src).unwrap();
        validate_program(&old).unwrap();
        validate_program(&new).unwrap();

        let sql = generate_postgres_migration_sql(&old, &new).unwrap();
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS \"post\""));
    }

    #[test]
    fn diffs_nullability_and_unique() {
        let old_src = r#"
            entity User {
                email text;
                nickname text nullable;
            }
        "#;
        let new_src = r#"
            entity User {
                email text unique;
                nickname text;
            }
        "#;
        let old = parse_program(old_src).unwrap();
        let new = parse_program(new_src).unwrap();
        validate_program(&old).unwrap();
        validate_program(&new).unwrap();

        let sql = generate_postgres_migration_sql(&old, &new).unwrap();
        assert!(sql.contains("ADD CONSTRAINT \"uq_user_email\" UNIQUE (\"email\")"));
        assert!(sql.contains("ALTER TABLE \"user\" ALTER COLUMN \"nickname\" SET NOT NULL"));
    }
}
