use std::collections::HashMap;

use anyhow::{anyhow, Result};

use crate::ast::{CmpOp, EntityDecl, Expr, Literal, Program, SelectTarget};

pub fn generate_postgres_queries_sql(program: &Program) -> Result<String> {
    let mut out = String::new();
    out.push_str("-- Generated by jwc (gen-query-sql)\n");

    if program.selects.is_empty() {
        return Ok(out);
    }

    let mut entity_by_name: HashMap<String, &EntityDecl> = HashMap::new();
    let mut entity_by_table: HashMap<String, &EntityDecl> = HashMap::new();
    for entity in &program.entities {
        entity_by_name.insert(entity.name.to_lowercase(), entity);
        entity_by_table.insert(crate::sql::to_snake_case(&entity.name), entity);
    }

    for select in &program.selects {
        let from_key = select.from.to_lowercase();
        let entity = entity_by_name
            .get(&from_key)
            .copied()
            .or_else(|| entity_by_table.get(&from_key).copied())
            .ok_or_else(|| anyhow!("select from unknown entity/table: {}", select.from))?;
        let table = crate::sql::to_snake_case(&entity.name);

        let projection = match &select.target {
            SelectTarget::Star | SelectTarget::Entity(_) => "*".to_string(),
            SelectTarget::Fields(fields) => fields
                .iter()
                .map(|f| format!("\"{}\"", f))
                .collect::<Vec<_>>()
                .join(", "),
        };

        out.push_str(&format!("SELECT {} FROM \"{}\"", projection, table));

        if let Some(expr) = &select.where_expr {
            out.push_str(" WHERE ");
            out.push_str(&expr_to_sql(expr));
        }

        out.push_str(";\n");
    }

    Ok(out)
}

fn expr_to_sql(expr: &Expr) -> String {
    match expr {
        Expr::Cmp(c) => format!(
            "\"{}\" {} {}",
            c.field,
            cmp_op_to_sql(&c.op),
            literal_to_sql(&c.value)
        ),
        Expr::And(l, r) => format!("({} AND {})", expr_to_sql(l), expr_to_sql(r)),
        Expr::Or(l, r) => format!("({} OR {})", expr_to_sql(l), expr_to_sql(r)),
    }
}

fn cmp_op_to_sql(op: &CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "=",
        CmpOp::Gt => ">",
        CmpOp::Lt => "<",
        CmpOp::Gte => ">=",
        CmpOp::Lte => "<=",
    }
}

fn literal_to_sql(lit: &Literal) -> String {
    match lit {
        Literal::Int(v) => v.to_string(),
        Literal::Decimal(s) => s.clone(),
        Literal::Bool(true) => "TRUE".to_string(),
        Literal::Bool(false) => "FALSE".to_string(),
        Literal::Str(s) => format!("'{}'", s.replace("'", "''")),
        Literal::Array(_) => "NULL".to_string(),
        Literal::Obj(_) => "NULL".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    #[test]
    fn generates_select_sql_with_and_or() {
        let src = r#"
            entity User { age int; active bool; name text; }
            select * from User where age > 18 and active = true or name = "a";
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();

        let sql = generate_postgres_queries_sql(&program).unwrap();
        assert!(sql.contains("SELECT * FROM \"user\" WHERE"));
        assert!(sql.contains("AND"));
        assert!(sql.contains("OR"));
        assert!(sql.contains("'a'"));
    }

    #[test]
    fn generates_select_sql_with_projection_list() {
        let src = r#"
            entity User { id uuid; name text; active bool; }
            select id, name from User where active = true;
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();

        let sql = generate_postgres_queries_sql(&program).unwrap();
        assert!(sql.contains("SELECT \"id\", \"name\" FROM \"user\""));
    }
}
