//! Schema diff engine for incremental migrations.
//!
//! `jwc migrate new <name>` previously rewrote the full schema on every
//! invocation, so even small changes (e.g. adding one column) produced a
//! 100-line `CREATE TABLE` migration that conflicted with the existing
//! tables. This module computes a structural diff between the latest
//! committed migration snapshot (parsed from the most recent `*.up.sql`
//! generated by jwc) and the current entity definitions, then emits the
//! minimal set of `CREATE TABLE` / `ALTER TABLE` / `DROP TABLE` statements
//! needed to bring the schema up to date.
//!
//! Foreign-key diffs and primary-key changes are intentionally out of
//! scope for now — the generated DDL only covers tables and columns
//! (add / drop / type change / nullability flip). FK creation is still
//! emitted on full `CreateTable` ops so brand-new entities keep their
//! relationships.
//!
//! ## Canonical DDL format we parse
//!
//! `sql::generate_postgres_table_sql` always writes tables in this exact
//! shape, which the regex-based parser below relies on:
//!
//! ```text
//! CREATE TABLE IF NOT EXISTS "table_name" (
//!     "col1" type NOT NULL,
//!     "col2" type,
//!     CONSTRAINT "fk_..." FOREIGN KEY (...) REFERENCES "..." (...),
//!     CONSTRAINT "ck_..." CHECK (...),
//!     PRIMARY KEY ("col1")
//! );
//! ```
//!
//! Anything that doesn't match this shape (ALTER statements, comments,
//! hand-edited DDL) is skipped — we only parse what jwc itself wrote.

use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use regex::Regex;

use crate::ast::{ModelDecl, ModelKind, OnDeleteAction, Program};
use crate::sql::{map_type_postgres, to_snake_case};

/// One column in a parsed/snapshotted table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnSnapshot {
    pub name: String,
    /// Lower-cased SQL type, e.g. `"integer"`, `"varchar(120)"`, `"uuid"`.
    pub sql_type: String,
    pub is_nullable: bool,
    pub is_primary_key: bool,
    /// `GENERATED BY DEFAULT AS IDENTITY` was emitted for this column.
    /// Round-tripped from prior migrations by `parse_column_line` so
    /// `migrate new` doesn't pretend to re-add identity columns.
    pub is_auto_increment: bool,
    /// A table-level `UNIQUE ("col")` constraint was emitted for this column
    /// (from `entity X { col ... unique; }`). Round-tripped from prior
    /// migrations so `migrate new` doesn't re-add the constraint.
    pub is_unique: bool,
    /// A standalone `CREATE INDEX` was emitted for this column (from
    /// `entity X { col ... index; }`). Round-tripped from prior migrations
    /// so `migrate new` neither re-creates an existing index nor misses a
    /// newly declared one.
    pub is_indexed: bool,
    /// Foreign-key target for `entity X { col uuid references Y.id ... }`.
    /// Populated by `entity_to_snapshot`; the DDL parser does NOT extract
    /// FK constraints from prior migrations (FK diff is intentionally
    /// out of scope), so any snapshot reconstructed from disk leaves this
    /// at `None` regardless of what the migration originally contained.
    pub fk: Option<FkSnapshot>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FkSnapshot {
    /// Target table name in snake_case (matches what jwc emits).
    pub target_table: String,
    pub target_column: String,
    pub on_delete: OnDeleteAction,
}

/// One table — name plus ordered column list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableSnapshot {
    /// snake_case table name (matches what jwc writes to SQL).
    pub name: String,
    pub columns: Vec<ColumnSnapshot>,
}

/// A single DDL change between two snapshots.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DiffOp {
    CreateTable(TableSnapshot),
    DropTable(String),
    AddColumn {
        table: String,
        column: ColumnSnapshot,
    },
    DropColumn {
        table: String,
        column_name: String,
    },
    AlterColumnType {
        table: String,
        column_name: String,
        new_type: String,
    },
    SetNotNull {
        table: String,
        column_name: String,
    },
    DropNotNull {
        table: String,
        column_name: String,
    },
    AddUnique {
        table: String,
        column_name: String,
    },
    DropUnique {
        table: String,
        column_name: String,
    },
    CreateIndex {
        table: String,
        column_name: String,
    },
    DropIndex {
        table: String,
        column_name: String,
    },
}

// ---------------------------------------------------------------------------
// Snapshot construction from the in-memory Program
// ---------------------------------------------------------------------------

/// Build a snapshot for one `entity` model. Reuses `sql::map_type_postgres`
/// so the SQL type strings line up with what we actually emit when creating
/// the table, which is critical for `AlterColumnType` to compare apples to
/// apples.
pub fn entity_to_snapshot(model: &ModelDecl) -> Result<TableSnapshot> {
    if model.kind != ModelKind::Entity {
        return Err(anyhow!(
            "entity_to_snapshot called on non-entity model '{}'",
            model.name
        ));
    }

    let table_name = to_snake_case(&model.name);
    let mut columns = Vec::with_capacity(model.fields.len());

    for field in &model.fields {
        let (sql_type, _constraints) = map_type_postgres(&field.ty, &field.name)?;
        let fk = field.references.as_ref().map(|r| FkSnapshot {
            target_table: to_snake_case(&r.entity),
            target_column: r.column.clone(),
            on_delete: r.on_delete,
        });
        columns.push(ColumnSnapshot {
            name: field.name.clone(),
            sql_type,
            is_nullable: field.is_nullable,
            is_primary_key: field.is_primary_key,
            is_auto_increment: field.is_auto_increment,
            // A PK is already unique and the DDL skips a separate UNIQUE for
            // it, so mirror that here to stay diff-stable with the SQL parser.
            is_unique: field.is_unique && !field.is_primary_key,
            // `index_statements` skips PK / unique columns because those
            // already have an index; mirror that so the diff doesn't think
            // an index is missing every run.
            is_indexed: field.is_indexed && !field.is_primary_key && !field.is_unique,
            fk,
        });
    }

    Ok(TableSnapshot {
        name: table_name,
        columns,
    })
}

/// Convert an entire Program into the set of table snapshots that will be
/// compared against the on-disk state.
pub fn program_to_snapshots(program: &Program) -> Result<Vec<TableSnapshot>> {
    let mut out = Vec::new();
    for model in &program.models {
        if model.kind != ModelKind::Entity {
            continue;
        }
        out.push(entity_to_snapshot(model)?);
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Snapshot reconstruction from previously generated migrations
// ---------------------------------------------------------------------------

/// Locate and parse the most recent `*.up.sql` migration in `migrations_dir`.
///
/// Returns an empty vector when no migrations exist yet (fresh project), or
/// when the latest file contains no recognisable `CREATE TABLE` statements
/// (e.g. an `-- empty migration` placeholder).
pub fn read_latest_snapshot(migrations_dir: &Path) -> Result<Vec<TableSnapshot>> {
    if !migrations_dir.is_dir() {
        return Ok(Vec::new());
    }

    // Strategy: accumulate the parsed table set across ALL up.sql files in
    // chronological order. This lets us correctly track tables created in
    // one migration and altered in a later one. Each new file's CREATE TABLE
    // adds (or replaces) the snapshot; each ALTER TABLE applies on top.
    let mut up_files: Vec<PathBuf> = std::fs::read_dir(migrations_dir)
        .with_context(|| format!("Failed to read {}", migrations_dir.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.ends_with(".up.sql"))
                .unwrap_or(false)
        })
        .collect();
    up_files.sort();

    let mut tables: Vec<TableSnapshot> = Vec::new();

    for path in &up_files {
        let sql = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;

        // CREATE TABLE statements emitted by jwc.
        for parsed in parse_create_tables(&sql) {
            // Replace existing entry if a re-create snuck in, otherwise append.
            if let Some(slot) = tables.iter_mut().find(|t| t.name == parsed.name) {
                *slot = parsed;
            } else {
                tables.push(parsed);
            }
        }

        // ALTER TABLE statements emitted by this module on subsequent runs.
        apply_alter_statements(&sql, &mut tables);

        // DROP TABLE (in case a future op emits one) — keep snapshot honest.
        apply_drop_statements(&sql, &mut tables);
    }

    // CREATE INDEX / DROP INDEX in a second pass, once every table is known.
    //
    // These are standalone statements that reference a table by name, so
    // unlike a column definition they can't be read while that table may not
    // exist yet. Two migrations generated inside the same second sort by
    // name, which is enough to put an `add-index` file ahead of the
    // `initial` that creates the table — a single pass would silently drop
    // the flag there and re-propose the index on every later `migrate new`.
    for path in &up_files {
        let Ok(sql) = std::fs::read_to_string(path) else {
            continue;
        };
        apply_index_statements(&sql, &mut tables);
    }

    Ok(tables)
}

/// Parse zero or more canonical `CREATE TABLE IF NOT EXISTS "name" ( ... );`
/// statements out of a SQL blob. Anything else is ignored.
fn parse_create_tables(sql: &str) -> Vec<TableSnapshot> {
    // `(?is)` — case-insensitive + dot matches newlines. The body group is
    // non-greedy so multiple CREATE statements in one file each match their
    // own balanced parens.
    let create_re = Regex::new(
        r#"(?is)CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+"([A-Za-z_][A-Za-z0-9_]*)"\s*\(\s*(.+?)\s*\)\s*;"#,
    )
    .expect("static regex compiles");

    let mut out = Vec::new();

    for cap in create_re.captures_iter(sql) {
        let name = cap
            .get(1)
            .map(|m| m.as_str().to_string())
            .unwrap_or_default();
        let body = cap.get(2).map(|m| m.as_str()).unwrap_or("");

        let entries = split_top_level_commas(body);
        let mut columns: Vec<ColumnSnapshot> = Vec::new();
        let mut pk_cols: Vec<String> = Vec::new();
        let mut unique_cols: Vec<String> = Vec::new();

        for entry in entries {
            let entry = entry.trim();
            if entry.is_empty() {
                continue;
            }

            // PRIMARY KEY ("col1" [, "col2"])
            if let Some(rest) = strip_prefix_ci(entry, "PRIMARY KEY") {
                for col in extract_quoted_idents(rest) {
                    pk_cols.push(col);
                }
                continue;
            }

            // UNIQUE ("col") — table-level single-column unique we emit for
            // `unique` fields. (Composite UNIQUE is captured but only the
            // single-column form round-trips to a column `is_unique` flag.)
            if let Some(rest) = strip_prefix_ci(entry, "UNIQUE") {
                let cols = extract_quoted_idents(rest);
                if cols.len() == 1 {
                    unique_cols.push(cols[0].clone());
                }
                continue;
            }

            // CONSTRAINT "..." ... — FK/CHECK; skip for column parsing.
            if starts_with_ci(entry, "CONSTRAINT") {
                continue;
            }

            // Column line: `"name" type [NOT NULL]`. The type may itself
            // contain parens (e.g. `numeric(18,2)`) and may be followed by
            // additional column modifiers — we just look for `NOT NULL` at
            // the end and trim it.
            if let Some(col) = parse_column_line(entry) {
                columns.push(col);
            }
        }

        // Mark PK / UNIQUE columns now that the trailing constraint clauses
        // are known. A PK column never carries a separate UNIQUE flag (the
        // DDL doesn't emit one), keeping it consistent with entity_to_snapshot.
        for col in &mut columns {
            if pk_cols.iter().any(|p| p == &col.name) {
                col.is_primary_key = true;
            }
            if !col.is_primary_key && unique_cols.iter().any(|u| u == &col.name) {
                col.is_unique = true;
            }
        }

        out.push(TableSnapshot { name, columns });
    }

    out
}

/// Parse a single column declaration line such as `"id" uuid NOT NULL` or
/// `"price" numeric(18,2)`. Returns `None` for unrecognised shapes.
fn parse_column_line(entry: &str) -> Option<ColumnSnapshot> {
    let entry = entry.trim().trim_end_matches(',');

    // Name is the first quoted identifier.
    let col_re = Regex::new(r#"^"([A-Za-z_][A-Za-z0-9_]*)"\s+(.+)$"#).ok()?;
    let cap = col_re.captures(entry)?;
    let name = cap.get(1)?.as_str().to_string();
    let rest = cap.get(2)?.as_str().trim();

    // Detect trailing `NOT NULL`. Be tolerant of additional modifiers like
    // `DEFAULT ...` between the type and `NOT NULL`, although jwc doesn't
    // emit those yet.
    let upper = rest.to_uppercase();
    let is_nullable = !upper.contains("NOT NULL");
    let is_auto_increment = upper.contains("AS IDENTITY") || upper.contains("SERIAL");

    // Strip the `NOT NULL` tail, the `GENERATED ... AS IDENTITY` clause,
    // and any trailing whitespace so the remaining slice is just the SQL
    // type. Order matters: trim the identity phrase first, then NOT NULL.
    let mut sql_type = rest.to_string();
    let upper_for_strip = sql_type.to_uppercase();
    if let Some(idx) = upper_for_strip.find("GENERATED ") {
        sql_type.truncate(idx);
    }
    let upper_after_identity = sql_type.to_uppercase();
    if let Some(idx) = upper_after_identity.find("NOT NULL") {
        sql_type.truncate(idx);
    }
    let sql_type = sql_type.trim().trim_end_matches(',').trim().to_string();

    Some(ColumnSnapshot {
        name,
        sql_type: normalize_sql_type(&sql_type),
        is_nullable,
        is_primary_key: false, // PRIMARY KEY clause sets this in a later pass
        is_auto_increment,
        is_unique: false,  // UNIQUE clause sets this in a later pass
        is_indexed: false, // CREATE INDEX statements set this in a later pass
        fk: None,
    })
}

/// Lower-case the SQL type so comparisons against `map_type_postgres` output
/// are stable regardless of how the migration was written.
fn normalize_sql_type(ty: &str) -> String {
    // Collapse internal whitespace and lower-case. Keep parens / commas.
    let mut prev_space = false;
    let mut out = String::with_capacity(ty.len());
    for ch in ty.chars() {
        if ch.is_whitespace() {
            if !prev_space {
                out.push(' ');
                prev_space = true;
            }
        } else {
            out.push(ch.to_ascii_lowercase());
            prev_space = false;
        }
    }
    out.trim().to_string()
}

/// Split a comma-separated list while ignoring commas inside parentheses
/// (e.g. `numeric(18,2)` or `CHECK (a > 0 AND b < 10)`).
fn split_top_level_commas(s: &str) -> Vec<String> {
    let mut depth = 0i32;
    let mut current = String::new();
    let mut out = Vec::new();
    for ch in s.chars() {
        match ch {
            '(' => {
                depth += 1;
                current.push(ch);
            }
            ')' => {
                depth -= 1;
                current.push(ch);
            }
            ',' if depth == 0 => {
                out.push(std::mem::take(&mut current));
            }
            _ => current.push(ch),
        }
    }
    if !current.trim().is_empty() {
        out.push(current);
    }
    out
}

fn starts_with_ci(haystack: &str, needle: &str) -> bool {
    haystack
        .get(..needle.len())
        .map(|s| s.eq_ignore_ascii_case(needle))
        .unwrap_or(false)
}

fn strip_prefix_ci<'a>(haystack: &'a str, prefix: &str) -> Option<&'a str> {
    if starts_with_ci(haystack, prefix) {
        Some(&haystack[prefix.len()..])
    } else {
        None
    }
}

/// Extract every `"ident"` token from a string in order.
fn extract_quoted_idents(s: &str) -> Vec<String> {
    let re = Regex::new(r#""([A-Za-z_][A-Za-z0-9_]*)""#).expect("static regex compiles");
    re.captures_iter(s)
        .filter_map(|c| c.get(1).map(|m| m.as_str().to_string()))
        .collect()
}

/// Replay `ALTER TABLE` statements (the kind this module emits) onto the
/// running table set so cumulative state matches the latest migration's
/// "as-if applied" view.
fn apply_alter_statements(sql: &str, tables: &mut [TableSnapshot]) {
    // ALTER TABLE "t" ADD COLUMN "c" type [NOT NULL];
    let add_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+ADD\s+COLUMN\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+([^;]+?)\s*;"#,
    )
    .expect("static regex compiles");

    for cap in add_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let col = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        let tail = cap
            .get(3)
            .map(|m| m.as_str())
            .unwrap_or("")
            .trim()
            .to_string();
        let upper = tail.to_uppercase();
        let is_nullable = !upper.contains("NOT NULL");
        let mut sql_type = tail.clone();
        if let Some(idx) = upper.find("NOT NULL") {
            sql_type.truncate(idx);
        }
        let sql_type = normalize_sql_type(sql_type.trim());

        let is_auto_increment = upper.contains("AS IDENTITY") || upper.contains("SERIAL");

        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            t.columns.push(ColumnSnapshot {
                name: col,
                sql_type,
                is_nullable,
                is_primary_key: false,
                is_auto_increment,
                is_unique: false,
                is_indexed: false,
                fk: None,
            });
        }
    }

    // ALTER TABLE "t" DROP COLUMN "c";
    let drop_col_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+DROP\s+COLUMN\s+"([A-Za-z_][A-Za-z0-9_]*)"\s*;"#,
    )
    .expect("static regex compiles");
    for cap in drop_col_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let col = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            t.columns.retain(|c| c.name != col);
        }
    }

    // ALTER TABLE "t" ALTER COLUMN "c" TYPE newtype [USING ...];
    let type_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+ALTER\s+COLUMN\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+TYPE\s+([^;]+?)\s*;"#,
    )
    .expect("static regex compiles");
    for cap in type_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let col = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        let mut new_type = cap
            .get(3)
            .map(|m| m.as_str())
            .unwrap_or("")
            .trim()
            .to_string();
        // Strip optional `USING ...` tail so we keep only the type itself.
        if let Some(pos) = new_type.to_uppercase().find(" USING ") {
            new_type.truncate(pos);
        }
        let new_type = normalize_sql_type(new_type.trim());
        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            if let Some(c) = t.columns.iter_mut().find(|c| c.name == col) {
                c.sql_type = new_type;
            }
        }
    }

    // ALTER TABLE "t" ALTER COLUMN "c" SET NOT NULL;
    let set_nn_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+ALTER\s+COLUMN\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+SET\s+NOT\s+NULL\s*;"#,
    )
    .expect("static regex compiles");
    for cap in set_nn_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let col = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            if let Some(c) = t.columns.iter_mut().find(|c| c.name == col) {
                c.is_nullable = false;
            }
        }
    }

    // ALTER TABLE "t" ALTER COLUMN "c" DROP NOT NULL;
    let drop_nn_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+ALTER\s+COLUMN\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+DROP\s+NOT\s+NULL\s*;"#,
    )
    .expect("static regex compiles");
    for cap in drop_nn_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let col = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            if let Some(c) = t.columns.iter_mut().find(|c| c.name == col) {
                c.is_nullable = true;
            }
        }
    }

    // ALTER TABLE "t" ADD CONSTRAINT "..." UNIQUE ("c"); → mark column unique.
    let add_uniq_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+ADD\s+CONSTRAINT\s+"[^"]+"\s+UNIQUE\s*\(\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*\)\s*;"#,
    )
    .expect("static regex compiles");
    for cap in add_uniq_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let col = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            if let Some(c) = t.columns.iter_mut().find(|c| c.name == col) {
                c.is_unique = true;
            }
        }
    }

    // ALTER TABLE "t" DROP CONSTRAINT [IF EXISTS] "t_c_key"; → clear unique on
    // the column whose default constraint name matches.
    let drop_uniq_re = Regex::new(
        r#"(?is)ALTER\s+TABLE\s+"([A-Za-z_][A-Za-z0-9_]*)"\s+DROP\s+CONSTRAINT\s+(?:IF\s+EXISTS\s+)?"([^"]+)"\s*;"#,
    )
    .expect("static regex compiles");
    for cap in drop_uniq_re.captures_iter(sql) {
        let table = cap.get(1).map(|m| m.as_str()).unwrap_or("").to_string();
        let cname = cap.get(2).map(|m| m.as_str()).unwrap_or("").to_string();
        if let Some(t) = tables.iter_mut().find(|t| t.name == table) {
            for c in t.columns.iter_mut() {
                if cname == format!("{}_{}_key", table, c.name) {
                    c.is_unique = false;
                }
            }
        }
    }
}

/// Replay `DROP TABLE` statements onto the running snapshot.
/// Recover `is_indexed` from the `CREATE INDEX` / `DROP INDEX` statements a
/// previous migration emitted. Matches on the target table and column rather
/// than the index name, so an index a user added by hand under a different
/// name still counts as present and isn't proposed again.
fn apply_index_statements(sql: &str, tables: &mut [TableSnapshot]) {
    let create = Regex::new(
        r#"(?is)CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?"?[A-Za-z_][A-Za-z0-9_]*"?\s+ON\s+"([A-Za-z_][A-Za-z0-9_]*)"\s*\(\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*\)"#,
    )
    .expect("static regex compiles");
    for cap in create.captures_iter(sql) {
        let (Some(table), Some(col)) = (cap.get(1), cap.get(2)) else {
            continue;
        };
        if let Some(t) = tables.iter_mut().find(|t| t.name == table.as_str()) {
            if let Some(c) = t.columns.iter_mut().find(|c| c.name == col.as_str()) {
                c.is_indexed = true;
            }
        }
    }

    // `DROP INDEX "ix_<table>_<col>";` — the name is the only thing the
    // statement carries, so the convention is what we can match on.
    let drop =
        Regex::new(r#"(?is)DROP\s+INDEX\s+(?:IF\s+EXISTS\s+)?"ix_([A-Za-z_][A-Za-z0-9_]*)"\s*;"#)
            .expect("static regex compiles");
    for cap in drop.captures_iter(sql) {
        let Some(rest) = cap.get(1).map(|m| m.as_str()) else {
            continue;
        };
        for t in tables.iter_mut() {
            let Some(col_name) = rest.strip_prefix(&format!("{}_", t.name)) else {
                continue;
            };
            if let Some(c) = t.columns.iter_mut().find(|c| c.name == col_name) {
                c.is_indexed = false;
            }
        }
    }
}

fn apply_drop_statements(sql: &str, tables: &mut Vec<TableSnapshot>) {
    let re = Regex::new(r#"(?is)DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?"([A-Za-z_][A-Za-z0-9_]*)"\s*;"#)
        .expect("static regex compiles");
    for cap in re.captures_iter(sql) {
        if let Some(name) = cap.get(1).map(|m| m.as_str()) {
            tables.retain(|t| t.name != name);
        }
    }
}

// ---------------------------------------------------------------------------
// Diff computation
// ---------------------------------------------------------------------------

/// Compute the minimal `DiffOp` list that transforms `old` into `new`.
///
/// Ordering:
/// 1. `DropTable` first — drops anything no longer in the model.
/// 2. `CreateTable` next — adds brand-new tables.
/// 3. Per-table column ops (`AddColumn`, `DropColumn`, `AlterColumnType`,
///    `SetNotNull`, `DropNotNull`) in entity declaration order.
pub fn compute_diff(old: &[TableSnapshot], new: &[TableSnapshot]) -> Vec<DiffOp> {
    let mut ops: Vec<DiffOp> = Vec::new();

    // Drops first.
    for old_table in old {
        if !new.iter().any(|t| t.name == old_table.name) {
            ops.push(DiffOp::DropTable(old_table.name.clone()));
        }
    }

    // Creates next.
    for new_table in new {
        if !old.iter().any(|t| t.name == new_table.name) {
            ops.push(DiffOp::CreateTable(new_table.clone()));
        }
    }

    // Alters for tables present in both.
    for new_table in new {
        let Some(old_table) = old.iter().find(|t| t.name == new_table.name) else {
            continue;
        };

        // Dropped columns (in old but not new).
        for old_col in &old_table.columns {
            if !new_table.columns.iter().any(|c| c.name == old_col.name) {
                ops.push(DiffOp::DropColumn {
                    table: new_table.name.clone(),
                    column_name: old_col.name.clone(),
                });
            }
        }

        // Added / modified columns.
        for new_col in &new_table.columns {
            match old_table.columns.iter().find(|c| c.name == new_col.name) {
                None => {
                    ops.push(DiffOp::AddColumn {
                        table: new_table.name.clone(),
                        column: new_col.clone(),
                    });
                    // ADD COLUMN carries no index; emit one alongside.
                    if new_col.is_indexed {
                        ops.push(DiffOp::CreateIndex {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    }
                }
                Some(old_col) => {
                    if !sql_types_equal(&old_col.sql_type, &new_col.sql_type) {
                        ops.push(DiffOp::AlterColumnType {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                            new_type: new_col.sql_type.clone(),
                        });
                    }
                    if old_col.is_nullable && !new_col.is_nullable {
                        ops.push(DiffOp::SetNotNull {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    } else if !old_col.is_nullable && new_col.is_nullable {
                        ops.push(DiffOp::DropNotNull {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    }
                    // A `unique` modifier added to / removed from an existing
                    // column → ADD / DROP a UNIQUE constraint (pain log 2 #6).
                    if !old_col.is_unique && new_col.is_unique {
                        ops.push(DiffOp::AddUnique {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    } else if old_col.is_unique && !new_col.is_unique {
                        ops.push(DiffOp::DropUnique {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    }
                    // Same for an `index` modifier.
                    if !old_col.is_indexed && new_col.is_indexed {
                        ops.push(DiffOp::CreateIndex {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    } else if old_col.is_indexed && !new_col.is_indexed {
                        ops.push(DiffOp::DropIndex {
                            table: new_table.name.clone(),
                            column_name: new_col.name.clone(),
                        });
                    }
                }
            }
        }
    }

    ops
}

fn sql_types_equal(a: &str, b: &str) -> bool {
    normalize_sql_type(a) == normalize_sql_type(b)
}

// ---------------------------------------------------------------------------
// DDL emission
// ---------------------------------------------------------------------------

/// Render a list of diff ops as a Postgres migration body.
///
/// Returns `String::new()` for an empty diff so callers can detect "no
/// schema changes" without inspecting the string contents.
pub fn diff_to_sql(diff: &[DiffOp]) -> String {
    if diff.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("-- Generated by jwc (incremental diff)\n");

    for op in diff {
        match op {
            DiffOp::DropTable(name) => {
                out.push_str(&format!("DROP TABLE IF EXISTS \"{}\";\n", name));
            }
            DiffOp::CreateTable(snapshot) => {
                out.push_str(&render_create_table(snapshot));
            }
            DiffOp::AddColumn { table, column } => {
                let nn = if column.is_nullable { "" } else { " NOT NULL" };
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" ADD COLUMN \"{}\" {}{};\n",
                    table, column.name, column.sql_type, nn
                ));
            }
            DiffOp::DropColumn { table, column_name } => {
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" DROP COLUMN \"{}\";\n",
                    table, column_name
                ));
            }
            DiffOp::AlterColumnType {
                table,
                column_name,
                new_type,
            } => {
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" ALTER COLUMN \"{}\" TYPE {} USING \"{}\"::{};\n",
                    table, column_name, new_type, column_name, new_type
                ));
            }
            DiffOp::SetNotNull { table, column_name } => {
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" ALTER COLUMN \"{}\" SET NOT NULL;\n",
                    table, column_name
                ));
            }
            DiffOp::DropNotNull { table, column_name } => {
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" ALTER COLUMN \"{}\" DROP NOT NULL;\n",
                    table, column_name
                ));
            }
            DiffOp::AddUnique { table, column_name } => {
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" ADD CONSTRAINT \"{}_{}_key\" UNIQUE (\"{}\");\n",
                    table, table, column_name, column_name
                ));
            }
            DiffOp::DropUnique { table, column_name } => {
                out.push_str(&format!(
                    "ALTER TABLE \"{}\" DROP CONSTRAINT IF EXISTS \"{}_{}_key\";\n",
                    table, table, column_name
                ));
            }
            DiffOp::CreateIndex { table, column_name } => {
                out.push_str(&format!(
                    "CREATE INDEX IF NOT EXISTS \"ix_{}_{}\" ON \"{}\" (\"{}\");\n",
                    table, column_name, table, column_name
                ));
            }
            DiffOp::DropIndex { table, column_name } => {
                out.push_str(&format!(
                    "DROP INDEX IF EXISTS \"ix_{}_{}\";\n",
                    table, column_name
                ));
            }
        }
    }

    out
}

/// Render a `CREATE TABLE IF NOT EXISTS` for a snapshot. Used when an
/// entity is brand-new — emits columns and PK only (FKs are intentionally
/// out of scope for the diff engine; full FK emission happens through
/// `sql::generate_postgres_table_sql` for the bootstrap migration).
fn render_create_table(snapshot: &TableSnapshot) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut pk_cols: Vec<&str> = Vec::new();
    let mut unique_lines: Vec<String> = Vec::new();
    let mut fk_lines: Vec<String> = Vec::new();

    for col in &snapshot.columns {
        let identity = if col.is_auto_increment {
            " GENERATED BY DEFAULT AS IDENTITY"
        } else {
            ""
        };
        let nn = if col.is_nullable { "" } else { " NOT NULL" };
        lines.push(format!(
            "    \"{}\" {}{}{}",
            col.name, col.sql_type, identity, nn
        ));
        if col.is_primary_key {
            pk_cols.push(&col.name);
        }
        if col.is_unique && !col.is_primary_key {
            unique_lines.push(format!("    UNIQUE (\"{}\")", col.name));
        }
        if let Some(fk) = &col.fk {
            let mut clause = format!(
                "    CONSTRAINT \"fk_{}_{}\" FOREIGN KEY (\"{}\") REFERENCES \"{}\" (\"{}\")",
                snapshot.name, col.name, col.name, fk.target_table, fk.target_column
            );
            match fk.on_delete {
                OnDeleteAction::NoAction => {}
                OnDeleteAction::Cascade => clause.push_str(" ON DELETE CASCADE"),
                OnDeleteAction::Restrict => clause.push_str(" ON DELETE RESTRICT"),
                OnDeleteAction::SetNull => clause.push_str(" ON DELETE SET NULL"),
            }
            fk_lines.push(clause);
        }
    }

    if !pk_cols.is_empty() {
        let quoted = pk_cols
            .iter()
            .map(|c| format!("\"{}\"", c))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("    PRIMARY KEY ({})", quoted));
    }
    lines.extend(unique_lines);
    lines.extend(fk_lines);

    let mut out = String::new();
    out.push_str(&format!(
        "CREATE TABLE IF NOT EXISTS \"{}\" (\n",
        snapshot.name
    ));
    out.push_str(&lines.join(",\n"));
    out.push_str("\n);\n");
    // Indexes are standalone statements, so they follow the table — and must
    // be emitted here too, or a table created by `migrate new` would lose the
    // indexes that `gen-sql` gives the same entity.
    for col in &snapshot.columns {
        if col.is_indexed && !col.is_primary_key && !col.is_unique {
            out.push_str(&format!(
                "CREATE INDEX IF NOT EXISTS \"ix_{}_{}\" ON \"{}\" (\"{}\");\n",
                snapshot.name, col.name, snapshot.name, col.name
            ));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    fn col(name: &str, ty: &str, nullable: bool, pk: bool) -> ColumnSnapshot {
        ColumnSnapshot {
            name: name.to_string(),
            sql_type: ty.to_string(),
            is_nullable: nullable,
            is_primary_key: pk,
            is_auto_increment: false,
            is_unique: false,
            is_indexed: false,
            fk: None,
        }
    }

    fn table(name: &str, cols: Vec<ColumnSnapshot>) -> TableSnapshot {
        TableSnapshot {
            name: name.to_string(),
            columns: cols,
        }
    }

    #[test]
    fn empty_to_empty_is_empty_diff() {
        let diff = compute_diff(&[], &[]);
        assert!(diff.is_empty());
        assert_eq!(diff_to_sql(&diff), "");
    }

    #[test]
    fn new_entity_produces_create_table() {
        let new = vec![table(
            "user",
            vec![
                col("id", "uuid", false, true),
                col("name", "text", true, false),
            ],
        )];
        let diff = compute_diff(&[], &new);
        assert_eq!(diff.len(), 1);
        assert!(matches!(&diff[0], DiffOp::CreateTable(t) if t.name == "user"));

        let sql = diff_to_sql(&diff);
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS \"user\""));
        assert!(sql.contains("\"id\" uuid NOT NULL"));
        assert!(sql.contains("PRIMARY KEY (\"id\")"));
    }

    #[test]
    fn same_schema_produces_no_diff() {
        let snap = vec![table(
            "user",
            vec![
                col("id", "uuid", false, true),
                col("name", "text", true, false),
            ],
        )];
        let diff = compute_diff(&snap, &snap);
        assert!(diff.is_empty(), "expected empty diff, got {:?}", diff);
    }

    #[test]
    fn added_column_produces_add_column() {
        let old = vec![table("user", vec![col("id", "uuid", false, true)])];
        let new = vec![table(
            "user",
            vec![
                col("id", "uuid", false, true),
                col("email", "varchar(120)", false, false),
            ],
        )];
        let diff = compute_diff(&old, &new);
        assert_eq!(diff.len(), 1);
        match &diff[0] {
            DiffOp::AddColumn { table, column } => {
                assert_eq!(table, "user");
                assert_eq!(column.name, "email");
                assert_eq!(column.sql_type, "varchar(120)");
                assert!(!column.is_nullable);
            }
            other => panic!("expected AddColumn, got {:?}", other),
        }
        let sql = diff_to_sql(&diff);
        assert!(sql.contains("ALTER TABLE \"user\" ADD COLUMN \"email\" varchar(120) NOT NULL;"));
    }

    #[test]
    fn dropped_column_produces_drop_column() {
        let old = vec![table(
            "user",
            vec![
                col("id", "uuid", false, true),
                col("legacy", "text", true, false),
            ],
        )];
        let new = vec![table("user", vec![col("id", "uuid", false, true)])];
        let diff = compute_diff(&old, &new);
        assert_eq!(diff.len(), 1);
        assert!(matches!(
            &diff[0],
            DiffOp::DropColumn { table, column_name }
            if table == "user" && column_name == "legacy"
        ));
        let sql = diff_to_sql(&diff);
        assert!(sql.contains("ALTER TABLE \"user\" DROP COLUMN \"legacy\";"));
    }

    #[test]
    fn changed_nullable_emits_set_not_null_or_drop_not_null() {
        // nullable -> non-nullable
        let old = vec![table("user", vec![col("bio", "text", true, false)])];
        let new = vec![table("user", vec![col("bio", "text", false, false)])];
        let diff = compute_diff(&old, &new);
        assert_eq!(diff.len(), 1);
        assert!(matches!(&diff[0], DiffOp::SetNotNull { .. }));
        assert!(diff_to_sql(&diff).contains("SET NOT NULL"));

        // non-nullable -> nullable
        let diff2 = compute_diff(&new, &old);
        assert_eq!(diff2.len(), 1);
        assert!(matches!(&diff2[0], DiffOp::DropNotNull { .. }));
        assert!(diff_to_sql(&diff2).contains("DROP NOT NULL"));
    }

    #[test]
    fn changed_type_emits_alter_column_type() {
        let old = vec![table(
            "user",
            vec![col("name", "varchar(50)", false, false)],
        )];
        let new = vec![table(
            "user",
            vec![col("name", "varchar(120)", false, false)],
        )];
        let diff = compute_diff(&old, &new);
        assert_eq!(diff.len(), 1);
        assert!(matches!(
            &diff[0],
            DiffOp::AlterColumnType { new_type, .. } if new_type == "varchar(120)"
        ));
        let sql = diff_to_sql(&diff);
        assert!(sql.contains("ALTER COLUMN \"name\" TYPE varchar(120)"));
    }

    #[test]
    fn dropped_table_emits_drop_table() {
        let old = vec![table("ghost", vec![col("id", "uuid", false, true)])];
        let diff = compute_diff(&old, &[]);
        assert_eq!(diff.len(), 1);
        assert!(matches!(&diff[0], DiffOp::DropTable(n) if n == "ghost"));
        assert!(diff_to_sql(&diff).contains("DROP TABLE IF EXISTS \"ghost\";"));
    }

    #[test]
    fn parse_create_table_roundtrips_columns_and_pk() {
        let sql = r#"
-- Generated by jwc
CREATE TABLE IF NOT EXISTS "user" (
    "id" uuid NOT NULL,
    "email" varchar(120) NOT NULL,
    "bio" text,
    "amount" numeric(18,2) NOT NULL,
    PRIMARY KEY ("id")
);
"#;
        let tables = parse_create_tables(sql);
        assert_eq!(tables.len(), 1);
        let t = &tables[0];
        assert_eq!(t.name, "user");
        assert_eq!(t.columns.len(), 4);
        assert_eq!(t.columns[0].name, "id");
        assert!(!t.columns[0].is_nullable);
        assert!(t.columns[0].is_primary_key);
        assert_eq!(t.columns[1].sql_type, "varchar(120)");
        assert!(t.columns[2].is_nullable);
        assert_eq!(t.columns[3].sql_type, "numeric(18,2)");
    }

    #[test]
    fn autoincrement_round_trips_through_schema_diff() {
        let src = r#"
            entity Note {
                id int pk autoincrement;
                title varchar(120);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let snaps = program_to_snapshots(&program).unwrap();
        assert_eq!(snaps.len(), 1);
        assert!(snaps[0].columns[0].is_auto_increment);

        // Render → parse → diff against the original program. A clean round
        // trip means no phantom diff op is produced when nothing changed.
        let ddl = diff_to_sql(&compute_diff(&[], &snaps));
        let reparsed = parse_create_tables(&ddl);
        let diff = compute_diff(&reparsed, &snaps);
        assert!(
            diff.is_empty(),
            "expected empty diff after round trip, got {:?}",
            diff
        );
    }

    #[test]
    fn create_table_diff_emits_fk_constraints_for_new_entity() {
        let src = r#"
            entity User {
                id uuid pk;
                name varchar(60);
            }
            entity Post {
                id uuid pk;
                author_id uuid references User.id on delete cascade;
                title varchar(200);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let new_snaps = program_to_snapshots(&program).unwrap();
        let diff = compute_diff(&[], &new_snaps);
        let sql = diff_to_sql(&diff);
        assert!(
            sql.contains(
                "CONSTRAINT \"fk_post_author_id\" FOREIGN KEY (\"author_id\") REFERENCES \"user\" (\"id\") ON DELETE CASCADE"
            ),
            "FK lost in schema diff output:\n{sql}"
        );
    }

    #[test]
    fn entity_to_snapshot_matches_emitted_types() {
        let src = r#"
            entity User {
                id uuid pk;
                email varchar(120);
                bio text nullable;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let snaps = program_to_snapshots(&program).unwrap();
        assert_eq!(snaps.len(), 1);
        let user = &snaps[0];
        assert_eq!(user.name, "user");
        assert_eq!(user.columns.len(), 3);

        let id = &user.columns[0];
        assert_eq!(id.name, "id");
        assert_eq!(id.sql_type, "uuid");
        assert!(!id.is_nullable);
        assert!(id.is_primary_key);

        let email = &user.columns[1];
        assert_eq!(email.sql_type, "varchar(120)");
        assert!(!email.is_nullable);

        let bio = &user.columns[2];
        assert_eq!(bio.sql_type, "text");
        assert!(bio.is_nullable);
    }

    #[test]
    fn parse_then_diff_against_unchanged_entity_is_empty() {
        // Round-trip: generate canonical DDL for a program, parse it back,
        // and confirm the diff against the same program is empty.
        let src = r#"
            entity User {
                id uuid pk;
                email varchar(120);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let generated = crate::sql::generate_postgres_schema_sql(&program).unwrap();

        let parsed = parse_create_tables(&generated);
        let snapshots = program_to_snapshots(&program).unwrap();

        let diff = compute_diff(&parsed, &snapshots);
        assert!(
            diff.is_empty(),
            "expected empty diff between canonical SQL and its source program, got {:?}",
            diff
        );
    }

    #[test]
    fn replay_add_column_alter_persists_into_snapshot() {
        // Simulate two migration files: a CREATE TABLE then an ADD COLUMN.
        let mut tables: Vec<TableSnapshot> = parse_create_tables(
            r#"CREATE TABLE IF NOT EXISTS "user" (
    "id" uuid NOT NULL,
    PRIMARY KEY ("id")
);"#,
        );
        apply_alter_statements(
            r#"ALTER TABLE "user" ADD COLUMN "email" varchar(120) NOT NULL;"#,
            &mut tables,
        );
        assert_eq!(tables.len(), 1);
        assert_eq!(tables[0].columns.len(), 2);
        assert_eq!(tables[0].columns[1].name, "email");
        assert_eq!(tables[0].columns[1].sql_type, "varchar(120)");
        assert!(!tables[0].columns[1].is_nullable);
    }

    #[test]
    fn read_latest_snapshot_returns_empty_for_missing_dir() {
        let tmp = std::env::temp_dir().join("jwc-schema-diff-missing");
        let _ = std::fs::remove_dir_all(&tmp);
        let snaps = read_latest_snapshot(&tmp).unwrap();
        assert!(snaps.is_empty());
    }

    fn snapshots_of(src: &str) -> Vec<TableSnapshot> {
        let program = parse_program(src).expect("parses");
        validate_program(&program).expect("validates");
        program_to_snapshots(&program).expect("snapshots")
    }

    const WALLET_PLAIN: &str = r#"
        dbcontext Db: Postgres;
        entity Wallet of Db {
            id      int pk autoincrement;
            user_id int;
        }
    "#;
    const WALLET_INDEXED: &str = r#"
        dbcontext Db: Postgres;
        entity Wallet of Db {
            id      int pk autoincrement;
            user_id int index;
        }
    "#;

    /// Foreign-key columns were unindexed with no way to say otherwise, so
    /// every `where user_id == @u` was a sequential scan.
    #[test]
    fn declaring_index_emits_create_index() {
        let sql = diff_to_sql(&compute_diff(
            &snapshots_of(WALLET_PLAIN),
            &snapshots_of(WALLET_INDEXED),
        ));
        assert!(
            sql.contains(
                r#"CREATE INDEX IF NOT EXISTS "ix_wallet_user_id" ON "wallet" ("user_id")"#
            ),
            "got: {sql}"
        );
    }

    #[test]
    fn removing_index_emits_drop_index() {
        let sql = diff_to_sql(&compute_diff(
            &snapshots_of(WALLET_INDEXED),
            &snapshots_of(WALLET_PLAIN),
        ));
        assert!(
            sql.contains(r#"DROP INDEX IF EXISTS "ix_wallet_user_id""#),
            "got: {sql}"
        );
    }

    /// The index flag has to survive the SQL round-trip, or every later
    /// `migrate new` would re-propose an index that already exists.
    #[test]
    fn index_flag_round_trips_through_generated_sql() {
        let dir = std::env::temp_dir().join(format!("jwc-idx-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("mkdir");

        // Deliberately named so the index migration sorts BEFORE the table
        // that it references — two migrations made in the same second do
        // exactly this, and a single-pass reader loses the flag.
        let snaps = snapshots_of(WALLET_INDEXED);
        std::fs::write(
            dir.join("100_aaa-add-index.up.sql"),
            "CREATE INDEX IF NOT EXISTS \"ix_wallet_user_id\" ON \"wallet\" (\"user_id\");\n",
        )
        .unwrap();
        let mut create = diff_to_sql(&compute_diff(&[], &snaps));
        // Strip the index line so only the CREATE TABLE remains in this file.
        create = create
            .lines()
            .filter(|l| !l.starts_with("CREATE INDEX"))
            .collect::<Vec<_>>()
            .join("\n");
        std::fs::write(dir.join("100_bbb-initial.up.sql"), create).unwrap();

        let recovered = read_latest_snapshot(&dir).expect("reads");
        let col = recovered
            .iter()
            .find(|t| t.name == "wallet")
            .and_then(|t| t.columns.iter().find(|c| c.name == "user_id"))
            .expect("user_id column recovered");
        assert!(col.is_indexed, "index flag lost on round-trip");

        // Nothing left to do → an empty diff.
        assert!(
            compute_diff(&recovered, &snaps)
                .iter()
                .all(|op| !matches!(op, DiffOp::CreateIndex { .. })),
            "index was re-proposed after round-trip"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A PK or unique column already has an index; a second one would only
    /// cost writes.
    #[test]
    fn index_is_not_emitted_for_pk_or_unique_columns() {
        let snaps = snapshots_of(
            r#"
            dbcontext Db: Postgres;
            entity E of Db {
                id    int pk autoincrement index;
                email varchar(80) unique index;
            }
        "#,
        );
        let sql = diff_to_sql(&compute_diff(&[], &snaps));
        assert!(
            !sql.contains("CREATE INDEX"),
            "redundant index emitted: {sql}"
        );
    }
}
