use anyhow::{bail, Result};

use crate::ast::{EntityDecl, Program, TypeSpec};

pub fn generate_postgres_schema_sql(program: &Program) -> Result<String> {
    let mut out = String::new();
    out.push_str("-- Generated by jwc\n");

    for (idx, entity) in program.entities.iter().enumerate() {
        if idx != 0 {
            out.push('\n');
        }
        out.push_str(&generate_postgres_table_sql(entity)?);
        out.push('\n');
    }

    Ok(out)
}

pub(crate) fn generate_postgres_table_sql(entity: &EntityDecl) -> Result<String> {
    let table = to_snake_case(&entity.name);
    let mut lines: Vec<String> = Vec::new();
    let mut constraints: Vec<String> = Vec::new();

    let mut primary_key: Option<String> = None;

    for field in &entity.fields {
        let (sql_type, extra_constraints) = map_type_postgres(&field.ty, &field.name)?;

        let null_sql = if field.mods.nullable { "NULL" } else { "NOT NULL" };
        lines.push(format!("    \"{}\" {} {}", field.name, sql_type, null_sql));
        constraints.extend(extra_constraints);

        if field.mods.unique {
            constraints.push(format!(
                "CONSTRAINT \"uq_{}_{}\" UNIQUE (\"{}\")",
                table, field.name, field.name
            ));
        }
        if field.mods.primary_key {
            primary_key = Some(field.name.clone());
        }
    }

    if let Some(pk) = primary_key {
        constraints.push(format!("CONSTRAINT \"pk_{}\" PRIMARY KEY (\"{}\")", table, pk));
    }

    for c in constraints {
        lines.push(format!("    {}", c));
    }

    let mut out = String::new();
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS \"{}\" (\n", table));
    out.push_str(&lines.join(",\n"));
    out.push_str("\n);\n");
    Ok(out)
}

pub(crate) fn map_type_postgres(ty: &TypeSpec, field_name: &str) -> Result<(String, Vec<String>)> {
    let name = ty.name.as_str();
    let mut constraints = Vec::new();
    let sql_type = match name {
        "uuid" => "uuid".to_string(),
        "bool" => "boolean".to_string(),
        "json" => "jsonb".to_string(),
        "datetime" | "timestamp" => "timestamptz".to_string(),
        "bigint" => "bigint".to_string(),
        "int" => {
            if ty.args.len() == 2 {
                let min = ty.args[0];
                let max = ty.args[1];
                if min > max {
                    bail!("int(min,max) requires min <= max for field '{field_name}'");
                }
                constraints.push(format!(
                    "CONSTRAINT \"ck_{}_range\" CHECK (\"{}\" >= {} AND \"{}\" <= {})",
                    field_name, field_name, min, field_name, max
                ));
            }
            "integer".to_string()
        }
        "text" | "string" => {
            if ty.args.len() == 1 {
                format!("varchar({})", ty.args[0])
            } else {
                "text".to_string()
            }
        }
        "varchar" => {
            if ty.args.len() == 1 {
                format!("varchar({})", ty.args[0])
            } else {
                "varchar".to_string()
            }
        }
        "decimal" => {
            if ty.args.len() != 2 {
                bail!("decimal requires (precision,scale) for field '{field_name}'");
            }
            format!("numeric({},{})", ty.args[0], ty.args[1])
        }
        other => bail!("Unsupported type '{other}' for Postgres"),
    };

    Ok((sql_type, constraints))
}

pub(crate) fn to_snake_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for (idx, ch) in input.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if idx != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    #[test]
    fn generates_create_table_sql() {
        let src = r#"
            entity User {
                id uuid;
                age int(0,200);
                name text(50);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS \"user\""));
        assert!(sql.contains("\"id\" uuid"));
        assert!(sql.contains("\"name\" varchar(50)"));
        assert!(sql.contains("CHECK (\"age\" >= 0 AND \"age\" <= 200)"));
    }

    #[test]
    fn generates_unique_and_pk_and_nullability() {
        let src = r#"
            entity User {
                id uuid pk;
                email text unique;
                nickname text nullable;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("PRIMARY KEY"));
        assert!(sql.contains("UNIQUE"));
        assert!(sql.contains("\"nickname\" text NULL"));
        assert!(sql.contains("\"email\" text NOT NULL"));
    }

    #[test]
    fn string_alias_maps_to_text_or_varchar() {
        let src = r#"
            entity Todo {
                id int;
                title string(120);
                notes string;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("\"title\" varchar(120)"));
        assert!(sql.contains("\"notes\" text"));
    }
}
