use std::collections::HashMap;

use anyhow::{anyhow, bail, Result};

use crate::ast::{ModelDecl, ModelKind, OnDeleteAction, Program, TypeSpec};

pub fn generate_postgres_schema_sql(program: &Program) -> Result<String> {
    let mut out = String::new();
    out.push_str("-- Generated by jwc\n");

    let ctx_drivers = program
        .dbcontexts
        .iter()
        .map(|ctx| (ctx.name.to_lowercase(), ctx.driver.to_lowercase()))
        .collect::<HashMap<_, _>>();

    let entities = program
        .models
        .iter()
        .filter(|m| m.kind == ModelKind::Entity)
        .collect::<Vec<_>>();

    for (idx, entity) in entities.iter().enumerate() {
        let driver = resolve_entity_driver(program, entity, &ctx_drivers)?;
        if !driver.eq_ignore_ascii_case("postgres") {
            let ctx_name = entity.context_name.as_deref().unwrap_or("<implicit>");
            bail!(
                "Entity '{}' is bound to dbcontext '{}' with driver '{}', cannot generate Postgres SQL",
                entity.name,
                ctx_name,
                driver
            );
        }

        if idx != 0 {
            out.push('\n');
        }
        out.push_str(&generate_postgres_table_sql(entity)?);
        out.push('\n');
    }

    Ok(out)
}

fn resolve_entity_driver(
    program: &Program,
    entity: &ModelDecl,
    ctx_drivers: &HashMap<String, String>,
) -> Result<String> {
    if let Some(context_name) = &entity.context_name {
        let key = context_name.to_lowercase();
        let driver = ctx_drivers.get(&key).ok_or_else(|| {
            anyhow!(
                "Entity '{}' references unknown dbcontext '{}'",
                entity.name,
                context_name
            )
        })?;
        return Ok(driver.clone());
    }

    if program.dbcontexts.len() == 1 {
        return Ok(program.dbcontexts[0].driver.to_lowercase());
    }

    if program.dbcontexts.len() > 1 {
        bail!(
            "Entity '{}' must specify 'of <DbContextName>' when multiple dbcontexts are declared",
            entity.name
        );
    }

    Ok("postgres".to_string())
}

pub(crate) fn generate_postgres_table_sql(entity: &ModelDecl) -> Result<String> {
    let table = to_snake_case(&entity.name);
    let mut lines: Vec<String> = Vec::new();
    let mut constraints: Vec<String> = Vec::new();

    for field in &entity.fields {
        let (sql_type, extra_constraints) = map_type_postgres(&field.ty, &field.name)?;
        // `GENERATED BY DEFAULT AS IDENTITY` (not ALWAYS) so callers can
        // still write an explicit id when they need to (e.g. seed data
        // imports). NOT NULL is implied by IDENTITY but we keep it for
        // diff-stability with previously emitted migrations.
        let identity_suffix = if field.is_auto_increment {
            " GENERATED BY DEFAULT AS IDENTITY"
        } else {
            ""
        };
        let null_suffix = if field.is_nullable { "" } else { " NOT NULL" };
        lines.push(format!(
            "    \"{}\" {}{}{}",
            field.name, sql_type, identity_suffix, null_suffix
        ));
        if field.is_primary_key {
            constraints.push(format!("PRIMARY KEY (\"{}\")", field.name));
        }
        // A primary key is already unique; only emit a separate UNIQUE for
        // non-PK columns marked `unique`.
        if field.is_unique && !field.is_primary_key {
            constraints.push(format!("UNIQUE (\"{}\")", field.name));
        }
        if let Some(reference) = &field.references {
            let target_table = to_snake_case(&reference.entity);
            let mut fk = format!(
                "CONSTRAINT \"fk_{}_{}\" FOREIGN KEY (\"{}\") REFERENCES \"{}\" (\"{}\")",
                table, field.name, field.name, target_table, reference.column
            );
            match reference.on_delete {
                OnDeleteAction::NoAction => {}
                OnDeleteAction::Cascade => fk.push_str(" ON DELETE CASCADE"),
                OnDeleteAction::Restrict => fk.push_str(" ON DELETE RESTRICT"),
                OnDeleteAction::SetNull => fk.push_str(" ON DELETE SET NULL"),
            }
            constraints.push(fk);
        }
        constraints.extend(extra_constraints);
    }

    for c in constraints {
        lines.push(format!("    {}", c));
    }

    let mut out = String::new();
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS \"{}\" (\n", table));
    out.push_str(&lines.join(",\n"));
    out.push_str("\n);\n");
    for stmt in index_statements(entity) {
        out.push_str(&stmt);
    }
    Ok(out)
}

/// `CREATE INDEX` for every column marked `index`.
///
/// Emitted after the table so the statement is valid on both a fresh create
/// and a re-run. `pk` and `unique` columns are skipped: Postgres already
/// backs those with an index, and a second one would just cost writes.
pub(crate) fn index_statements(entity: &ModelDecl) -> Vec<String> {
    let table = to_snake_case(&entity.name);
    entity
        .fields
        .iter()
        .filter(|f| f.is_indexed && !f.is_primary_key && !f.is_unique)
        .map(|f| {
            format!(
                "CREATE INDEX IF NOT EXISTS \"ix_{}_{}\" ON \"{}\" (\"{}\");\n",
                table, f.name, table, f.name
            )
        })
        .collect()
}

pub(crate) fn map_type_postgres(ty: &TypeSpec, field_name: &str) -> Result<(String, Vec<String>)> {
    let name = ty.name.as_str();
    let mut constraints = Vec::new();
    let sql_type = match name {
        "uuid" => "uuid".to_string(),
        "bool" => "boolean".to_string(),
        "json" => "jsonb".to_string(),
        // `byte[]` / `bytes` syntax isn't reachable via the parser today
        // (entity `parse_type_spec` only accepts a bare identifier), so
        // the canonical entity-column spelling is `bytea`. Map all three
        // to Postgres `BYTEA` for forward-compat with whatever the
        // function-param parser produces.
        "bytea" | "bytes" | "byte[]" => "bytea".to_string(),
        "datetime" | "timestamp" => "timestamptz".to_string(),
        "bigint" => "bigint".to_string(),
        "int" => {
            if ty.args.len() == 2 {
                let min = ty.args[0];
                let max = ty.args[1];
                if min > max {
                    bail!("int(min,max) requires min <= max for field '{field_name}'");
                }
                constraints.push(format!(
                    "CONSTRAINT \"ck_{}_range\" CHECK (\"{}\" >= {} AND \"{}\" <= {})",
                    field_name, field_name, min, field_name, max
                ));
            }
            "integer".to_string()
        }
        "text" => {
            if ty.args.len() == 1 {
                format!("varchar({})", ty.args[0])
            } else {
                "text".to_string()
            }
        }
        "varchar" => {
            if ty.args.len() == 1 {
                format!("varchar({})", ty.args[0])
            } else {
                "varchar".to_string()
            }
        }
        "decimal" => {
            if ty.args.len() != 2 {
                bail!("decimal requires (precision,scale) for field '{field_name}'");
            }
            format!("numeric({},{})", ty.args[0], ty.args[1])
        }
        other => bail!("Unsupported type '{other}' for Postgres"),
    };

    Ok((sql_type, constraints))
}

pub(crate) fn to_snake_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for (idx, ch) in input.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if idx != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    #[test]
    fn generates_create_table_sql() {
        let src = r#"
            entity User {
                id uuid;
                age int(0,200);
                name text(50);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS \"user\""));
        assert!(sql.contains("\"id\" uuid"));
        assert!(sql.contains("\"name\" varchar(50)"));
        assert!(sql.contains("CHECK (\"age\" >= 0 AND \"age\" <= 200)"));
        assert!(sql.contains("\"id\" uuid NOT NULL"));
    }

    #[test]
    fn nullable_and_pk_are_generated() {
        let src = r#"
            entity Todo {
                id uuid pk;
                description text nullable;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("\"id\" uuid NOT NULL"));
        assert!(sql.contains("PRIMARY KEY (\"id\")"));
        assert!(sql.contains("\"description\" text"));
        assert!(!sql.contains("\"description\" text NOT NULL"));
    }

    #[test]
    fn autoincrement_emits_generated_identity_clause() {
        let src = r#"
            entity Note {
                id int pk autoincrement;
                title varchar(120);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(
            sql.contains("\"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
            "expected identity clause in DDL, got:\n{sql}"
        );
        assert!(sql.contains("PRIMARY KEY (\"id\")"));
    }

    #[test]
    fn autoincrement_on_non_int_type_fails_validation() {
        let src = r#"
            entity Note {
                id uuid pk autoincrement;
                title varchar(120);
            }
        "#;
        let program = parse_program(src).unwrap();
        let err = validate_program(&program).unwrap_err().to_string();
        assert!(
            err.contains("autoincrement is only valid on int / bigint"),
            "got: {err}"
        );
    }

    #[test]
    fn foreign_key_with_cascade_is_generated() {
        let src = r#"
            entity User {
                id uuid pk;
            }
            entity Post {
                id uuid pk;
                user_id uuid references User.id on delete cascade;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains(
            "CONSTRAINT \"fk_post_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"user\" (\"id\")"
        ));
        assert!(sql.contains("ON DELETE CASCADE"));
    }

    #[test]
    fn fk_to_unknown_entity_fails_validation() {
        let src = r#"
            entity Post {
                id uuid pk;
                user_id uuid references Ghost.id;
            }
        "#;
        let program = parse_program(src).unwrap();
        let err = validate_program(&program).unwrap_err().to_string();
        assert!(err.contains("unknown entity"));
    }

    #[test]
    fn bytea_column_is_generated() {
        let src = r#"
            entity Blob {
                id uuid pk;
                payload bytea;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(
            sql.contains("\"payload\" bytea NOT NULL"),
            "expected bytea column in DDL, got:\n{sql}"
        );
    }

    #[test]
    fn varchar_and_decimal_are_generated() {
        let src = r#"
            entity User {
                id uuid;
                email varchar(120);
                amount decimal(18,2);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("\"email\" varchar(120) NOT NULL"));
        assert!(sql.contains("\"amount\" numeric(18,2) NOT NULL"));
    }
}
