use std::collections::HashMap;

use anyhow::{anyhow, bail, Result};

use crate::ast::{ModelDecl, ModelKind, Program, TypeSpec};

pub fn generate_postgres_schema_sql(program: &Program) -> Result<String> {
    let mut out = String::new();
    out.push_str("-- Generated by jwc\n");

    let ctx_drivers = program
        .dbcontexts
        .iter()
        .map(|ctx| (ctx.name.to_lowercase(), ctx.driver.to_lowercase()))
        .collect::<HashMap<_, _>>();

    let entities = program
        .models
        .iter()
        .filter(|m| m.kind == ModelKind::Entity)
        .collect::<Vec<_>>();

    for (idx, entity) in entities.iter().enumerate() {
        let driver = resolve_entity_driver(program, entity, &ctx_drivers)?;
        if !driver.eq_ignore_ascii_case("postgres") {
            let ctx_name = entity.context_name.as_deref().unwrap_or("<implicit>");
            bail!(
                "Entity '{}' is bound to dbcontext '{}' with driver '{}', cannot generate Postgres SQL",
                entity.name,
                ctx_name,
                driver
            );
        }

        if idx != 0 {
            out.push('\n');
        }
        out.push_str(&generate_postgres_table_sql(entity)?);
        out.push('\n');
    }

    Ok(out)
}

fn resolve_entity_driver(
    program: &Program,
    entity: &ModelDecl,
    ctx_drivers: &HashMap<String, String>,
) -> Result<String> {
    if let Some(context_name) = &entity.context_name {
        let key = context_name.to_lowercase();
        let driver = ctx_drivers.get(&key).ok_or_else(|| {
            anyhow!(
                "Entity '{}' references unknown dbcontext '{}'",
                entity.name,
                context_name
            )
        })?;
        return Ok(driver.clone());
    }

    if program.dbcontexts.len() == 1 {
        return Ok(program.dbcontexts[0].driver.to_lowercase());
    }

    if program.dbcontexts.len() > 1 {
        bail!(
            "Entity '{}' must specify 'of <DbContextName>' when multiple dbcontexts are declared",
            entity.name
        );
    }

    Ok("postgres".to_string())
}

pub(crate) fn generate_postgres_table_sql(entity: &ModelDecl) -> Result<String> {
    let table = to_snake_case(&entity.name);
    let mut lines: Vec<String> = Vec::new();
    let mut constraints: Vec<String> = Vec::new();

    for field in &entity.fields {
        let (sql_type, extra_constraints) = map_type_postgres(&field.ty, &field.name)?;
        let null_suffix = if field.is_nullable { "" } else { " NOT NULL" };
        lines.push(format!("    \"{}\" {}{}", field.name, sql_type, null_suffix));
        if field.is_primary_key {
            constraints.push(format!("PRIMARY KEY (\"{}\")", field.name));
        }
        constraints.extend(extra_constraints);
    }

    for c in constraints {
        lines.push(format!("    {}", c));
    }

    let mut out = String::new();
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS \"{}\" (\n", table));
    out.push_str(&lines.join(",\n"));
    out.push_str("\n);\n");
    Ok(out)
}

pub(crate) fn map_type_postgres(ty: &TypeSpec, field_name: &str) -> Result<(String, Vec<String>)> {
    let name = ty.name.as_str();
    let mut constraints = Vec::new();
    let sql_type = match name {
        "uuid" => "uuid".to_string(),
        "bool" => "boolean".to_string(),
        "json" => "jsonb".to_string(),
        "datetime" | "timestamp" => "timestamptz".to_string(),
        "bigint" => "bigint".to_string(),
        "int" => {
            if ty.args.len() == 2 {
                let min = ty.args[0];
                let max = ty.args[1];
                if min > max {
                    bail!("int(min,max) requires min <= max for field '{field_name}'");
                }
                constraints.push(format!(
                    "CONSTRAINT \"ck_{}_range\" CHECK (\"{}\" >= {} AND \"{}\" <= {})",
                    field_name, field_name, min, field_name, max
                ));
            }
            "integer".to_string()
        }
        "text" => {
            if ty.args.len() == 1 {
                format!("varchar({})", ty.args[0])
            } else {
                "text".to_string()
            }
        }
        "varchar" => {
            if ty.args.len() == 1 {
                format!("varchar({})", ty.args[0])
            } else {
                "varchar".to_string()
            }
        }
        "decimal" => {
            if ty.args.len() != 2 {
                bail!("decimal requires (precision,scale) for field '{field_name}'");
            }
            format!("numeric({},{})", ty.args[0], ty.args[1])
        }
        other => bail!("Unsupported type '{other}' for Postgres"),
    };

    Ok((sql_type, constraints))
}

pub(crate) fn to_snake_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for (idx, ch) in input.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if idx != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    #[test]
    fn generates_create_table_sql() {
        let src = r#"
            entity User {
                id uuid;
                age int(0,200);
                name text(50);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS \"user\""));
        assert!(sql.contains("\"id\" uuid"));
        assert!(sql.contains("\"name\" varchar(50)"));
        assert!(sql.contains("CHECK (\"age\" >= 0 AND \"age\" <= 200)"));
        assert!(sql.contains("\"id\" uuid NOT NULL"));
    }

    #[test]
    fn nullable_and_pk_are_generated() {
        let src = r#"
            entity Todo {
                id uuid pk;
                description text nullable;
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("\"id\" uuid NOT NULL"));
        assert!(sql.contains("PRIMARY KEY (\"id\")"));
        assert!(sql.contains("\"description\" text"));
        assert!(!sql.contains("\"description\" text NOT NULL"));
    }

    #[test]
    fn varchar_and_decimal_are_generated() {
        let src = r#"
            entity User {
                id uuid;
                email varchar(120);
                amount decimal(18,2);
            }
        "#;
        let program = parse_program(src).unwrap();
        validate_program(&program).unwrap();
        let sql = generate_postgres_schema_sql(&program).unwrap();
        assert!(sql.contains("\"email\" varchar(120) NOT NULL"));
        assert!(sql.contains("\"amount\" numeric(18,2) NOT NULL"));
    }
}
