//! OpenAPI 3.1 generator — walks a validated `Program` and emits a JSON
//! document compatible with Swagger UI / Redoc / openapi-generator.
//!
//! Source of facts (no extra annotation needed in user code):
//! - Routes → paths + methods + operationId (handler fn name or
//!   synthesised from the path)
//! - `route GET "/users/{id}" -> getUser` + `function getUser(id: int)` →
//!   path parameter `id: integer` (no body)
//! - `route POST "/users" { validate body { ... } let req = body(); ... }`
//!   → requestBody with a JSON object whose fields come from the
//!   `validate body` block (each field becomes required/typed based on
//!   the rules present)
//! - `class Foo { name: string; age: int? }` → `components/schemas/Foo`
//! - `entity User of AppDb { ... }` → `components/schemas/User`
//! - HTTP-style response builders inside the body (`ok`, `created`,
//!   `notFound`, ...) → declared response codes (best-effort)
//!
//! What we DON'T do today (kept as TODOs for the next pass):
//! - Inferring response body shape from `return ok({...})` literals
//! - Auth (we'd need a `[Bearer]` / `[ApiKey]` annotation on routes;
//!   today we emit `security: []` so every endpoint is open in the doc)
//! - WebSocket routes — OpenAPI 3 doesn't model them. Omitted entirely.

use std::collections::{BTreeMap, BTreeSet};

use serde_json::{json, Map, Value};

use crate::ast::{
    Expr, FieldDecl, FunctionDecl, ModelDecl, ModelKind, Program, RouteDecl, RouteProtocol, Stmt,
    TypedParam, ValidateField, ValidateRule,
};

/// Top-level entry: build the OpenAPI document for `program`.
///
/// `info_title` / `info_version` come from the project manifest so the
/// generated `info` block matches what the user typed in `jwcproj`. The
/// generator never bails — invalid programs would have been rejected by
/// `validate_program` before reaching here; anything ambiguous degrades
/// to a permissive `Object` schema rather than crashing.
pub fn generate_openapi(program: &Program, info_title: &str, info_version: &str) -> Value {
    let schemas = build_component_schemas(program);
    let paths = build_paths(program);

    json!({
        "openapi": "3.1.0",
        "info": {
            "title":   info_title,
            "version": info_version,
            "description": "Generated by `jwc swagger` from JWC source — do not hand-edit.",
        },
        "paths": paths,
        "components": {
            "schemas": schemas,
        },
    })
}

fn build_component_schemas(program: &Program) -> Map<String, Value> {
    let mut out = Map::new();
    for model in &program.models {
        // Only top-level (root-namespace) models are surfaced — sub-namespace
        // classes are usually internal helpers and would noise the spec.
        if !model.namespace.is_empty() {
            continue;
        }
        out.insert(model.name.clone(), model_to_schema(model));
    }
    out
}

fn model_to_schema(model: &ModelDecl) -> Value {
    let mut props = Map::new();
    let mut required: Vec<Value> = Vec::new();
    for f in &model.fields {
        props.insert(f.name.clone(), field_to_schema(f));
        if !f.is_nullable {
            required.push(json!(f.name));
        }
    }
    let kind_str = match model.kind {
        ModelKind::Entity => "entity",
        ModelKind::Class => "class",
    };
    let mut schema = json!({
        "type": "object",
        "title": model.name,
        "description": format!("JWC {kind_str} `{}`", model.name),
        "properties": props,
    });
    if !required.is_empty() {
        schema["required"] = Value::Array(required);
    }
    schema
}

fn field_to_schema(f: &FieldDecl) -> Value {
    let inner = jwc_type_to_openapi(&f.ty.name);
    if f.is_nullable {
        // OpenAPI 3.1 supports `type: ["string", "null"]` shorthand; we
        // use `nullable: true` for 3.0 compatibility tooling out there.
        let mut s = inner;
        if let Value::Object(ref mut m) = s {
            m.insert("nullable".into(), Value::Bool(true));
        }
        s
    } else {
        inner
    }
}

/// Map JWC primitive / model name → OpenAPI 3 schema fragment.
fn jwc_type_to_openapi(name: &str) -> Value {
    match name.to_ascii_lowercase().as_str() {
        "string" | "str" | "text" | "varchar" => json!({ "type": "string" }),
        "int" | "integer" | "bigint" => json!({ "type": "integer", "format": "int64" }),
        "number" | "double" | "float" => json!({ "type": "number" }),
        "decimal" => json!({ "type": "string", "format": "decimal" }),
        "bool" | "boolean" => json!({ "type": "boolean" }),
        "uuid" => json!({ "type": "string", "format": "uuid" }),
        "datetime" | "timestamp" => json!({ "type": "string", "format": "date-time" }),
        "json" => json!({ "type": "object", "additionalProperties": true }),
        "bytes" | "byte[]" => json!({ "type": "string", "format": "byte" }),
        other => {
            // Anything else is assumed to be a component schema (entity or
            // class). The component map is built independently so dangling
            // refs are caught by `openapi-validator` rather than us.
            json!({ "$ref": format!("#/components/schemas/{}", other) })
        }
    }
}

fn build_paths(program: &Program) -> Map<String, Value> {
    // OpenAPI groups by `path`, so we collect into a (path → method → op) map first.
    let mut by_path: BTreeMap<String, BTreeMap<String, Value>> = BTreeMap::new();
    for route in &program.routes {
        if !matches!(route.protocol, RouteProtocol::Http) {
            continue; // skip WS / SSE — OpenAPI 3 doesn't cover them.
        }
        if !route.namespace.is_empty() {
            continue; // sub-namespace routes need a mount to be active.
        }
        let openapi_path = normalize_path(&route.path);
        let method = route.method.to_ascii_lowercase();
        let op = route_to_operation(program, route);
        by_path.entry(openapi_path).or_default().insert(method, op);
    }
    by_path
        .into_iter()
        .map(|(p, ops)| {
            let mut m = Map::new();
            for (method, op) in ops {
                m.insert(method, op);
            }
            (p, Value::Object(m))
        })
        .collect()
}

/// JWC's `{id}` placeholders happen to be the same shape OpenAPI uses,
/// so the conversion is a no-op for path segments. We just guarantee
/// a leading slash — the parser tolerates routes declared without one.
fn normalize_path(path: &str) -> String {
    if path.starts_with('/') {
        path.to_string()
    } else {
        format!("/{path}")
    }
}

fn route_to_operation(program: &Program, route: &RouteDecl) -> Value {
    let handler_fn = route
        .handler
        .as_deref()
        .and_then(|name| program.functions.iter().find(|f| f.name == name));

    let mut op = Map::new();
    op.insert(
        "operationId".into(),
        Value::String(operation_id(route, handler_fn)),
    );
    op.insert(
        "summary".into(),
        Value::String(format!("{} {}", route.method, normalize_path(&route.path))),
    );

    // Path parameters come from `{name}` segments. If the handler has a
    // typed param with the same name we pick up its type; otherwise default
    // to string.
    let path_params = extract_path_params(&route.path);
    let mut parameters: Vec<Value> = Vec::new();
    for pname in &path_params {
        let ty = handler_fn
            .and_then(|f| f.params.iter().find(|p| &p.name == pname))
            .and_then(|p| p.ty.as_deref())
            .unwrap_or("string");
        parameters.push(json!({
            "name":     pname,
            "in":       "path",
            "required": true,
            "schema":   jwc_type_to_openapi(ty),
        }));
    }
    // Query params: any `query_param("name", ...)` call inside the body.
    for qname in extract_query_params(&route.body) {
        parameters.push(json!({
            "name":     qname,
            "in":       "query",
            "required": false,
            "schema":   { "type": "string" },
        }));
    }
    if !parameters.is_empty() {
        op.insert("parameters".into(), Value::Array(parameters));
    }

    // Request body: derived from a `validate body { ... }` block when present,
    // else inferred from a `body()` / `let X = body()` call.
    if let Some(body_schema) = extract_request_body(&route.body) {
        op.insert(
            "requestBody".into(),
            json!({
                "required": true,
                "content": {
                    "application/json": { "schema": body_schema }
                }
            }),
        );
    }

    // Responses — gather every distinct status code mentioned via the
    // built-in response builders. Default to 200 with a permissive schema.
    let status_codes = extract_response_codes(&route.body);
    let mut responses = Map::new();
    if status_codes.is_empty() {
        responses.insert("200".into(), default_ok_response());
    } else {
        for code in &status_codes {
            responses.insert(code.to_string(), default_response_for(code));
        }
    }
    op.insert("responses".into(), Value::Object(responses));

    Value::Object(op)
}

fn operation_id(route: &RouteDecl, handler_fn: Option<&FunctionDecl>) -> String {
    if let Some(f) = handler_fn {
        return f.name.clone();
    }
    // Synthesise `getUsersById` style id from method + path.
    let mut out = route.method.to_ascii_lowercase();
    let segs: Vec<&str> = route.path.split('/').filter(|s| !s.is_empty()).collect();
    for seg in segs {
        let cleaned = seg.trim_matches(|c| c == '{' || c == '}');
        out.push_str(&capitalize(cleaned));
    }
    if out == route.method.to_ascii_lowercase() {
        out.push_str("Root");
    }
    out
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(first) => first
            .to_uppercase()
            .chain(c.flat_map(|ch| ch.to_lowercase()))
            .collect(),
    }
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = path.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'{' {
            if let Some(close) = path[i + 1..].find('}') {
                let name = &path[i + 1..i + 1 + close];
                if !name.is_empty() {
                    out.push(name.to_string());
                }
                i += close + 2;
                continue;
            }
        }
        i += 1;
    }
    out
}

fn extract_query_params(stmts: &[Stmt]) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for s in stmts {
        walk_stmt(s, &mut |e| {
            if let Expr::Call { name, args } = e {
                if name == "query_param" {
                    if let Some(Expr::Str(s)) = args.first() {
                        out.insert(s.clone());
                    }
                }
            }
        });
    }
    out
}

/// Surface a JSON-Schema for the request body. If a `validate body { ... }`
/// block exists, use its declared fields. Otherwise return `None` so the
/// operation has no `requestBody`.
fn extract_request_body(stmts: &[Stmt]) -> Option<Value> {
    for s in stmts {
        if let Stmt::ValidateBody { fields } = s {
            return Some(validate_block_to_schema(fields));
        }
    }
    None
}

fn validate_block_to_schema(fields: &[ValidateField]) -> Value {
    let mut props = Map::new();
    let mut required: Vec<Value> = Vec::new();
    for f in fields {
        let mut prop = jwc_type_to_openapi(infer_field_type(f));
        // Surface `pattern("...")` as `pattern` and length / min / max as
        // matching JSON-Schema keywords so the rendered docs include them.
        for rule in &f.rules {
            apply_rule_to_schema(rule, &mut prop);
        }
        props.insert(f.name.clone(), prop);
        if f.rules.iter().any(|r| matches!(r, ValidateRule::Required)) {
            required.push(json!(f.name));
        }
    }
    let mut schema = json!({
        "type": "object",
        "properties": props,
    });
    if !required.is_empty() {
        schema["required"] = Value::Array(required);
    }
    schema
}

/// Best-effort: numeric `min` / `max` rules imply an integer; anything else
/// defaults to string (covers `required` + length/pattern rules).
fn infer_field_type(f: &ValidateField) -> &'static str {
    for r in &f.rules {
        if matches!(r, ValidateRule::Min(_) | ValidateRule::Max(_)) {
            return "integer";
        }
    }
    "string"
}

fn apply_rule_to_schema(rule: &ValidateRule, prop: &mut Value) {
    let Value::Object(m) = prop else { return };
    match rule {
        ValidateRule::MinLength(n) => {
            m.insert("minLength".into(), json!(n));
        }
        ValidateRule::MaxLength(n) => {
            m.insert("maxLength".into(), json!(n));
        }
        ValidateRule::Min(s) => {
            if let Ok(n) = s.parse::<i64>() {
                m.insert("minimum".into(), json!(n));
            }
        }
        ValidateRule::Max(s) => {
            if let Ok(n) = s.parse::<i64>() {
                m.insert("maximum".into(), json!(n));
            }
        }
        ValidateRule::Pattern(p) => {
            m.insert("pattern".into(), Value::String(p.clone()));
        }
        ValidateRule::Required => {} // tracked separately in `required` list
    }
}

fn extract_response_codes(stmts: &[Stmt]) -> BTreeSet<u16> {
    let mut out = BTreeSet::new();
    for s in stmts {
        walk_stmt(s, &mut |e| {
            if let Expr::Call { name, args } = e {
                if let Some(code) = builtin_to_status(name) {
                    out.insert(code);
                } else if name == "statusCode" || name == "status_code" {
                    if let Some(Expr::Int(n)) = args.first() {
                        out.insert(*n as u16);
                    }
                }
            }
        });
    }
    out
}

fn builtin_to_status(name: &str) -> Option<u16> {
    match name {
        "ok" | "json" | "text" => Some(200),
        "created" => Some(201),
        "noContent" | "no_content" => Some(204),
        "badRequest" | "bad_request" => Some(400),
        "unauthorized" => Some(401),
        "forbidden" => Some(403),
        "notFound" | "not_found" => Some(404),
        "internalError" | "internal_error" => Some(500),
        _ => None,
    }
}

fn default_ok_response() -> Value {
    json!({
        "description": "OK",
        "content": {
            "application/json": {
                "schema": { "type": "object", "additionalProperties": true }
            }
        }
    })
}

fn default_response_for(code: &u16) -> Value {
    let desc = match code {
        200 => "OK",
        201 => "Created",
        204 => "No Content",
        302 => "Found (redirect)",
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        500 => "Internal Server Error",
        _ => "Response",
    };
    json!({
        "description": desc,
        "content": {
            "application/json": {
                "schema": { "type": "object", "additionalProperties": true }
            }
        }
    })
}

// =========================== Tree walk helpers ============================

fn walk_stmt<F: FnMut(&Expr)>(s: &Stmt, f: &mut F) {
    match s {
        Stmt::Let { value, .. }
        | Stmt::Assign { value, .. }
        | Stmt::FieldAssign { value, .. }
        | Stmt::Print(value)
        | Stmt::Expr(value)
        | Stmt::Return(Some(value)) => walk_expr(value, f),
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            walk_expr(cond, f);
            for s in then_body {
                walk_stmt(s, f);
            }
            if let Some(eb) = else_body {
                for s in eb {
                    walk_stmt(s, f);
                }
            }
        }
        Stmt::While { cond, body } => {
            walk_expr(cond, f);
            for s in body {
                walk_stmt(s, f);
            }
        }
        Stmt::ForIn { iter, body, .. } => {
            walk_expr(iter, f);
            for s in body {
                walk_stmt(s, f);
            }
        }
        Stmt::Try {
            body, catch_body, ..
        } => {
            for s in body {
                walk_stmt(s, f);
            }
            for s in catch_body {
                walk_stmt(s, f);
            }
        }
        Stmt::Transaction { body } => {
            for s in body {
                walk_stmt(s, f);
            }
        }
        _ => {}
    }
}

fn walk_expr<F: FnMut(&Expr)>(e: &Expr, f: &mut F) {
    f(e);
    match e {
        Expr::Call { args, .. } => {
            for a in args {
                walk_expr(a, f);
            }
        }
        Expr::Await(inner) | Expr::Neg(inner) | Expr::Not(inner) => walk_expr(inner, f),
        Expr::Add(a, b)
        | Expr::Sub(a, b)
        | Expr::Mul(a, b)
        | Expr::Div(a, b)
        | Expr::Mod(a, b)
        | Expr::Eq(a, b)
        | Expr::Neq(a, b)
        | Expr::Lt(a, b)
        | Expr::Lte(a, b)
        | Expr::Gt(a, b)
        | Expr::Gte(a, b)
        | Expr::And(a, b)
        | Expr::Or(a, b) => {
            walk_expr(a, f);
            walk_expr(b, f);
        }
        Expr::ObjectLit(pairs) => {
            for (_, v) in pairs {
                walk_expr(v, f);
            }
        }
        _ => {}
    }
}

// `TypedParam` not directly used in this module today — kept the import
// for the operationId / param-typing helpers above.
#[allow(dead_code)]
fn _force_use(_p: TypedParam) {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_program, validate_program};

    fn build(src: &str) -> Value {
        let p = parse_program(src).expect("parse");
        validate_program(&p).expect("validate");
        generate_openapi(&p, "test", "0.0.0")
    }

    #[test]
    fn empty_program_has_openapi_skeleton() {
        let doc = build(r#"function main() { print("hi"); }"#);
        assert_eq!(doc["openapi"], "3.1.0");
        assert_eq!(doc["info"]["title"], "test");
        assert!(doc["paths"].as_object().unwrap().is_empty());
    }

    #[test]
    fn route_with_path_param_emits_parameter() {
        let doc = build(
            r#"
            function getUser(id: int) { return ok({ id: id }); }
            route GET "/users/{id}" -> getUser;
            function main() { print("ok"); }
        "#,
        );
        let op = &doc["paths"]["/users/{id}"]["get"];
        assert_eq!(op["operationId"], "getUser");
        let params = op["parameters"].as_array().unwrap();
        assert_eq!(params.len(), 1);
        assert_eq!(params[0]["name"], "id");
        assert_eq!(params[0]["in"], "path");
        assert_eq!(params[0]["schema"]["type"], "integer");
    }

    #[test]
    fn validate_body_block_lands_in_request_body() {
        let doc = build(
            r#"
            route POST "/users" {
                validate body {
                    name:  required, minLength(2), maxLength(64);
                    email: required, pattern("^[^@]+@[^@]+$");
                }
                let req = body();
                return created(req);
            }
            function main() { print("ok"); }
        "#,
        );
        let body =
            &doc["paths"]["/users"]["post"]["requestBody"]["content"]["application/json"]["schema"];
        let props = body["properties"].as_object().unwrap();
        assert!(props.contains_key("name"));
        assert!(props.contains_key("email"));
        let req: Vec<String> = body["required"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert!(req.contains(&"name".to_string()));
        assert!(req.contains(&"email".to_string()));
        assert_eq!(props["name"]["minLength"], 2);
        assert_eq!(props["email"]["pattern"], "^[^@]+@[^@]+$");
    }

    #[test]
    fn class_becomes_component_schema() {
        let doc = build(
            r#"
            class UserView {
                id    string;
                name  string;
                age   int;
            }
            function main() { print("ok"); }
        "#,
        );
        let schema = &doc["components"]["schemas"]["UserView"];
        assert_eq!(schema["type"], "object");
        let props = schema["properties"].as_object().unwrap();
        assert_eq!(props["age"]["type"], "integer");
        let req: Vec<String> = schema["required"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert!(req.contains(&"id".to_string()));
    }

    #[test]
    fn response_codes_picked_up_from_builders() {
        let doc = build(
            r#"
            route POST "/maybe" {
                if (true) { return created({ id: 1 }); }
                return badRequest({ error: "x" });
            }
            function main() { print("ok"); }
        "#,
        );
        let responses = doc["paths"]["/maybe"]["post"]["responses"]
            .as_object()
            .unwrap();
        assert!(responses.contains_key("201"));
        assert!(responses.contains_key("400"));
    }
}
